### ISSUE TITLE
Copilot network connection error.

### ISSUE THREAD

**Issue by Qasszls** [microsoft/vscode-copilot-release#10]
- VS Code Version: 1.79.0-insider(Universal)
- OS Version: Darwin arm64 21.4.0
- Logs:
`2023-05-17 11:38:44.654 [error] [Extension Host] [ERROR] [default] [2023-05-17T03:38:44.651Z] Request Error: read ECONNRESET
2023-05-17 11:38:44.655 [error] [Extension Host] FetchError: read ECONNRESET
    at C (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:2:35897)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:2:40053
    at c.fetch (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:997288)
    at t.OpenAIChatMLFetcher.fetchWithParameters (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:944558)
    at t.OpenAIChatMLFetcher.fetchAndStreamChat (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:942819)
    at t.ChatMLFetcher.fetch (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:930617)
    at t.ChatMLFetcher.fetchResponse (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:930460)
    at t.CopilotInteractiveSession.fetchConversationResponse (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:877041)
    at t.CopilotInteractiveSession._provideResponseWithProgress (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:876632)
    at t.CopilotInteractiveSession.provideResponseWithProgress (/Users/liushangzuo/.vscode-insiders/extensions/github.copilot-chat-0.1.2023051601/dist/extension.js:8:874400)
    at A.$provideReply (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:123500)`

Steps to Reproduce:

1.Start a conversation with copilot; 
2.Do something else, don't interact with it, and don't toggle sidebar extensions. ; 
3.Wait about 15 minutes for the link to fail

**Comment by Qasszls** [comment]
It looks like a problem with a broken network connection. In theory, even if the intermediate network connection is down, can you help me automatically reconnect when I re-initiate the session 😄

**Comment by zy6p** [comment]
I encountered the same issue. The internet connection is too unstable and it keeps loading in circles, unable to refresh.

**Comment by digitarald** [comment]
Waiting 15 minutes to fail on bad connection isn't great. At least we should catch those issues to retry or time out.

**Comment by TimothyFran** [comment]
Having same problem, need to reload window each time I want to use chat and can't use suggestions

**Comment by lramos15** [comment]
Are you still experiencing this issue in the latest versions?
