### ISSUE TITLE
Please add delay before inline suggestions

### ISSUE THREAD

**Issue by daniel-tonic** [microsoft/vscode-copilot-release#1013]
During a recent frustrating moment I was trying to add additional tabs to a document.  Unfortunately every time I would hit tab, CoPilot saw it as an opportunity to suggest something.  Since I was hitting tab repeatedly to try to pad something, it would then automatically accept a suggestion when that wasn't my intention at all.  In the end I had to accept the suggestion, then go back and put tabs in front of that, then delete the suggestion so I could do my work.  I think a delay after a tab is hit to see if the user is pressing it multiple times would make sense to avoid this frustrating experience of trying to hit tabs before CoPilot decides to suggest and accept something.

Thank you

**Comment by barxilly** [comment]
If anything I think it should just be a changeable extension setting

**Comment by gpaddis** [comment]
@daniel-tonic As a workaround, you can disable the inline suggestions:

![grafik](https://github.com/user-attachments/assets/0e4518cf-ad77-4f90-8ed5-8386166f48e9)

Then you can assign a custom keyboard shortcut to "Trigger inline suggestion" (I use CTRL+SHIFT+S)

![grafik](https://github.com/user-attachments/assets/70277de5-bc31-4693-8706-7de112a2990c)

This way, you can decide when you need a suggestion and trigger it manually.

**Comment by isidorn** [comment]
Fair feature request but nothing that we have on the immediate plan.

**Comment by yannmichaux** [comment]
+1 on that one, it's hellish not being able to think for a few moments without Copilot's suggestion, let me think for a few moments, damn !

**Comment by Sharondio** [comment]
Please please please implement this. A configurable delay would be the perfect middle-ground between no suggestions, and immediate suggestions on every keystroke.

**Comment by joerohde** [comment]
This has become even more problematic with syntax color highlighting (yes, I've turned it off).   But if I'm thinking sometimes it feels like I'm looking at actual changed code because it isn't dim enough.  Being able to delay to N ms would go a long way.

**Comment by SponeKiller** [comment]
Also please add this feature, autosuggestion is currently tooo fast and istead of helping its getting annoying,

**Comment by abkarcher** [comment]
Hello,

I think I have to add another vote here; the increase of suggestion speed over time makes this feel like a usability regression fix as much as a feature request.

Generally, having no or slow suggestions seems much less inconvenient than having instantaneous suggestions that are not relevant. They shift the entire screen around and interrupt work. It would be preferable that the model spend the extra time checking its confidence in the suggestions.

(Regardless, thanks for all the great work on these features!)

**Comment by jmesterh** [comment]
For the love of God, please add a configurable delay to the suggestions. It's nearly impossible to hit tab in Python without copilot adding a paragraph of gibberish code. Let me think!

**Comment by Sacs** [comment]
One other workaround that we can use in the short term is toggling auto-completion on and off. The setting in keybinds is labelled "GitHub Copilot: Toggle (Enable/Disable) Completions"

**Comment by sirwolfgang** [comment]
A setting like `github.copilot.editor.delayAutoCompletions = 15000` ms or something would be helpful

**Comment by pkkid** [comment]
This is actually causing bugs in my code because the auto-completion is so fast that I often miss that it completely changed some of my code when moving my cursor around the screen. I bring it up because the following example is happening to me multiple times a week, and I feel the too fast speed to suggest completions is 100% the cause.

Providing this story as an example of the pain this is causing us. Not trying to be rude by explaining it. -- Anyway, I just spent 30 minutes trying to figure out why an exception was happening in my code. In the end, it was Copilot. I had the following schema definition in Django, and I must have put my cursor in the wrong spot, and accidentally accepted a change copilot was suggesting. This happens to me more often that it should. Usually I catch it, and its just a minor annoyance. Other times, like this one, I spend 30m trying to figure what I think I did wrong, only to get annoyed that it wasn't me at all, but the IDE being too eager to make me accept suggestions and I happened to miss it.

```python
class CategorySchema(Schema):
    id: Optional[int] = Field(None, description='Internal category id')
    url: Optional[str] = Field(None, description='URL for the category resource')
    name: str = Field(..., description='Name of this cateogry')
    exclude: Optional[bool] = Field(None, description='Exclude this category from reports')
    sortid: Optional[int] = Field(None, description='User sort id when listing categories')
```

Was changed to:
```python
class CategorySchema(Schema):
    id: Optional[int] = Field(None, description='Internal category id')
    url: Optional[str] = Field(None, description='URL for the category resource')
    name: str = Field(..., description='Name of this cateogry')
    exclude: Optional[bool] = Field(NotImplemented, description='Exclude this category from reports')
    sortid: Optional[int] = Field(None, description='User sort id when listing categories')
```

Normally, I can spot exception and fix them pretty easy, but Django was spitting this out (which was no help). So I got to spend time going line-by-line to figure out what the heck happend.
```python
Traceback (most recent call last):
  File "/home/pkkid/Projects/site/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self.core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkkid/Projects/site/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 55, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__
```

Can you spot the bug? In the context of this change in a larger file, I couldn't. Not until I went line by line. Copilot suggested (and I accidentally accepted) a change of the `None` keyword to `NotImplemented`.

Please, please reconsider adding a delay option in the near future.

**Comment by fvwanja** [comment]
+1

**Comment by hallatore** [comment]
Suggestions in the editor the last couple of weeks is starting to get in the way. Finding myself hitting esc 90% of the time now.
I feel the issue is a combination of timing and poor suggestion quality. I'd rather get a fewer suggestions with a delay.

Right now it feels like an annoying person that never lets you finish your sentence before it interrupts you. It's supposed to be a suggestion. Suggestions are supposed to come at a pause of thought! Not 20ms after I stopped typing something.

**Comment by quangv** [comment]
could be related: https://github.com/orgs/community/discussions/17670

**Comment by hallatore** [comment]
I haven't tested it, but for suggestions there is `editor.quickSuggestionsDelay` already. (It's 10 ms by default, but you can set it to 2000 etc)
Should copilot adhere to the same setting, or introduce a similar one?

**Comment by bakura10** [comment]
Yes, please add this. This is getting so frustratring, I end up adding code that I don't want all the time.

**Comment by ceri-waterscreative** [comment]
+1

**Comment by pkkid** [comment]
I feel like I am seeing this complaint come up more and more. Maybe putting it all out there will help get some attention behind this request? All of these posts showcase the issue or are looking for a workaround because of this issue.

1. https://github.com/microsoft/vscode-copilot-release/issues/11895 (June 8, 2025)
2. https://github.com/microsoft/vscode-copilot-release/issues/11105 (May 29, 2025)
3. https://github.com/microsoft/vscode-copilot-release/issues/1355 (June 29, 2024)
4. https://github.com/microsoft/vscode-copilot-release/issues/13340 (June 24, 2025)
5. https://github.com/microsoft/vscode-copilot-release/issues/8495 (Apr 24, 2025)
6. [Can I make copilot less intrusive?](https://github.com/orgs/community/discussions/75309) (Nov 12, 2023)
7. [Turn off Copilot Temporarily for inline Suggestions in Visual Studio](https://github.com/orgs/community/discussions/138225) (Sept 9, 2024)
8. Reddit: [Slow down hyperactive Github Copilot?](https://www.reddit.com/r/vscode/comments/1m4k46r/slow_down_hyperactive_github_copilot/) (July 20, 2025)
9. Reddit: [Whats your preferred shortcut for disabling Copilot?](https://www.reddit.com/r/vscode/comments/1mdahlp/whats_your_preferred_shortcut_for_disabling/) (July 30, 2025)

**Comment by harley-codes** [comment]
Bump!

**Comment by minsa110** [comment]
Thank you for all your feedback and for the bump! We're actively working on this and changes will land soon on VS Code Insiders to enable delay setting configuration. We'll keep you posted!
