### ISSUE TITLE
error

### ISSUE THREAD

**Issue by parmiiida** [microsoft/vscode-copilot-release#1023]
chunk-NCXG4GXZ.js?v=b3da840d:19409 Uncaught TypeError: Cannot read properties of undefined (reading 'params')

**Comment by jrieken** [comment]
@parmiiida Please attach more details about this error

**Comment by NurRobin** [comment]
Guessing I have a similar/the same error:

```
2024-03-20 22:46:13.570 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-03-20 22:46:13.570 [info] [chat fetch] modelMaxPromptTokens 7168
2024-03-20 22:46:13.570 [info] [chat fetch] modelMaxResponseTokens 4096
2024-03-20 22:46:13.570 [info] [chat fetch] chat model gpt-3.5-turbo
2024-03-20 22:46:14.144 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 573 ms
2024-03-20 22:46:14.147 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-03-20 22:46:14.147 [info] [streamChoices] request done: requestId: [ee30de4f-4bd3-42d5-bb9b-913ad8921d4c] responseId: [ee30de4f-4bd3-42d5-bb9b-913ad8921d4c] model deployment ID: [x4dff5e5d11fc]
2024-03-20 22:46:15.759 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,wasp-lang/wasp
2024-03-20 22:46:15.760 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,Jvr2022/apkupdater
2024-03-20 22:46:15.760 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,Meisolsson/PocketHub
2024-03-20 22:46:15.760 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,git-for-windows/git
2024-03-20 22:46:15.760 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,Meisolsson/PocketHub
2024-03-20 22:46:15.760 [info] [CodeSearchChunkSearch] Could not find workspace folder for repo,donnemartin/system-design-primer
2024-03-20 22:46:16.148 [info] [extension] TypeError: Cannot read properties of undefined (reading 'kind')
    at /home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:829:488
    at Array.forEach (<anonymous>)
    at po.prepare (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:829:411)
    at /home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:758:4616
    at Array.map (<anonymous>)
    at gt._processPromptPieces (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:758:4562)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at gt.render (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:758:5475)
    at t.buildPrompt (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:763:1863)
    at OS._provideResponseWithProgress (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:859:813)
    at OS.provideResponseWithProgress (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:857:1830)
    at r.z (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-chat-0.14.2024032004/dist/extension.js:871:859)
    at n.$invokeAgent (/home/ubuntu/.vscode-server-insiders/cli/servers/Insiders-342d7a0c0ceec77ace1a4b50c1da809c64d224a9/server/out/vs/workbench/api/node/extensionHostProcess.js:154:43824)
```

To my knowledge, this only happens when using #codebase or @workspace.

Using version v0.14.2024032004 (pre-release)

**Comment by jrieken** [comment]
not actionable
