### ISSUE TITLE
Chat 0.13.1 doesn't support python 3.6: Error on conversation request: TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by naphystart** [microsoft/vscode-copilot-release#1040]
- VS Code Version:  1.87.1
- OS Version: win10 19044.2130
- Logs: `2024-03-15 15:43:27.732 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-03-15 15:43:27.732 [info] [chat fetch] modelMaxPromptTokens 3072
2024-03-15 15:43:27.732 [info] [chat fetch] modelMaxResponseTokens 2121
2024-03-15 15:43:27.732 [info] [chat fetch] chat model gpt-4
2024-03-15 15:43:29.802 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2069 ms
2024-03-15 15:43:29.804 [info] [streamChoices] request done: requestId: [6816d092-be04-4d32-a5a0-f0beed407053] responseId: [6816d092-be04-4d32-a5a0-f0beed407053] model deployment ID: []
2024-03-15 15:43:29.815 [info] [extension] Error on conversation request: TypeError: e.replace is not a function
    at String.replaceAll (c:\Users\hello\.vscode\extensions\ms-python.python-2022.8.1\out\client\extension.js:2:148794)
    at t.logProgress (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:670:148)
    at Object.report (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:798:1864)
    at aS.applyDeltaToProgress (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:797:1415)
    at c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:797:2297
    at Array.forEach (<anonymous>)
    at aS.checkForKeyWords (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:797:2285)
    at aS.applyDelta (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:797:2477)
    at aS.apply (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:797:1246)
    at m.accessor.get.fetchOne.temperature (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:800:2896)
    at m (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:1018:2760)
    at t.processSSEInner (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:1018:3050)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.processSSE (c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:1018:646)
    at c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:118:90873
    at c:\Users\hello\.vscode\extensions\github.copilot-chat-0.13.1\dist\extension.js:118:90422`

Steps to Reproduce:

1. install python extension v2022.8.1 (which support python 3.6)
2. install copilot chat v0.13.1
3. chat

**Comment by lyhellcat** [comment]
try to update python extension version to `v2024.2.1` can fix this problem.

**Comment by lramos15** [comment]
Closing due to being a python extension bug
