### ISSUE TITLE
Copilot Chat Failing with Proxy Due to Unknown Kerberos Issue

### ISSUE THREAD

**Issue by ryorke1** [microsoft/vscode-copilot-release#1046]
I am having an issue where Copilot and Copilot Chat fail to fetch results after a few minutes of VS Code being opened while connected to a corporate proxy (using an Enterprise Copilot License). If I close and reopen VS Code (or VS COde Insider) the issue goes away briefly and I am able to get results both in chat as well as in code suggestions. I have no Kerberos configurations in place that should be causing this issue not any SPNs configured in VS Code settings. If I go off the proxy and on direct internet instead behind corporate VPN (not ideal) I am able to work with copilot without issues. This was working before however I am not sure when this broke as I had about a month of downtime. 

- VS Code Version: 1.88.0-insider (Universal) & 1.87.2 (Universal)
- OS Version: Mac OS X Sonoma 14.4 (M1 Mac)
- Logs:
```
2024-03-15 11:03:46.045 [info] [FetcherService] Using Helix fetcher
2024-03-15 11:03:46.045 [info] [gitExtensionService] Initializing Git extension service.
2024-03-15 11:03:46.045 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-03-15 11:03:46.045 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-03-15 11:03:46.045 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-03-15 11:03:47.022 [info] [auth] Logged in as MYCOPILOTUSER
2024-03-15 11:03:47.804 [info] [chat] copilot token chat_enabled: true
2024-03-15 11:03:47.804 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-03-15 11:03:47.804 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-03-15 11:03:47.813 [info] [auth] Got Copilot token for MYCOPILOTUSER
2024-03-15 11:04:20.793 [info] [auth] Logged in as MYCOPILOTUSER
2024-03-15 11:04:20.794 [info] [auth] Logged in as MYCOPILOTUSER
2024-03-15 11:04:21.836 [info] [chat] copilot token chat_enabled: true
2024-03-15 11:04:21.836 [info] [auth] Got Copilot token for MYCOPILOTUSER
2024-03-15 11:04:21.928 [info] [chat] copilot token chat_enabled: true
2024-03-15 11:04:21.928 [info] [auth] Got Copilot token for MYCOPILOTUSER
2024-03-15 11:05:34.264 [info] [FetcherService] Using Helix fetcher
2024-03-15 11:05:34.264 [info] [gitExtensionService] Initializing Git extension service.
2024-03-15 11:05:34.866 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-03-15 11:05:34.866 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-03-15 11:05:34.866 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-03-15 11:05:35.214 [info] [auth] Logged in as MYCOPILOTUSER
2024-03-15 11:05:36.170 [info] [chat] copilot token chat_enabled: true
2024-03-15 11:05:36.170 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-03-15 11:05:36.170 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-03-15 11:05:36.184 [info] [auth] Got Copilot token for MYCOPILOTUSER
2024-03-15 11:05:54.349 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-03-15 11:05:54.350 [info] [chat fetch] modelMaxPromptTokens 3072
2024-03-15 11:05:54.350 [info] [chat fetch] modelMaxResponseTokens 3692
2024-03-15 11:05:54.350 [info] [chat fetch] chat model gpt-4
2024-03-15 11:05:54.528 [info] [extension] Error on conversation request: oie:  Miscellaneous failure (see text): Server (krbtgt/A.EXAMPLE.COM@B.EXAMPLE.COM) unknown while looking up 'HTTP/proxy.example.com@A.EXAMPLE.COM' (cached result, timeout in 1197 sec) (negative cache)
    at D3e (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:94:29560)
    at rht (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:94:31585)
    at hU.fetch (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:1107:30801)
    at ZDe (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:1100:7970)
    at U0.fetchMany (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:1100:12960)
    at U0.fetchOne (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:1100:12042)
    at RS.fetchConversationResponse (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:895:2481)
    at RS._provideResponseWithProgress (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:895:1536)
    at RS.provideResponseWithProgress (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:893:1830)
    at r.z (/Users/MYCOPILOTUSER/.vscode-insiders/extensions/github.copilot-chat-0.14.2024031501/dist/extension.js:905:773)
    at i.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:43832)
```

Steps to Reproduce:

1. Configure proxy within VSCode settings and restart VS Code
2. Ask chat for some information. Initially this works. 
3. Wait a few minutes and try asking another question. Receive the error log above and an error telling me to "Please check your firewall rules and network connection then try again. Error Code: undefined."

**Comment by ryorke1** [comment]
Hi @alexdima. Any thoughts/updates on this issue?

**Comment by alexdima** [comment]
@ryorke1 Could you please try configuring:
```
"github.copilot.advanced": {
  "debug.useElectronFetcher": true
}
```
