### ISSUE TITLE
Whenever I use the chat function, I get the response "r.report is not a function"

### ISSUE THREAD

**Issue by honjes** [microsoft/vscode-copilot-release#1129]
Whenever I use the chat function, I get the response "_r.report is not a function_"

- VS Code Version: 1.89.0-insider
- Copilot Add-on Version: v1.180.0
- Copilot Chat Add-on Version: v0.14.1
- OS Version: Windows_NTx64 10.0.19045
- Logs:
```
2024-04-14 09:57:00.406 [info] [FetcherService] Using Helix fetcher
2024-04-14 09:57:00.406 [info] [gitExtensionService] Initializing Git extension service.
2024-04-14 09:57:00.406 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-14 09:57:00.406 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-14 09:57:00.406 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-14 09:57:00.616 [info] [auth] Logged in as _
2024-04-14 09:57:00.917 [info] [chat] copilot token chat_enabled: true
2024-04-14 09:57:00.918 [info] [chat] Registration of interactive providers failed:,TypeError: le.interactive.registerInteractiveSessionProvider is not a function
2024-04-14 09:57:00.918 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-14 09:57:00.918 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-04-14 09:57:00.931 [info] [auth] Got Copilot token for honjes
2024-04-14 09:57:20.683 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-14 09:57:20.684 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-14 09:57:20.684 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-14 09:57:20.684 [info] [chat fetch] chat model gpt-4
2024-04-14 09:57:22.001 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1316 ms
2024-04-14 09:57:22.820 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-14 09:57:22.821 [info] [streamChoices] request done: requestId: [35e13c78-4ca1-4bfc-8cac-3ee00b7c1e7d] responseId: [35e13c78-4ca1-4bfc-8cac-3ee00b7c1e7d] model deployment ID: [xd564f7006c5c]
2024-04-14 09:57:22.823 [info] [extension] TypeError: r.report is not a function
    at Object.report (c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:855:1767)
    at iE.applyDeltaToProgress (c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:1498)
    at c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:2590
    at c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:2343
    at Array.forEach (<anonymous>)
    at iE.checkForKeyWords (c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:2331)
    at iE.applyDelta (c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:2525)
    at iE.doProcessResponse (c:\Users\_\.vscode-insiders\extensions\github.copilot-chat-0.14.1\dist\extension.js:854:1312)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Steps to Reproduce:

1. open VS Code
2. send message in GitHub copilot chat

**Comment by argonzalez2016** [comment]
Same exact issue here

**Comment by JohnHuang-CT** [comment]
the same question

**Comment by taurisjoe** [comment]
> I also had this problem, but switching to the pre-release of GitHub.copilot-chat fixed the problem.

This did not solve the problem for me.  r.report is still not a function.

**Comment by Nicholas-Autio-Mitchell** [comment]
When using vscode devcontainers, there is currently no way to enforce installation of pre-release versions of extensions via the `devcontainer.json` config file. E.g. using "github.copilot-chat@prerelease" does not work.

It is unfortunately necessary to either manually install it in the extensions menu (and reload the window), or implement a nasty workaround e.g. via the `postCreateCommand`.

**Comment by roblourens** [comment]
When using VS Code Insiders, please use the latest pre-release version of the Copilot Chat extension

**Comment by epicwhale** [comment]
@roblourens  Even though I'm using the pre release version, every time the container is built, it installs a non pre release version of the extension, so I'm back to this issue with every build. How do we enforce a dev container with vs insider to always use the pre release version of the extension? I'm lost. It's leading to various other side effects other than this.

**Comment by Nicholas-Autio-Mitchell** [comment]
@epicwhale
> How do we enforce a dev container with vs insider to always use the pre release version of the extension?

You cannot, it is not currently supported by vscode devcontainers. See [my comment above](https://github.com/microsoft/vscode-copilot-release/issues/1129#issuecomment-2065586813).

This is technically not a shortcoming of the copilot chat extension, although given how often a devcontainer typically gets rebuilt, this is very inconvenient.

**Comment by roblourens** [comment]
I'm not the devcontainer expert but does this format work for you?

https://github.com/microsoft/vscode/issues/149383#issuecomment-1132192731

**Comment by epicwhale** [comment]
> I'm not the devcontainer expert but does this format work for you?
> 
> [microsoft/vscode#149383 (comment)](https://github.com/microsoft/vscode/issues/149383#issuecomment-1132192731)

Nope, this does not seem to do anything for me. Still installs release version of extension.

**Comment by roblourens** [comment]
cc @sandy081 @bamurtaugh is it possible to auto-install the pre-release version of an extension in a devcontainer?

**Comment by Nicholas-Autio-Mitchell** [comment]
@roblourens - please read above comments. I have already posted twice that **it is not possible** to configure prerelease versions of extensions in devcontainers.

**Comment by sandy081** [comment]
It should work, Please open an issue with steps to reproduce. Thanks.

**Comment by MalteMagnussen** [comment]
Same exact issue occurring for me as OP. I just ask the chat, and it happens. 

![image](https://github.com/microsoft/vscode-copilot-release/assets/11192971/ff7c248c-91cf-4118-bf2f-f6b29f09588d)

**Comment by bannsec** [comment]
Same problem. I open an ssh remote workstation in vscode. Most plugins seem to work fine but i get the exact same chat error when trying to even say "hello". Very annoying.

**Comment by Nicholas-Autio-Mitchell** [comment]
@bannsec @MalteMagnussen
Please read previous comments. It is a known issue/bug with workarounds.

**Comment by shubhamshr777** [comment]
I am getting the same issue. (r.report is not a function)

**Comment by Kukuster** [comment]
the most recent "latest/stable" update `b58957e6` of vscode on snap on ubuntu just fixed the issue for me, without workarounds
```
snap refresh code
```
just came out on May 2nd

**Comment by MalteMagnussen** [comment]
> @bannsec @MalteMagnussen Please read previous comments. It is a known issue/bug with workarounds.

Updating my extensions and restart VSCode fixed it. Thanks.

**Comment by heinosasshallik** [comment]
Updating my extensions fixed it. A restart was not necessary.
