### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#1159]
- VS Code Version:1.88.1
- OS Version:10
- Logs:

Steps to Reproduce:

1. install github copilot chat in docker vs code dev container
2. leave for an extended period (no idea how long i left it for a few weeks)
3. go into container and try and use extension

2024-04-26 14:01:04.435 [error] [default] Error sending telemetry FetchError: certificate has expired
    at fetch (/home/vscode/.vscode-server/extensions/github.copilot-1.184.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/vscode/.vscode-server/extensions/github.copilot-1.184.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at WU.fetch (/home/vscode/.vscode-server/extensions/github.copilot-1.184.0/lib/src/network/helix.ts:78:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'CERT_HAS_EXPIRED',
  errno: undefined,
  erroredSysCall: undefined
  
  Removing extension and reinstalling doesnt seem to work

**Comment by craftzneko** [comment]
Though there was a cert used by copilot but think its my cert in the container
