### ISSUE TITLE
Invalid copilot token: missing token: 403. (And, "Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date.")

### ISSUE THREAD

**Issue by SeleznevAS-dev** [microsoft/vscode-copilot-release#1188]
- VS Code Version: 1.89.0
- OS Version: Windows 11 23H2 22631.3527
- Logs: 
2024-05-07 16:56:26.577 [info] [FetcherService] Using Helix fetcher
2024-05-07 16:56:26.577 [info] [gitExtensionService] Initializing Git extension service.
2024-05-07 16:56:26.577 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-05-07 16:56:26.577 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-05-07 16:56:26.577 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-05-07 16:56:26.704 [info] [FetcherService] Using Electron fetcher
2024-05-07 16:56:26.711 [info] [auth] Logged in as San1k-02
2024-05-07 16:56:27.088 [info] [auth] Invalid copilot token: missing token: 403 
2024-05-07 16:56:27.090 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-07 16:56:27.093 [info] [auth] Logged in as San1k-02
2024-05-07 16:56:27.402 [info] [auth] Invalid copilot token: missing token: 403 
2024-05-07 16:56:27.517 [info] [RemoteAgents] Invalid remote agent response: access denied
 (SyntaxError: Unexpected token 'a', "access denied
" is not valid JSON)

Steps to Reproduce:

1. Open VS Code
2. Use GitHub Copilot Chat

**Comment by San1k-02** [comment]
With release version (v.0.15.0) of Chat logs are:
2024-05-07 16:59:44.298 [info] [FetcherService] Using Helix fetcher
2024-05-07 16:59:44.298 [info] [gitExtensionService] Initializing Git extension service.
2024-05-07 16:59:44.298 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-05-07 16:59:44.298 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-05-07 16:59:44.298 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-05-07 16:59:44.420 [info] [FetcherService] Using Electron fetcher
2024-05-07 16:59:44.423 [info] [auth] Logged in as San1k-02
2024-05-07 16:59:44.788 [info] [auth] Invalid copilot token: missing token: 403 
2024-05-07 16:59:44.790 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-07 16:59:44.805 [info] [auth] Logged in as San1k-02
2024-05-07 16:59:45.032 [info] [auth] Invalid copilot token: missing token: 403 

Otherwise, GitHub Copilot works perfectly

**Comment by jrieken** [comment]
Please ensure that the GitHub Copilot Chat extension is up to date.

**Comment by San1k-02** [comment]
> Please ensure that the GitHub Copilot Chat extension is up to date.

It's updated.

**Comment by jrieken** [comment]
please share the full version number

**Comment by San1k-02** [comment]
v.0.15.0
![image](https://github.com/microsoft/vscode-copilot-release/assets/71916703/6106e14a-3581-479b-8f26-5486797e3ec9)

**Comment by nikolas-garza-1** [comment]
I am also hitting this issue. I have tried installing previous version but still chat does not work

**Comment by joaofigueroa** [comment]
Hello guys, I'm also facing this issue with the version 0.15.0

**Comment by Jefsnkz** [comment]
Também estou com esse problema, não sei o porquê.

**Comment by Jefsnkz** [comment]
I'm also having this problem, I don't know why.

**Comment by airtongomeslima** [comment]
Same here. Solved changing to the pre-release version.

**Comment by lwl4613615** [comment]
[info] [RemoteAgents] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)

**Comment by jrieken** [comment]
` GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"`

⬆️ @TylerLeonhardt  either something with auth

⬇️ @roblourens or something with remote agents

`[info] [RemoteAgents] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)`

**Comment by ssslakter** [comment]
I have the same problem starting from yesterday. Everything is the latest version.
Switching to pre-release doesn't help. Copilot code completion also not working and when pressing `ctrl+i` it only shows pop up with trivial type-based suggestions. 
Although strangely `GitHub Copilot: Open Completions Panel` works fine and shows some code snippets, but it's inconvenient to use

**Comment by San1k-02** [comment]
> Same here. Solved changing to the pre-release version.

Not working for me, logs are:

2024-05-08 13:19:50.953 [info] [auth] Invalid copilot token: missing token: 403 
2024-05-08 13:19:51.274 [info] [RemoteAgents] Invalid remote agent response: access denied
 (SyntaxError: Unexpected token 'a', "access denied
" is not valid JSON)

v0.16.2024050801

**Comment by mispon** [comment]
The same issue after update to the v0.15.0 today

**Comment by bcdebusk** [comment]
Same.  Not working

**Comment by roblourens** [comment]
Sorry for the trouble. There seems to be an issue with authentication which incorrectly triggers the check that the extension may not be up to date. Looking into it. The `RemoteAgents` error is expected, just a red herring.

**Comment by roblourens** [comment]
And for anyone seeing this, has it gone away today, or if you reload the window, do you see it go away?

If not, are you behind a corporate proxy, or anything else interesting about your network configuration?

**Comment by ssslakter** [comment]
The problem didn't go away after reloading window. I also use my own proxy

**Comment by San1k-02** [comment]
> And for anyone seeing this, has it gone away today, or if you reload the window, do you see it go away?
> 
> If not, are you behind a corporate proxy, or anything else interesting about your network configuration?

No, it didn't go away. I'm also using proxy, but Copilot works perfectly.

**Comment by roblourens** [comment]
Could you try downgrading to VS Code 1.88 with the links at the top of the page here https://code.visualstudio.com/updates/v1_88

Then make sure to downgrade Copilot Chat to 0.14 (right click Copilot Chat > Install Another Version) and check whether it works for you. That would help us understand whether it's a client-side issue, or service/network issue

**Comment by Jefsnkz** [comment]
> Alguns de vocês poderiam tentar fazer o downgrade para o VS Code 1.88 com os links no topo da página aqui https://code.visualstudio.com/updates/v1_88
> 
> Em seguida, certifique-se de fazer o downgrade do Copilot Chat para 0.14 (clique com o botão direito do mouse em Copilot Chat > Instalar outra versão) e verifique se ele funciona para você? Isso nos ajudaria a entender se é um problema do lado do cliente ou de serviço/rede

Hello! I've been having a problem with my Copilot since the day before yesterday, the day before yesterday I couldn't use it, I couldn't use Chat (I even uninstalled it and installed it back, so nothing happened) so I left it the other day, and it ended up working, so Last night it failed again. At someone's suggestion, I installed version 1.88, I installed 1.89 several times, I reinstalled all the extensions and it doesn't work. When I try to click on "Join" nothing happens to enter the chat. Can you help me with a guide? I'm new to using Copilot

**Comment by lwl4613615** [comment]
I already know how to reproduce this issue 100%. When I use the latest version of VSCODE and install the latest version of GitHub Copilot Chat 0.15.0 and the plugin for this link, and complete the login and verification of the second plugin, I will encounter the issue of GitHub Copilot Chat not being able to be used. After uninstalling the second plugin, there is no problem.

the pugin link:https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb

**Comment by roblourens** [comment]
Thanks @lwl4613615, but it doesn't look like that extension is related to chat, so you might be seeing a different problem. Maybe you can open a new issue and share your logs or more details about what you see

**Comment by eavelasquez** [comment]
I have the same issue and checking the VSCode console, this appears:

![image](https://github.com/microsoft/vscode-copilot-release/assets/47928703/abe2c8e4-c5a8-4f2f-97f6-548604674f9f)

**Comment by roblourens** [comment]
@eavelasquez please make sure both Copilot Chat and VS Code are updated to the latest

**Comment by San1k-02** [comment]
@roblourens Just checked again on the latest version of VS Code (v.1.89.0) and Copilot Chat (v.0.15.0) and everything works. Did you fix something?

**Comment by anupamg7** [comment]
I've been facing the same issue for a couple of days now. 

I just uninstalled CoPilot & VS Code. Re installed VS Code & the extension, and it gives me the same error. "Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date." 

Inline suggestion are working though.

**Comment by Jefsnkz** [comment]
> > Alguns de vocês poderiam tentar fazer o downgrade para o VS Code 1.88 com os links no topo da página aqui https://code.visualstudio.com/updates/v1_88
> > Em seguida, certifique-se de fazer o downgrade do Copilot Chat para 0.14 (clique com o botão direito do mouse em Copilot Chat > Instalar outra versão) e verifique se ele funciona para você? Isso nos ajudaria a entender se é um problema do lado do cliente ou de serviço/rede
> 
> Olá! Eu tenho tido um problema com o meu Copilot desde anteontem, anteontem eu não pude usá-lo, eu não pude usar o Chat (eu até desinstalei e instalei de volta, então nada aconteceu) então eu saí no outro dia e ele acabou funcionando, então ontem à noite ele falhou novamente. Por sugestão do Roblourens, instalei a versão 1.88, instalei a 1.89 várias vezes, reinstalei todas as extensões e não funciona. Quando tento clicar em "Entrar" nada acontece para entrar no chat. Você pode me ajudar com um guia? Eu sou novo no uso do Copilot.

I just finished reinstalling Windows, downloaded i and installed Visual Studio Code again, downloaded the Github Copilot extension, and still nothing.
2024-05-09 16:32:30.052 [error] [auth] Extension activation failed: "Canceled"
2024-05-09 16:32:32.809 [error] [auth] Retrying auth
2024-05-09 16:32:39.347 [info] [fetcher] Using Helix fetcher.
2024-05-09 16:32:39.374 [info] [fetcher] Using Helix fetcher.
2024-05-09 16:32:39.400 [info] [fetcher] Using Helix fetcher.

**Comment by Jefsnkz** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/103887149/a40e706e-bf52-4864-99f0-cc51b430db45)

**Comment by Jefsnkz** [comment]
Can someone help me? I've been having the same problem for 3 days.

**Comment by jhampton** [comment]
Adding a +1 here.  I'm on VSCode latest, I've tried 0.14, 0.15, 0.15.1 of the Chat extension.  No interesting logs.  No network changes.

**Comment by jhampton** [comment]
-1

In my case, the org providing Copilot had a policy disallowing chat.  I enabled chat and it's working fine.  

I think the challenge on UX side here is: if chat isn't enabled at the policy level for an Org, a message to that effect would be helpful.

**Comment by anupamg7** [comment]
I had the same issue. My org had disallowed chat. I got it enabled and it works just fine :)

**Comment by RezaShamsipour** [comment]
same error for 3 days after update extension, how fix that ?

**Comment by alexdima** [comment]
Trying to shed some light here on our networking related changes. **We are trying to move from using the nodejs network stack to using Chromium's network stack**. Chromium's network stack supports a lot more kinds of proxies, since a core piece of Chromium is to... reach the internet :), but there might be something special about your environment that prevents it from working. 

Appologies for any disruption this might have caused! The Chromium network stack seems to work great in the environments we have tested it in, but we don't really know if there are gaps in its support or in our use of it unless we try it out in the real world.

We briefly enabled an experiment in v0.15.0 where we enabled the Chromium network stack (called ElectronFetcher in logs). We have since disabled this experiment. But we still want to make the ElectronFetcher the default fetcher for local extension hosts (VS Code extension hosts in regular, local scenarios, i.e. not WSL, not SSH, not devcontainers).

Would it please be possible to help us by:
* installing the [latest VS Code Insiders](https://code.visualstudio.com/insiders/). This can be installed side-by-side with your main VS Code installation
* installing the Pre-Release version of the Copilot Chat Extension `v0.16.2024051401 (pre-release)`
* trying if it works under your environment
* if it doesn't work, trying to configure `"github.copilot.advanced": { "debug.useElectronFetcher": false }` and trying if it works then.
* if the Electron Fetcher doesn't work, we'd like to find out what is special about your network environment.

Thank you very much!

**Comment by KyleGashler** [comment]
@alexdima I'm still getting the same issue after following all of your instructions and have nothing special about my network.

**Comment by alexdima** [comment]
@KyleGashler Could you please share the following:
* what OS you are using, and are you using WSL, devcontainers, remotessh or local development?
* VS Code version
* The GitHub Copilot Chat version
* The "GitHub Copilot" log
* The "GitHub Copilot Chat" log
* The "Extension Host" log
* The Developer tools log (Help > Toggle Developer Tools)

**Comment by mengxing-m** [comment]
configuring "GitHub. Copilot. Advanced": {"debug. useElectronFetcher": false}, it helped me

vs code: 1.93.1
copilot chat: 0.20.3

**Comment by chrmarti** [comment]
@mengxing-m Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.

**Comment by chrmarti** [comment]
Could everyone still seeing this with VS Code 1.96 or later check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here? Thanks.

**Comment by syllogismos** [comment]
```
2025-01-07 05:59:17.046 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2025-01-07 05:59:17.046 [error] Error: Failed to get copilot token
    at B0._authShowWarnings (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:4102)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at B0.getCopilotToken (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:2438)
    at dF.getCopilotToken (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:26267)
    at Y0._getAuthSession (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:488:2825)
    at r (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:488:2288)
    at Y0._registerEmbeddings (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:488:2787)
    at async Promise.all (index 1)
    at async Promise.allSettled (index 0)
    at tB.waitForActivationBlockers (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:13668)
    at /Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:2255:4201
    at Frr (/Users/anil/.vscode/extensions/github.copilot-chat-0.23.2/dist/extension.js:2255:4014)
    at K0.n (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
    at K0.m (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
    at K0.l (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
2025-01-07 05:59:17.046 [info] activationBlocker from 'languageModelAccess' took for 10230ms
```

I'm getting these logs in `GitHub copilot chat` output section.
