### ISSUE TITLE
Invalid Copilot token: missing token: 403 and Cannot Login to Copilot in VS Code

### ISSUE THREAD

**Issue by AdrianeNS** [microsoft/vscode-copilot-release#1198]
- VS Code Version: 1.89.1
- OS Version:  Windows 11 Home 23H2
- Logs - See below

I'm getting the errors in the subject of this post.   Both VS Code and Copilot Chat are updated to the latest versions. I cannot login to Copilot Chat manually either. when I click on the "Chat" icon in the left pane, there is a link to sign-in but when I click on the link one of two things will happen. Either nothing happens at all, or a web page opens with a 502 error, "Web server received an invalid response while acting as a gateway or proxy server." I tried updating Copilot Chat to the pre-release version but it's still happening. Here is a snippet from the log:

2024-05-10 11:14:51.939 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:14:51.940 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:14:51.941 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:14:51.941 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:14:51.943 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:14:51.943 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:14:51.945 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:14:51.952 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:14:51.954 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:14:51.954 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:14:51.956 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:15:57.061 [info] [FetcherService] Using Helix fetcher
2024-05-10 11:15:57.062 [info] [gitExtensionService] Initializing Git extension service.
2024-05-10 11:15:57.437 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-05-10 11:15:57.437 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-05-10 11:15:57.437 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-05-10 11:15:59.156 [info] [auth] Logged in as AdrianeNS
2024-05-10 11:16:03.217 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:16:03.220 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2024-05-10 11:16:03.248 [info] [auth] Logged in as AdrianeNS
2024-05-10 11:16:03.410 [info] [auth] Invalid copilot token: missing token: 403
2024-05-10 11:16:04.440 [info] [RemoteAgents] Invalid remote agent response: unauthorized: not licensed to use Copilot
(SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON)

**Comment by Lnkxx** [comment]
Do you used copilot-gpt4-service before？

**Comment by leovingo** [comment]
I have same issue,

**Comment by leovingo** [comment]
I have same issue, 
2024-05-23 15:45:21.816 [error] [auth] Extension activation failed: "Contact Support. You are currently logged in as leovingo."
2024-05-23 15:45:21.818 [info] [auth] Invalid copilot token: missing token: 403 
I have edu account and have use copilot in vsc before

**Comment by makk521** [comment]
> I have same issue, 2024-05-23 15:45:21.816 [error] [auth] Extension activation failed: "Contact Support. You are currently logged in as leovingo." 2024-05-23 15:45:21.818 [info] [auth] Invalid copilot token: missing token: 403 I have edu account and have use copilot in vsc before

I have the same question,and my school is USTC in China.

**Comment by hdytime** [comment]
> Do you used copilot-gpt4-service before？

我用了一天，之后就用不了了，我在官网copilot点击start free trial也没有反应，你解决了吗？

**Comment by Lnkxx** [comment]
> > Do you used copilot-gpt4-service before？
> 
> 我用了一天，之后就用不了了，我在官网copilot点击start free trial也没有反应，你解决了吗？

你被封号了，去开工单申诉吧

**Comment by mikeguschke** [comment]
403 2024-05-27 08:43:34.439 [info] [auth] Invalid copilot token: missing token: 403 

Redirected to Github Copilot subscription page to signup for monthly or yearly Copilot account.
Please remove this binding associated with VScode.

**Comment by makk521** [comment]
> 403 2024-05-27 08:43:34.439 [信息] [身份验证] 副驾驶令牌无效：缺少令牌：403
> 
> 重定向至 Github Copilot 订阅页面以注册按月或按年订阅的 Copilot 帐户。 请删除与 VScode 关联的此绑定。

I have get the education plan which copilot is free,but now I can't use it.

**Comment by Lnkxx** [comment]
> > 403 2024-05-27 08:43:34.439 [信息] [身份验证] 副驾驶令牌无效：缺少令牌：403
> > 重定向至 Github Copilot 订阅页面以注册按月或按年订阅的 Copilot 帐户。 请删除与 VScode 关联的此绑定。
> 
> I have get the education plan which copilot is free,but now I can't use i


> > 403 2024-05-27 08:43:34.439 [信息] [身份验证] 副驾驶令牌无效：缺少令牌：403
> > 重定向至 Github Copilot 订阅页面以注册按月或按年订阅的 Copilot 帐户。 请删除与 VScode 关联的此绑定。
> 
> I have get the education plan which copilot is free,but now I can't use it.

我也是UCAS的学生包，你是不是存在滥用行为导致被检测了，一般出现403就是被封号了

**Comment by lramos15** [comment]
Hi everyone,

This seems to have slipped through our issue triage scripts and we do apologize for that / the long reply time. 

Are you still experiencing the same issue. Can you please try the latest VS Code insiders + Copilot Chat pre-release.

**Comment by iubayb** [comment]
> Hi everyone,
> 
> This seems to have slipped through our issue triage scripts and we do apologize for that / the long reply time.
> 
> Are you still experiencing the same issue. Can you please try the latest VS Code insiders + Copilot Chat pre-release.

Yes we are

**Comment by lramos15** [comment]
@iubayb Can you please provide a screenshot of the chat panel + your Copilot Chat Logs (CTRL / CMD + SHIFT + U -> GitHub Copilot Chat) on the latest VS Code insiders + Copilot Chat pre-release

**Comment by iubayb** [comment]
<img width="348" alt="Screenshot 2024-07-18 at 17 32 09" src="https://github.com/user-attachments/assets/062e983c-00da-4f00-907e-7df11f247923">

2024-07-18 17:31:59.544 [info] [auth] Logged in as iubayb
2024-07-18 17:32:00.065 [info] [chat] copilot token chat_enabled: false
2024-07-18 17:32:00.065 [info] [auth] Got Copilot token for iubayb
2024-07-18 17:32:00.094 [info] [auth] Logged in as iubayb
2024-07-18 17:32:00.107 [info] [chat] copilot token chat_enabled: false
2024-07-18 17:32:00.108 [info] [auth] Got Copilot token for iubayb
2024-07-18 17:32:00.844 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:88:17938)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UA._fetchModels (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:3447)
    at UA.getChatModel (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:2329)
    at ZT.getChatEndpoint (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:5862)
    at t.detectIntent (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:840:611)
    at JTe (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:845:795)
    at dp.fetchResponse (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:848:2336)
    at dp.provideInteractiveEditorResponse (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:847:2016)
    at Nc.handleCommonInlineChatRequest (/Users/ayoub/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:882:3894)
    at g.$invokeAgent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:50217)

**Comment by lramos15** [comment]
@iubayb That's not the latest VS Code Insiders + pre-release. But here I see that Copilot Chat is disabled by your organization

```
2024-07-18 17:32:00.094 [info] [auth] Logged in as iubayb
2024-07-18 17:32:00.107 [info] [chat] copilot token chat_enabled: false
2024-07-18 17:32:00.108 [info] [auth] Got Copilot token for iubayb
```

So therefore chat will not work until your organization admin enables it

**Comment by leovingo** [comment]
![image](https://github.com/user-attachments/assets/5f802c48-3741-49c0-a815-be90020213aa)
I tried downloading the latest version of vsc but it still doesn't work
