### ISSUE TITLE
Copilot extension error (Unexpected token 'o'... not valid JSON)

### ISSUE THREAD

**Issue by norbertkocon94** [microsoft/vscode-copilot-release#1205]
- VS Code Version: Actual newest.
- OS Version: Actual newest MacOS.
- Logs: 2024-05-13 11:09:56.647 [error] [auth] Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"

Steps to Reproduce:

1. Open VSC.
2. Copilot extension failed.

2024-05-13 11:09:56.647 [error] [auth] Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON".

**Comment by SecTreeCN** [comment]
I have the same problem and another error is 
- [default] Error sending telemetry TypeError: l.body?.pipeTo is not a function
    at fetchWithSession (node:electron/js2c/utility_init:2:1876)
    at Object.fetch (node:electron/js2c/utility_init:2:14427)
Did you slove the problem？

**Comment by mjbvz** [comment]
Please provide version numbers and with the copilot extension version too

**Comment by norbertkocon94** [comment]
Github Copilot v1.88.0 works correctly, v1.190.0 won't

**Comment by SecTreeCN** [comment]
GitHub Copilot version v1.190.0
and
VisualStudio Code version v1.89.1

**Comment by SecTreeCN** [comment]
vscode more infomation
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by lmarch2** [comment]
The Same problem too 
version  1.191.0

**Comment by mjbvz** [comment]
Thanks. I'm unfortunately unable to repro this. Can you please try getting the full stack of the error:

1. Reproduce the issue
1. In VS Code, run the `Developer: Toggle developer tools` command in the command palette
2. This should open the Chrome dev tools
3. In the dev tools, open up the console and look for the error message

The full error message and stack should help us figure out what's going on

**Comment by SecTreeCN** [comment]
all the error message are as follows 
- ERR Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): extensionsAny, newSymbolNamesProvider, interactive, chatProvider, codeActionAI, findTextInFiles, findFiles2, textSearchProvider, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, mappedEditsProvider, aiRelatedInformation, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, contribSourceControlInputBoxMenu, authLearnMore, testObserver, aiTextSearchProvider
product.json (WINS): interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver

- ERR [Extension Host] (node:9868) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

 - ERR [Extension Host] [auth] Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"

- ERR [Extension Host] [default] Error sending telemetry TypeError: l.body?.pipeTo is not a function
    at fetchWithSession (node:electron/js2c/utility_init:2:1876)
    at Object.fetch (node:electron/js2c/utility_init:2:14427)
    at M8.fetch (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\extension\src\electronFetcher.ts:77:37)
    at sendPostFunc (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\lib\src\telemetry\appInsightsReporter.ts:108:18)
    at _doSend (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\channels\applicationinsights-channel-js\dist-es5\Sender.js:636:28)
    at y.Qa.<computed> [as _sender] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\channels\applicationinsights-channel-js\dist-es5\Sender.js:281:32)
    at y.Qa.<computed> [as triggerSend] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\channels\applicationinsights-channel-js\dist-es5\Sender.js:368:64)
    at y.dynProtoProxy [as triggerSend] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\common\temp\node_modules\@microsoft\dynamicproto-js\dist-es5\DynamicProto.js:347:29)
    at y.Qa.flush (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\channels\applicationinsights-channel-js\dist-es5\Sender.js:143:55)
    at y.dynProtoProxy [as flush] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\common\temp\node_modules\@microsoft\dynamicproto-js\dist-es5\DynamicProto.js:347:29)
    at cb (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\shared\AppInsightsCore\dist-es5\JavaScriptSDK\AppInsightsCore.js:869:41)
    at Object._iterateChain [as iterate] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\shared\AppInsightsCore\dist-es5\JavaScriptSDK\ProcessTelemetryContext.js:174:17)
    at _flushChannels (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\shared\AppInsightsCore\dist-es5\JavaScriptSDK\AppInsightsCore.js:864:30)
    at _.Oi.<computed> [as unload] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\shared\AppInsightsCore\dist-es5\JavaScriptSDK\AppInsightsCore.js:456:22)
    at _.dynProtoProxy [as unload] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\common\temp\node_modules\@microsoft\dynamicproto-js\dist-es5\DynamicProto.js:347:29)
    at _.unload (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\shared\AppInsightsCore\dist-es5\JavaScriptSDK\HelperFuncs.js:131:44)
    at _.dynProtoProxy [as unload] (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\node_modules\@microsoft\common\temp\node_modules\@microsoft\dynamicproto-js\dist-es5\DynamicProto.js:347:29)
    at qF.dispose (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\lib\src\telemetry\appInsightsReporter.ts:77:27)
    at e7.deactivate (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\lib\src\telemetry.ts:120:45)
    at c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\extension\src\auth.ts:125:37
    at new Promise (<anonymous>)
    at handleAuthenticationError (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\extension\src\auth.ts:122:12)
    at attemptAuthentication (c:\Users\Tree\.vscode\extensions\github.copilot-1.190.0\extension\src\auth.ts:86:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

- ERR [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat

<img width="393" alt="PixPin_2024-05-15_17-29-04" src="https://github.com/microsoft/vscode-copilot-release/assets/143724791/f58ec37f-9084-4f72-bced-187df1606bc7">
<img width="393" alt="PixPin_2024-05-15_17-28-49" src="https://github.com/microsoft/vscode-copilot-release/assets/143724791/b472b442-2025-4a05-9702-c220ee1fa9a7">
<img width="393" alt="PixPin_2024-05-15_17-28-37" src="https://github.com/microsoft/vscode-copilot-release/assets/143724791/ce4ce03a-eb27-4384-9124-30383de6a045">
<img width="393" alt="PixPin_2024-05-15_17-28-20" src="https://github.com/microsoft/vscode-copilot-release/assets/143724791/23f3b91f-2a23-450c-be2a-5a974a45991d">

**Comment by jrieken** [comment]
The errors appear to be 

* an auth issue, the OG mentioning a JSON parse fail @TylerLeonhardt 
* the telemetry issue wrt the pipeTo-error @lramos15

**Comment by lramos15** [comment]
The telemetry issue originates from Completions `e\extensions\github.copilot-1.190.0\node_modules` @devm33

**Comment by devm33** [comment]
It looks like the auth issue is the main problem blocking extension activation: `ERR [Extension Host] [auth] Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"`

The telemetry error is curious though somehow the `Request.body` is invalid when it tries to write it out [here](https://github.com/electron/electron/blob/752efddf893b619c09dfaf941136ff4b146e5361/lib/browser/api/net-fetch.ts#L120). But the `sendPostFunc` restricts the data it accepts from the appinsights library to string `if (typeof payload.data !== 'string') throw new Error(...` 🤔

**Comment by TylerLeonhardt** [comment]
For Copilot Chat, our line of code would have shown:
```
GitHub Copilot could not connect to server. Extension activation failed:  ....
```
But instead you say that it says just:
```
Extension activation failed: 
```

That I was able to find in the Copilot extension, not the Copilot Chat extension. We should move this over to those folks.

@norbertkocon94 can you please get a discussion going over here? https://github.com/orgs/community/discussions/categories/copilot
