### ISSUE TITLE
Cannot have a text node outside a ChatMessage.

### ISSUE THREAD

**Issue by JakeHadley** [microsoft/vscode-copilot-release#1218]
- VS Code Version:  1.89.1 (Universal)
- OS Version: MacOS 14.4.1
- Logs:
```
2024-05-15 08:08:56.271 [info] [FetcherService] Using Helix fetcher
2024-05-15 08:08:56.272 [info] [gitExtensionService] Initializing Git extension service.
2024-05-15 08:08:56.272 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-05-15 08:08:56.272 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-05-15 08:08:56.272 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-05-15 08:08:58.064 [info] [auth] Logged in as JakeHadley
2024-05-15 08:08:58.808 [info] [chat] copilot token chat_enabled: true
2024-05-15 08:08:58.808 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-05-15 08:08:58.808 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-05-15 08:08:58.815 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 08:08:58.816 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-05-15 08:08:58.817 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-05-15 08:10:06.422 [info] [FetcherService] Using Helix fetcher
2024-05-15 08:10:06.422 [info] [gitExtensionService] Initializing Git extension service.
2024-05-15 08:10:06.422 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-05-15 08:10:06.422 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-05-15 08:10:06.422 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-05-15 08:10:07.038 [info] [auth] Logged in as JakeHadley
2024-05-15 08:10:07.674 [info] [chat] copilot token chat_enabled: true
2024-05-15 08:10:07.674 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-05-15 08:10:07.674 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-05-15 08:10:07.676 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 08:10:07.676 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-05-15 08:10:07.676 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-05-15 08:35:07.615 [info] [auth] Logged in as JakeHadley
2024-05-15 08:35:07.837 [info] [chat] copilot token chat_enabled: true
2024-05-15 08:35:07.837 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 09:00:07.740 [info] [auth] Logged in as JakeHadley
2024-05-15 09:00:08.010 [info] [chat] copilot token chat_enabled: true
2024-05-15 09:00:08.010 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 09:25:07.934 [info] [auth] Logged in as JakeHadley
2024-05-15 09:25:08.235 [info] [chat] copilot token chat_enabled: true
2024-05-15 09:25:08.235 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 09:50:08.220 [info] [auth] Logged in as JakeHadley
2024-05-15 09:50:08.512 [info] [chat] copilot token chat_enabled: true
2024-05-15 09:50:08.513 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 10:15:08.452 [info] [auth] Logged in as JakeHadley
2024-05-15 10:15:08.720 [info] [chat] copilot token chat_enabled: true
2024-05-15 10:15:08.721 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 10:40:08.661 [info] [auth] Logged in as JakeHadley
2024-05-15 10:40:08.960 [info] [chat] copilot token chat_enabled: true
2024-05-15 10:40:08.960 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 11:05:08.906 [info] [auth] Logged in as JakeHadley
2024-05-15 11:05:09.190 [info] [chat] copilot token chat_enabled: true
2024-05-15 11:05:09.190 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 11:30:09.129 [info] [auth] Logged in as JakeHadley
2024-05-15 11:30:09.405 [info] [chat] copilot token chat_enabled: true
2024-05-15 11:30:09.405 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 11:55:09.352 [info] [auth] Logged in as JakeHadley
2024-05-15 11:55:09.574 [info] [chat] copilot token chat_enabled: true
2024-05-15 11:55:09.574 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 12:17:58.526 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-05-15 12:17:58.526 [info] [chat fetch] modelMaxPromptTokens 3072
2024-05-15 12:17:58.526 [info] [chat fetch] modelMaxResponseTokens 4096
2024-05-15 12:17:58.526 [info] [chat fetch] chat model gpt-4
2024-05-15 12:17:59.609 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1082 ms
2024-05-15 12:18:14.559 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-05-15 12:18:14.561 [info] [streamChoices] request done: requestId: [c1de117c-a130-4bfe-920c-81bf298eb908] model deployment ID: []
2024-05-15 12:18:14.703 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-05-15 12:18:14.703 [info] [chat fetch] modelMaxPromptTokens 7168
2024-05-15 12:18:14.703 [info] [chat fetch] modelMaxResponseTokens 4096
2024-05-15 12:18:14.703 [info] [chat fetch] chat model gpt-3.5-turbo
2024-05-15 12:18:15.289 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 586 ms
2024-05-15 12:18:15.305 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-05-15 12:18:15.306 [info] [streamChoices] request done: requestId: [ff6790ee-87b5-4cc5-a48c-beb081917dcc] model deployment ID: []
2024-05-15 12:20:09.589 [info] [auth] Logged in as JakeHadley
2024-05-15 12:20:09.862 [info] [chat] copilot token chat_enabled: true
2024-05-15 12:20:09.862 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 12:45:09.695 [info] [auth] Logged in as JakeHadley
2024-05-15 12:45:10.057 [info] [chat] copilot token chat_enabled: true
2024-05-15 12:45:10.057 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 13:10:09.942 [info] [auth] Logged in as JakeHadley
2024-05-15 13:10:10.175 [info] [chat] copilot token chat_enabled: true
2024-05-15 13:10:10.175 [info] [auth] Got Copilot token for JakeHadley
2024-05-15 13:15:01.719 [info] [extension] Error: Cannot have a text node outside a ChatMessage. Text: ""
    at t._materialize (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:9:102)
    at t.materialize (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:5:1714)
    at nt.render (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:4:39261)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at nt.render (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:788:3529)
    at uJ.buildPrompt (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:1092:1079)
    at t6._provideResponseWithProgress (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:866:836)
    at t6.provideResponseWithProgress (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:864:4167)
    at i.y (/Users/jakehadley/.vscode/extensions/github.copilot-chat-0.15.1/dist/extension.js:876:1460)
    at n.$invokeAgent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:44194)
```

Steps to Reproduce:

1. I run `/tests` in either the chat window or the quick chat window, and after one command running successfully, every coinciding command give me this error: `Cannot have a text node outside a ChatMessage. Text: ""`
2. ![Screenshot 2024-05-15 at 22 21 30](https://github.com/microsoft/vscode-copilot-release/assets/35585841/3d1a83d5-b9aa-4f9d-abe0-e8baf734e6cf)

**Comment by jinenab** [comment]
I confirm I have the same issue with the same vscode version and OS Version: MacOS 14.5

**Comment by alexcza** [comment]
same here

**Comment by ulugbekna** [comment]
Hello everyone,

Thanks for the reports! 

Are you experiencing this when you invoke `/tests` in an empty file only?

**Comment by jinenab** [comment]
> Hello everyone,
> 
> Thanks for the reports!
> 
> Are you experiencing this when you invoke `/tests` in an empty file only?

for me its for files with code

**Comment by JakeHadley** [comment]
> Hello everyone,
> 
> Thanks for the reports!
> 
> Are you experiencing this when you invoke `/tests` in an empty file only?

Non-empty file. For context, this is also happening in a .dart file for me.

**Comment by alexcza** [comment]
> ulugbekna

inside a typescript file with code

**Comment by yuriccosta** [comment]
Why was this mark as closed? I still have this problem too.

**Comment by alexcza** [comment]
The problem persists after I updated copilot today to version 1.196.0

**Comment by ulugbekna** [comment]
@yuriccosta @alexcza Thank you for reaching out! 

Which version of extension are you on? The fix is currently available (released) in VS Code Insiders and corresponding Copilot Chat pre-release version `v0.16.2024052801 (pre-release)`. The next stable release (stable = not pre-release) should happen mid-next week. 

If you can still reproduce with the pre-release version and Insiders installed, please share current state of the editor (selected code) and how you are running `/tests` (panel chat vs inline chat, if you're adding extra instructions or not, etc.)

**Comment by ulugbekna** [comment]
@alexcza Are you on VS Code Insiders as well? Can you share your versions for VS Code and Copilot Chat extension? 

To get VS Code version: invoke command "Help: About" and copy the output.

To get Copilot Chat version: Open Extensions View, seach for Copilot Chat extension, the version is next to the name.



![Image](https://github.com/microsoft/vscode-copilot-release/assets/16353531/1d061fff-625c-45c5-af60-b9ad9c92dd2d)

**Comment by yuriccosta** [comment]
> @yuriccosta @alexcza Obrigado por entrar em contato!
> 
> Em qual versão da extensão você está? A correção está atualmente disponível (lançada) no VS Code Insiders e na versão de pré-lançamento correspondente do Copilot Chat `v0.16.2024052801 (pre-release)`. A próxima versão estável (estável = não pré-lançamento) deve acontecer no meio da próxima semana.
> 
> Se você ainda consegue reproduzir com a versão de pré-lançamento e Insiders instalados, compartilhe o estado atual do editor (código selecionado) e como você está executando `/tests` (bate-papo no painel versus bate-papo em linha, se você estiver adicionando instruções extras ou não, etc.)

My copilot is on version 1.197.0 and my VsCode is on 1.89.1

**Comment by alexcza** [comment]
> autocomplets

I don't think I am on VS Code Insiders
<img width="252" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/42179728/6e0d7505-7041-4d98-bb82-dfdf2cb936f3">

<img width="821" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/42179728/6914b067-41a8-4002-9336-f659bdfd6562">

**Comment by ulugbekna** [comment]
@alexcza You're on older version of pre-release Copilot Chat because you're not on [Insiders](https://code.visualstudio.com/insiders/).
