### ISSUE TITLE
Copilot Chat returning error when prompted in VSCode Insiders

### ISSUE THREAD

**Issue by davidseres** [microsoft/vscode-copilot-release#1219]
Whenever I try to ask something in the chat I get the following error message:

Cannot read properties of undefined (reading 'map')

![image](https://github.com/microsoft/vscode-copilot-release/assets/7083543/8fe4be82-2c70-4987-8672-f9080af85f89)

The error occurs on both the release and pre-release versions.

**Comment by andreamah** [comment]
Can you share the logs? There should be some logs in the `Copilot Chat` channel in the `Output` pane.

**Comment by davidseres** [comment]
I can't access the log file. But after today's update it works again

**Comment by jacketwpbb** [comment]
> Can you share the logs? There should be some logs in the `Copilot Chat` channel in the `Output` pane.

The same error was encountered in both the pre-release version and the released version.


[extension] TypeError: Cannot read properties of undefined (reading 'map')
    at F6.sanitizeVariables (/Users/x/.vscode-insiders/extensions/github.copilot-chat-0.16.2024051702/dist/extension.js:867:2134)
    at F6._provideResponseWithProgress (/Users/x/.vscode-insiders/extensions/github.copilot-chat-0.16.2024051702/dist/extension.js:867:670)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at F6.provideResponseWithProgress (/Users/x/.vscode-insiders/extensions/github.copilot-chat-0.16.2024051702/dist/extension.js:865:8991)
    at i.x (/Users/x/.vscode-insiders/extensions/github.copilot-chat-0.16.2024051702/dist/extension.js:877:1970)
    at n.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:44681)

**Comment by alexfilothodoros** [comment]
Hi.
I am getting the same error on macOS. I am running the latest version of code-insiders and of the copilot extensions.

**Comment by andreamah** [comment]
> Can you share the logs? There should be some logs in the `Copilot Chat` channel in the `Output` pane.

Can you try this ^?

**Comment by alexfilothodoros** [comment]
Hi. I couldn't find the log.
Anyway, a few more install/uninstall rounds and everything is working for now.

Thanks :)
