### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by cosmoKenney** [microsoft/vscode-copilot-release#1257]
- VS Code Version: Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.10.0

- OS Version: Windows 11
- Logs: 

Steps to Reproduce:

1. Via VS Extension Manager install the copilot chat extension. 
2. See a popup that says it cannot install on this version of VS.

Log...
```text
5/28/2024 10:50:31 AM - Microsoft VSIX Installer
5/28/2024 10:50:31 AM - -------------------------------------------
5/28/2024 10:50:31 AM - vsixinstaller.exe version:
5/28/2024 10:50:31 AM - 17.10.2179+08f3ed4b45
5/28/2024 10:50:31 AM - -------------------------------------------
5/28/2024 10:50:31 AM - Command line parameters:
5/28/2024 10:50:31 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.10.34916.146,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,D:\Tmp\VSIXccfcozzx.vsix
5/28/2024 10:50:31 AM - -------------------------------------------
5/28/2024 10:50:31 AM - Microsoft VSIX Installer
5/28/2024 10:50:31 AM - -------------------------------------------
5/28/2024 10:50:31 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (9a12f913) since it does not support extensions
5/28/2024 10:50:31 AM - Initializing Install...
5/28/2024 10:50:31 AM - Extension Details...
5/28/2024 10:50:31 AM - 	Identifier         : VS.GitHub.Copilot
5/28/2024 10:50:31 AM - 	Name               : GitHub Copilot Chat
5/28/2024 10:50:31 AM - 	Author             : Microsoft
5/28/2024 10:50:31 AM - 	Version            : 0.2.755.36570
5/28/2024 10:50:31 AM - 	Description        : GitHub Copilot Chat brings fully integrated AI-powered Copilot chat experiences to Visual Studio. Requires a GitHub ID which has been admitted for access to the private preview.
5/28/2024 10:50:31 AM - 	Locale             : en-US
5/28/2024 10:50:31 AM - 	MoreInfoURL        : https://aka.ms/VisualStudio.GitHub.Copilot/moreinfo
5/28/2024 10:50:31 AM - 	InstalledByMSI     : False
5/28/2024 10:50:31 AM - 	SupportedFrameworkVersionRange : [4.5,)
5/28/2024 10:50:32 AM - 	SignatureState     : ValidSignature
5/28/2024 10:50:32 AM - 	SignedBy           : Microsoft Corporation
5/28/2024 10:50:32 AM - 	Certificate Info   : 
5/28/2024 10:50:32 AM - 		-------------------------------------------------------
5/28/2024 10:50:32 AM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/28/2024 10:50:32 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/28/2024 10:50:32 AM - 		[Serial Number] : 330000056067F73C897D62BABD000000000560
5/28/2024 10:50:32 AM - 		[Not Before]    : 1/11/2024 12:05:33 PM
5/28/2024 10:50:32 AM - 		[Not After]     : 1/10/2025 12:05:33 PM
5/28/2024 10:50:32 AM - 		[Thumbprint]    : 80AF76D324CE728D7DF51CDCA241F5E9598169B7
5/28/2024 10:50:32 AM - 	Supported Products : 
5/28/2024 10:50:32 AM - 		Microsoft.VisualStudio.Community
5/28/2024 10:50:32 AM - 			Version : [17.8,17.10.34712.116)
5/28/2024 10:50:32 AM - 			ProductArchitecture : amd64
5/28/2024 10:50:32 AM - 		Microsoft.VisualStudio.Community
5/28/2024 10:50:32 AM - 			Version : [17.8,17.10.34712.116)
5/28/2024 10:50:32 AM - 			ProductArchitecture : arm64
5/28/2024 10:50:32 AM - 	References         : 
5/28/2024 10:50:32 AM - 	Prerequisites      : 
5/28/2024 10:50:32 AM - 		-------------------------------------------------------
5/28/2024 10:50:32 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/28/2024 10:50:32 AM - 		Name         : Visual Studio core editor
5/28/2024 10:50:32 AM - 		Version      : [17.0,18.0)
5/28/2024 10:50:32 AM - 		-------------------------------------------------------
5/28/2024 10:50:32 AM - 		Identifier   : Microsoft.VisualStudio.Component.IntelliCode
5/28/2024 10:50:32 AM - 		Name         : Visual Studio IntelliCode
5/28/2024 10:50:32 AM - 		Version      : [17.0,18.0)
5/28/2024 10:50:32 AM - Signature Details...
5/28/2024 10:50:32 AM - 	Extension is signed with a valid signature.
5/28/2024 10:50:32 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by sandy081** [comment]
What is VS Extension Manager?

Is the editor you are using Visual Studio Code or Visual Studio?

**Comment by cosmoKenney** [comment]
> What is VS Extension Manager?
> 
> Is the editor you are using Visual Studio Code or Visual Studio?
Oh, sorry, I posted this in the wrong spot I guess. I am using visual studio 2022. I'll close this. You can delete if you need to.

**Comment by LerioSindane** [comment]
<img width="428" alt="Screenshot 2024-06-13 at 20 49 06" src="https://github.com/microsoft/vscode-copilot-release/assets/57997464/e068305a-d26d-421b-9c5d-c761c74a757a">
I am unable to install the extension as well. I am using Visual Studio 2022 version 17.10.1 on Windows 11.

**Comment by ssoeun** [comment]
Hello all, i have a same problem in VS2022 Comunity
![error extention](https://github.com/microsoft/vscode-copilot-release/assets/14146750/05b97ae6-774b-41a0-9914-dd9e2d439ef2)
Can you help pleas.
Thanks

**Comment by cosmoKenney** [comment]
@LerioSindane, @ssoeun,
Turns out that for VS 2022, Copilot Chat is an option in the Visual Studio Installer. 
See here for the currently recommended method to install it: https://learn.microsoft.com/en-us/visualstudio/ide/visual-studio-github-copilot-install-and-states?view=vs-2022

**Comment by ssoeun** [comment]
@cosmoKenney ,
Thank you very much for your quick reply.
I hadn't paid attention to the version of my visual studio, which was 17.10. 
Thank you very much
