### ISSUE TITLE
Failed to get model for interactive session editor

### ISSUE THREAD

**Issue by 842u** [microsoft/vscode-copilot-release#126]
When you got Copilot Chat open in editor tab and restart VS Code session then error apears in that tab.
![image](https://github.com/microsoft/vscode-copilot-release/assets/23544888/362c157e-3814-4256-9b97-d2ab5a61cb8e)

- VS Code Version:
```
Version: 1.79.0-insider (user setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1 
V8: 10.8.168.25-electron.0
```
- OS Version:
`Windows_NT x64 10.0.22621`
- Logs:
```
[error] Error: Failed to get model for interactive session editor. id: 796b89c7-7c98-44c7-a9d0-eab52ade334c
    at e.ChatEditor.setInput (vscode-file://vscode-app/c:/Users/kamil/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2006:13914)
    at async e.EditorPanes.M (vscode-file://vscode-app/c:/Users/kamil/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:23729)
    at async e.EditorPanes.D (vscode-file://vscode-app/c:/Users/kamil/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:22324)
    at async e.EditorPanes.openEditor (vscode-file://vscode-app/c:/Users/kamil/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:21227)
    at async vscode-file://vscode-app/c:/Users/kamil/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2467:13463
```

Steps to Reproduce:

1. Open Copilot Chat in editor tab.
2. Close VS Code.
3. Open VS Code and error apears.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/187657
