### ISSUE TITLE
Problem with update to v0.16 on VSCode 1.90

### ISSUE THREAD

**Issue by mdragoss** [microsoft/vscode-copilot-release#1285]
- VS Code Version: 1.90
- OS Version: MacOS 14.5
- Logs: 2024-06-06 19:34:22.292 [error] Error: Chat response provider uses UNKNOWN vendor github.copilot-chat.

Steps to Reproduce: N/A

https://github.com/microsoft/vscode-copilot-release/assets/46487312/910a37ad-4ebc-4d6b-9ec0-567e967593af

**Comment by jrieken** [comment]
@mdragoss What version of VS Code does this happen with? Also, what other extensions do you have installed? Finally, enable trace logging and share the window log please

**Comment by mdragoss** [comment]
VSCode Version 1.90 (also added it to note title)

```
trace] [LM] registering language model chat github.copilot-chat/1/copilot-gpt-3.5-turbo {"extension":{"value":"GitHub.copilot-chat","_lower":"github.copilot-chat"},"id":"copilot-gpt-3.5-turbo","vendor":"github.copilot-chat","name":"gpt-3.5-turbo","family":"","version":"gpt-3.5-turbo","auth":{"providerLabel":"GitHub Copilot Chat","accountLabel":"mdragoss"}}
2024-06-10 17:01:03.735 [error] Chat response provider uses UNKNOWN vendor github.copilot-chat.: Error: Chat response provider uses UNKNOWN vendor github.copilot-chat.
    at i.registerLanguageModelChat (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:20612)
    at i.$registerLanguageModelProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1651:1412)
    at y.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14598)
    at y.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14364)
    at y.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:13397)
    at y.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:12232)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:10928)
    at h.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at h.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at r.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:615:14848)
    at U.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1673:8154)
2024-06-10 17:01:03.849 [trace] [LM] registering language model chat github.copilot-chat/2/copilot-gpt-4 {"extension":{"value":"GitHub.copilot-chat","_lower":"github.copilot-chat"},"id":"copilot-gpt-4","vendor":"github.copilot-chat","name":"gpt-4","family":"","version":"gpt-4","auth":{"providerLabel":"GitHub Copilot Chat","accountLabel":"mdragoss"}}
2024-06-10 17:01:03.903 [trace] CommandService#executeCommand _setContext
2024-06-10 17:01:04.631 [trace] SearchService#search {"_reason":"startFileSearch","folderQueries":[{"folder":{"$mid":1,"fsPath":"/test","external":"file:///test","path":"/test","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,"**/__pycache__":true,"**/.cache":true,"**/.coverage":true,"**/.coverage.*":true,"**/.hypothesis":true,"**/.mypy_cache":true,"**/.nox":true,"**/.pytest_cache":true,"**/.ruff_cache":true,"**/.tox":true},"fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"excludePattern":{"**/node_modules/**":true},"includePattern":{"**/package.json":true},"type":1,"shouldGlobMatchFilePattern":true}
2024-06-10 17:01:04.666 [trace] SearchService#search: 34ms
2024-06-10 17:01:04.762 [trace] MainThreadFileSystemEventService#$watch(): request to start watching uncorrelated (extension: ms-python.python, path: file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12, recursive: true, session: 0.06683906689520192)
2024-06-10 17:01:06.245 [trace] CommandService#executeCommand _setContext
2024-06-10 17:01:06.337 [trace] MainThreadFileSystemEventService#$unwatch(): request to stop watching (session: 0.369363579711975)
2024-06-10 17:01:06.338 [trace] MainThreadFileSystemEventService#$watch(): request to start watching uncorrelated (extension: vscode.git, path: file:///test/.git, recursive: false, session: 0.37168217987496277)
2024-06-10 17:01:06.339 [trace] CommandService#executeCommand _setContext
2024-06-10 17:01:06.340 [trace] CommandService#executeCommand _setContext
2024-06-10 17:01:07.162 [debug] User data changed
2024-06-10 17:01:11.629 [trace] [History stack global-default]: notifyNavigation() (editor: extension:github.copilot-chat/extension, event: <none>)
2024-06-10 17:01:11.629 [trace] [History stack global-default]: notifyNavigation() not ignoring (editor: extension:github.copilot-chat/extension, event: <none>)
2024-06-10 17:01:11.629 [trace] [History stack global-default]: onNonSelectionAwareEditorNavigation() (editor: extension:github.copilot-chat/extension, event: <none>)
2024-06-10 17:01:11.630 [trace] [History stack global-default]: add() (editor: extension:github.copilot-chat/extension, event: <none>)
2024-06-10 17:01:11.630 [trace] [History stack global-default]: index: 0, navigating: false
- group: 0, editor: extension:github.copilot-chat/extension, selection: <none>
			
2024-06-10 17:01:11.679 [debug] Webview(9671b8d1-4594-4e91-906f-da88ca9513f7): will update content
2024-06-10 17:01:11.804 [debug] Webview(9671b8d1-4594-4e91-906f-da88ca9513f7): webview ready
2024-06-10 17:01:12.609 [trace] RunAutomaticTasks: waited some extra time, but no update of tasks configuration
2024-06-10 17:01:14.504 [debug] User data changed
2024-06-10 17:01:14.763 [trace] CommandService#executeCommand workbench.action.toggleMaximizedPanel
2024-06-10 17:01:16.925 [trace] CommandService#executeCommand workbench.extensions.action.showExtensionsWithIds
2024-06-10 17:01:16.928 [trace] writeTextAreaState(reason: focusgain)
2024-06-10 17:01:16.936 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:16.944 [trace] writeTextAreaState(reason: focusgain)
2024-06-10 17:01:27.230 [trace] writeTextAreaState(reason: focusgain)
2024-06-10 17:01:27.235 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:27.246 [trace] CommandService#executeCommand _setContext
2024-06-10 17:01:27.426 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:27.458 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:27.475 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:27.491 [trace] writeTextAreaState(reason: selection changed)
2024-06-10 17:01:27.508 [trace] writeTextAreaState(reason: selection changed)
```

**Comment by mdragoss** [comment]
> This is really confusing and unexpected. The copilot chat extension uses the `copilot` vender, this is hardcoded and I see working correctly locally. Also, the data you are receiving has no family property which I have no explanation for.
> 
> <img alt="Screenshot 2024-06-10 at 16 56 41" width="1383" src="https://private-user-images.githubusercontent.com/1794099/338238982-df2da8e6-d0b6-4665-acad-3855cff65e65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzM3MzMsIm5iZiI6MTcxODAzMzQzMywicGF0aCI6Ii8xNzk0MDk5LzMzODIzODk4Mi1kZjJkYThlNi1kMGI2LTQ2NjUtYWNhZC0zODU1Y2ZmNjVlNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMTUzMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM1NDJjMTlkNDRkYTg4MGY1YzllNDU1OGI0NGEzY2Q1NjNmM2NjNDMzYzcyYmQyMGRkOWRjZGY1MmZiY2ZjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IYaJABtZrj1bYJTfmtmLitl-Xw7avbTjX1aLFhDcGUA">
> Can you please try with a new empty profile in which you install the extension fresh

I enabled some extensions for all profiles, but switching profiles updated them successfully. Thanks for the help!
