### ISSUE TITLE
Copilot: Out of memory

### ISSUE THREAD

**Issue by hkchengrex** [microsoft/vscode-copilot-release#1298]
The setup works when editing local files, but fails when editing remote files. An error "copilot: out of memory" appears at the bottom-right.

I have also tried the Copilot pre-release version. It does not work either.
It works for other remote servers so I am not sure what the problem is.
I don't think the server is running out of memory -- there are >400GB of free memory and I can easily occupy >10GB of memory with numpy running on the same server.

Related: https://github.com/orgs/community/discussions/45418

- VS Code Version: 1.90.0
- OS Version: Local machine: Ubuntu 22.04; remote: Red Hat Enterprise 8.2
- Logs:
```
2024-06-11 15:46:03.991 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-06-11 15:46:03.991 [info] [code-referencing] Public code references are enabled.
2024-06-11 15:46:04.058 [info] [auth] Sucessfully authenticated
2024-06-11 15:46:57.528 [error] [ghostText] provideInlineCompletionItems: RangeError: WebAssembly.Memory(): could not allocate memory
    at /home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/node_modules/web-tree-sitter/tree-sitter.js:1:5037
    at new Promise (<anonymous>)
    at Function.init (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/node_modules/web-tree-sitter/tree-sitter.js:1:393)
    at loadWasmLanguage (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/parse.ts:232:18)
    at getLanguage (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/parse.ts:253:34)
    at parseTreeSitter (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/parse.ts:262:36)
    at ze.isEmptyBlockStart (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/parseBlock.ts:327:28)
    at Object.isEmptyBlockStart (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/parseBlock.ts:863:39)
    at MessagePort.<anonymous> (/home/[redacted]/.vscode-server/extensions/github.copilot-1.200.0/prompt/src/worker.js:17:35)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20) {
  code: undefined
}
```

**Comment by ulugbekna** [comment]
Hi, this repo is for Copilot Chat extension. For Copilot extension, please report here - https://github.com/community/community/discussions/categories/copilot
