### ISSUE TITLE
terrible failure mode with expired Copilot subscription

### ISSUE THREAD

**Issue by allixsenos** [microsoft/vscode-copilot-release#1340]
forking this from #1294 discussion per @lramos15 instructions

I had a personal Copilot subscription which expired mid-May.

Before it expired, I was added to an org which *had* a Copilot subscription but prohibited Chat.

My Chat experience in VSCode was completely broken, and so was the quick-fix interface, with completely useless error messages:
* when I triggered the quick-fix interface with my shortcut, I'd get a VSCode error bubble saying the command something.quickfix didn't exist
* the Chat window was completely dead on stable VSCode
* the Chat window was throwing "Unable to resolve chat model with family selection: gpt-4" on VSCode Insiders

Several updates, restarts, upgrades and rollbacks did nothing for the issues. Similarly with disabling ALL OTHER extensions.

- Copilot Chat Extension Version: latest and pre-release
- VS Code Version: Latest stable and Insiders
- OS Version: MacOS 14.4.1
- Logs:

```
2024-06-24 20:56:55.190 [error] Activating extension GitHub.copilot-chat failed due to an error:
2024-06-24 20:56:55.190 [error] Error: Unable to resolve embeddings model with family selection: text-embedding-ada-002
    at RA.getEmbeddingsModel (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:1316:2737)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HC.getEmbeddingsEndpoint (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:1316:5985)
    at t.getRemoteContainer (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:3234)
    at t.getRemoteCacheLatestUpdateURL (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:3599)
    at t.fetchRemoteCacheLatest (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:4228)
    at t.getCache (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:4526)
    at t.getCache (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:6114)
    at bU._calculateEmbeddings (/Users/allixsenos/.vscode-insiders/extensions/github.copilot-chat-0.17.2024062401/dist/extension.js:182:8420)
```

The problems fully went away when I left the organization which was granting me Copilot with Chat disabled, at which point I could see my personal subscription had lapsed and I could renew it.

**Comment by lramos15** [comment]
This will be fixed in the pre-release next week.

Thanks for the report
