### ISSUE TITLE
Unable to install extension in VSCodium 1.89.1

### ISSUE THREAD

**Issue by davidalo** [microsoft/vscode-copilot-release#1341]
```

$ codium --install-extension ~/Downloads/GitHub.copilot-chat-0.17.2024062501.vsix
Installing extensions...
Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VSCodium '1.89.1'.
    at Y.install (/snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:56:83043)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m.installVSIX (/snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:37:1177)
    at async /snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:36:9815
    at async Promise.all (index 0)
    at async m.installExtensions (/snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:36:9752)
    at async /snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:58:9224
    at async Object.he [as main] (/snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:58:14700)
    at async h (/snap/codium/394/usr/share/codium/resources/app/out/vs/code/node/cli.js:33:29441)
Failed Installing Extensions: file:///home/david/Downloads/GitHub.copilot-chat-0.17.2024062501.vsix
```

- Copilot Chat Extension Version: GitHub.copilot-chat-0.17.2024062501.vsix
- VS Code Version: 1.89.1
- OS Version: Kubuntu 24.04
- Logs:

Steps to Reproduce:

1.
2.

**Comment by Silverbullet069** [comment]
Did you try to downgrade VSCodium? Which version works?

**Comment by wpinfusion** [comment]
I have this issue on VSCodum 1.94.2, and I tried downgrading to 1.91.1. Copilot installs, but Copilot Chat doesn't.

> Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VSCodium '1.91.1'.

Both Copilot as Copilot Chat are also not available in the Extensions list when searching.
