### ISSUE TITLE
Unable to resolve chat model with family selection: gpt-4

### ISSUE THREAD

**Issue by Denishollerbach** [microsoft/vscode-copilot-release#1361]
- Copilot Extension Version: v1.208.0
- Copilot Chat Extension Version: v0.16.1

- VS Code Version: Version: 
          Version: 1.90.1 (Universal)
          Commit: 611f9bfce64f25108829dd295f54a6894e87339d
          Date: 2024-06-11T21:02:41.372Z
          Electron: 29.4.0
          ElectronBuildId: 9593362
          Chromium: 122.0.6261.156
          Node.js: 20.9.0
          V8: 12.2.281.27-electron.0
          OS: Darwin x64 21.6.0

- macOS Version: macOS MONTEREY 12.7.4 (21H1123)

- Logs:
2024-07-02 09:54:45.756 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 09:54:45.756 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 09:54:45.756 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 09:54:45.756 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 09:54:45.756 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 09:54:45.756 [info] [auth] Logged in as Denishollerbach
2024-07-02 09:54:46.162 [info] [chat] copilot token chat_enabled: true
2024-07-02 09:54:46.162 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 09:54:46.162 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 09:54:46.178 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 09:54:46.839 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 09:55:04.890 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 09:55:04.890 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 09:55:04.890 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 09:55:04.890 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 09:55:04.890 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 09:55:04.971 [info] [auth] Logged in as Denishollerbach
2024-07-02 09:55:05.658 [info] [chat] copilot token chat_enabled: true
2024-07-02 09:55:05.658 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 09:55:05.658 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 09:55:05.673 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 09:55:06.420 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 09:55:17.134 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 09:55:17.134 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 09:55:17.134 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 09:55:17.134 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 09:55:17.135 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 09:55:17.205 [info] [auth] Logged in as Denishollerbach
2024-07-02 09:55:18.006 [info] [chat] copilot token chat_enabled: true
2024-07-02 09:55:18.006 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 09:55:18.006 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 09:55:18.023 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 09:55:18.731 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 09:55:50.498 [info] [extension] Error: Unable to resolve model with family selection: gpt-4
    at Z2.getChatModel (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:1164:5671)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at IT.getChatEndpoint (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:1164:7377)
    at Function.createIntentInvocation (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:818:5585)
    at K6._provideResponseWithProgress (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:844:553)
    at K6.provideResponseWithProgress (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:842:8996)
    at n.z (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.1/dist/extension.js:854:1972)
    at m.$invokeAgent (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:49553)
2024-07-02 09:56:17.677 [info] [FetcherService] Using Helix fetcher
2024-07-02 09:56:17.677 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 09:56:18.046 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 09:56:18.046 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 09:56:18.046 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 09:56:19.032 [info] [auth] Logged in as Denishollerbach
2024-07-02 09:56:19.731 [info] [chat] copilot token chat_enabled: true
2024-07-02 09:56:19.732 [info] [chat] Registration of interactive providers failed:,TypeError: le.interactive.registerInteractiveSessionProvider is not a function
2024-07-02 09:56:19.732 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 09:56:19.732 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 09:56:19.747 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:03:08.775 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 10:03:08.776 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 10:03:08.776 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 10:03:08.776 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 10:03:08.776 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 10:03:08.847 [info] [auth] Logged in as Denishollerbach
2024-07-02 10:03:09.269 [info] [chat] copilot token chat_enabled: true
2024-07-02 10:03:09.269 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 10:03:09.269 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 10:03:09.284 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:03:09.896 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 10:03:26.744 [info] [FetcherService] Using Helix fetcher
2024-07-02 10:03:26.744 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 10:03:26.744 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 10:03:26.744 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 10:03:26.744 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 10:03:27.251 [info] [auth] Logged in as Denishollerbach
2024-07-02 10:03:27.658 [info] [chat] copilot token chat_enabled: true
2024-07-02 10:03:27.658 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 10:03:27.658 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 10:03:27.673 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:03:32.292 [info] [FetcherService] Using Helix fetcher
2024-07-02 10:03:32.292 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 10:03:32.292 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 10:03:32.292 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 10:03:32.292 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 10:03:32.961 [info] [auth] Logged in as Denishollerbach
2024-07-02 10:03:33.472 [info] [chat] copilot token chat_enabled: true
2024-07-02 10:03:33.472 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 10:03:33.472 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 10:03:33.488 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:04:16.914 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 10:04:16.914 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 10:04:16.914 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 10:04:16.914 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 10:04:16.914 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 10:04:16.978 [info] [auth] Logged in as Denishollerbach
2024-07-02 10:04:17.607 [info] [chat] copilot token chat_enabled: true
2024-07-02 10:04:17.607 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 10:04:17.607 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 10:04:17.623 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:04:18.408 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 10:04:25.846 [info] [FetcherService] Using the Helix fetcher.
2024-07-02 10:04:25.846 [info] [gitExtensionService] Initializing Git extension service.
2024-07-02 10:04:25.846 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-02 10:04:25.846 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-02 10:04:25.846 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-02 10:04:25.976 [info] [auth] Logged in as Denishollerbach
2024-07-02 10:04:26.400 [info] [chat] copilot token chat_enabled: true
2024-07-02 10:04:26.400 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-07-02 10:04:26.400 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-02 10:04:26.416 [info] [auth] Got Copilot token for Denishollerbach
2024-07-02 10:04:27.234 [info] [RemoteAgents] Failed to load remote slash commands: ate: self signed certificate in certificate chain
2024-07-02 10:04:36.758 [info] [extension] Error: Unable to resolve model with family selection: gpt-4
    at Z2.getChatModel (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:1164:5671)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at IT.getChatEndpoint (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:1164:7377)
    at Function.createIntentInvocation (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:818:5585)
    at K6._provideResponseWithProgress (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:844:553)
    at K6.provideResponseWithProgress (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:842:8996)
    at n.z (/Users/denis.pereira/.vscode/extensions/github.copilot-chat-0.16.0/dist/extension.js:854:1972)
    at m.$invokeAgent (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:49553)
2024-07-02 10:04:42.275 [info] [extension] Error: Unable to resolve model with family selection: gpt-4

Steps to Reproduce:

1. instalar a extensao, conecatar com a conta do git hub
2. Testar o chat, perguntar algo com cmd + i, com cmd + shift + i e nada funciona sempre dando o erro de family selection seja gpt-4 ou gpt-3.5turbo

![image](https://github.com/microsoft/vscode-copilot-release/assets/42684336/415d8ac6-6399-4e3a-92a2-181a03fcde23)

**Comment by sdheepakdba** [comment]
We are also getting same issue

**Comment by leahrdt** [comment]
@aeschli Since today I have the same problem, I have windows 11 enterprice, it does not work neither in VS Code nor in Visual Studio 2022.

This is the last line of the problem in the visual studio code chat log: Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:49553)
This is the last line of the problem in the visual studio 2022 chat log: [Conversations Information] [CopilotCompletions] Error while processing the event: The SSL connection could not be established, see inner exception.

**Comment by chrmarti** [comment]
Please update to VS Code 1.91.0 and GitHub Copilot Chat 0.17.0.

If it doesn't work with these versions, please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

**Comment by leahrdt** [comment]
@chrmarti  I have  VS Code 1.91.0 and GitHub Copilot Chat 0.17.0. and I continued with the same problem:

workbench.desktop.main.js:sourcemap:139 [Extension Host] [extension] Error: Unable to resolve chat model with family selection: gpt-4
at UA.getChatModel (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2578)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ZT.getChatEndpoint (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
at t.invoke (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:839:3611)
at aM._provideResponseWithProgress (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
at aM.provideResponseWithProgress (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
at n.y (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
at g.$invokeAgent (c:\Users\vmvv\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)

Thank You

**Comment by alexdegtiar** [comment]
I have just set up copilot and am getting the same issue. Rolling back to some recent versions of the extensions has the same behavior (or a different non-functional behavior).

**Comment by chrmarti** [comment]
Please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

**Comment by leahrdt** [comment]
@chrmarti 
## GitHub Copilot Chat

- Extension Version: 0.17.1 (prod)
- VS Code: vscode/1.91.1
- OS: Windows

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": false,
    "debug.useNodeFetcher": false
  }
```

DNS Lookup api.githubcopilot.com: 140.82.114.22

Fetching https://api.githubcopilot.com/_ping:
- Electron Fetcher: Error: net::ERR_CONNECTION_RESET
- Node Fetcher: Error: read ECONNRESET
- Helix Fetcher (configured): Error: read ECONNRESET

**Comment by mofa65** [comment]
Hello, I changed my windows password and since then I also receive the same error, I run the github co pilot via WSL in VS code in a container, the problem reported today, it was running fine before. I have updated the proxy(cntlm) after updating the password. 
`2024-07-15 10:16:02.587 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-07-15 10:16:02.652 [info] [auth] Sucessfully authenticated
2024-07-15 10:16:03.051 [error] [default] Error sending telemetry FetchError: Unspecified GSS failure.  Minor code may provide more information: No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
    at fetch (/home/fao5fe/.vscode-server/extensions/github.copilot-1.212.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at cachingFetch (/home/fao5fe/.vscode-server/extensions/github.copilot-1.212.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Sq.fetch (/home/fao5fe/.vscode-server/extensions/github.copilot-1.212.0/lib/src/network/helix.ts:92:22) {
  type: 'system',
  _name: 'FetchError',
  code: undefined,
  errno: undefined,
  erroredSysCall: undefined
}
2024-07-15 10:20:21.830 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.`

**Comment by chrmarti** [comment]
@mofa65 If this is triggered by the password change, maybe you need to update your Kerberos config in WSL? The log suggests some issue with Kerberos authentication. Also join https://github.com/microsoft/vscode-copilot-release/issues/1380 which is about WSL and Kerberos.

**Comment by leahrdt** [comment]
> @mofa65 If this is triggered by the password change, maybe you need to update your Kerberos config in WSL? The log suggests some issue with Kerberos authentication. Also join #1380 which is about WSL and Kerberos.

Hi @chrmarti  
this morning I changed the error when trying to query github copilot chat, now it tells me the following:
GitHub Copilot
read ECONNRESET

**Comment by chrmarti** [comment]
(Continuing with @leahrdt in https://github.com/microsoft/vscode-copilot-release/issues/1362#issuecomment-2227914999.)

**Comment by mofa65** [comment]
> @mofa65 If this is triggered by the password change, maybe you need to update your Kerberos config in WSL? The log suggests some issue with Kerberos authentication. Also join #1380 which is about WSL and Kerberos.

How shall I update Kerberos?

**Comment by mofa65** [comment]
> > @mofa65 If this is triggered by the password change, maybe you need to update your Kerberos config in WSL? The log suggests some issue with Kerberos authentication. Also join #1380 which is about WSL and Kerberos.
> 
> How shall I update Kerberos?

Updating to latest 1.91.1 resolved the issue. Thank you

**Comment by chrmarti** [comment]
Great! Closing this issue since it looks like all threads have been resolved or continue elsewhere. Thanks.
