### ISSUE TITLE
Problem GitHub Copilot Chat

### ISSUE THREAD

**Issue by sdheepakdba** [microsoft/vscode-copilot-release#1362]
- Copilot Chat Extension Version:12,109,155
- VS Code Version:1.092
- OS Version: Windows 10
- Logs:

Errors :- Unable to resolve model with family selection: gpt-4

**Comment by leahrdt** [comment]
Since today I have the same problem, I have windows 11 enterprice, it does not work neither in VS Code nor in Visual Studio 2022.

**Comment by ulugbekna** [comment]
Hi, could you please share the logs from the Developer Tools (invoke command "Toggle Developer Tools" from the command palette (press F1 to open)) ?

**Comment by ulugbekna** [comment]
/duplicate https://github.com/microsoft/vscode-copilot-release/issues/1361

**Comment by chrmarti** [comment]
Please update to VS Code 1.91.0 and GitHub Copilot Chat 0.17.0.

If it doesn't work with these versions, please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

**Comment by leahrdt** [comment]
@chrmarti  I have VS Code 1.91.0 and GitHub Copilot Chat 0.17.0.

and I continued with the same problem:

workbench.desktop.main.js:sourcemap:139 [Extension Host] [extension] Error: Unable to resolve chat model with family selection: gpt-4
at UA.getChatModel (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2578)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ZT.getChatEndpoint (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
at t.invoke (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:839:3611)
at aM._provideResponseWithProgress (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
at aM.provideResponseWithProgress (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
at n.y (c:\Users\vmvv\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
at g.$invokeAgent (c:\Users\vmvv\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)

thank you

**Comment by chrmarti** [comment]
Please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

**Comment by leahrdt** [comment]
> Please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

This is the output: 

workbench.desktop.main.js:sourcemap:139 [Extension Host] [extension] Error: Unable to resolve chat model with family selection: gpt-4
at UA.getChatModel (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2578)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ZT.getChatEndpoint (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
at t.invoke (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:839:3611)
at aM._provideResponseWithProgress (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
at aM.provideResponseWithProgress (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
at n.y (c:\Users\vmvv.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
at g.$invokeAgent (c:\Users\vmvv\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)

**Comment by sacalata** [comment]
> @hediet Since today I have the same problem, I have windows 11 enterprice, it does not work neither in VS Code nor in Visual Studio 2022.
> 
> This is the last line of the problem in the visual studio code chat log: Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:49553) This is the last line of the problem in the visual studio 2022 chat log: [Conversations Information] [CopilotCompletions] Error while processing the event: The SSL connection could not be established, see inner exception.

I'm having the exact same problem and it started about a week ago...

**Comment by sacalata** [comment]
From chat diagnostics
`DNS Lookup api.githubcopilot.com: 140.82.112.22

Fetching https://api.githubcopilot.com/_ping:
- Electron Fetcher: Error: net::ERR_CERT_DATE_INVALID
- Node Fetcher: Error: certificate has expired
- Helix Fetcher (configured): Error: certificate has expired`

**Comment by chrmarti** [comment]
@sacalata Thanks, could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` for `https://api.githubcopilot.com` in VS Code?

**Comment by leahrdt** [comment]
@chrmarti 
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286)
Network Proxy Test 0.0.11
win32 10.0.22631 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://api.githubcopilot.com...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://api.githubcopilot.com (allowing unauthorized)...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)

**Comment by chrmarti** [comment]
The error message changed. Are you behind a firewall that might need to allow-list api.githubcopilot.com?

Could you also run `F1` > `GitHub Copilot: Collect Diagnostics`? That will check a few more hosts that are also needed by the GitHub Copilot extensions.

**Comment by leahrdt** [comment]
@chrmarti This is the result of GitHub Copilot: Collect Diagnostics

## Copilot

- Version: 1.213.0
- Build: prod
- Editor: vscode/1.91.1

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: c:\Users\vmvv\.vscode\extensions\ukoloff.win-ca-3.5.1\node_modules\win-ca\pem
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: disabled
- Chat: enabled

## Node setup

- Number of root certificates: 141
- Operating system: Windows_NT
- Operating system version: 10.0.22631
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: read ECONNRESET
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: true
- Is `mac-ca` installed?: false

## Authentication

- GitHub username: leahrdt

**Comment by benimue** [comment]
I had a similar or maybe even the same issue and got copilot chat working again adding the following setting (and restarting VS code afterwards):
```
"github.copilot.advanced": {
    "debug.useElectronFetcher": true,
},
```
See additional info [here](https://github.com/microsoft/vscode-copilot-release/issues/1032)

**Comment by chrmarti** [comment]
@leahrdt `api.githubcopilot.com` seems to be the only host that is not reachable. Please check with your IT and let them allow-list `https://*.githubcopilot.com` in the company network. Also see: https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot

**Comment by leahrdt** [comment]
Perfect, it's solved! thank you

**Comment by Willaaaaaaa** [comment]
@chrmarti Hello, Mr. Marti. This is my result. And, it's clear that both `github.com` and `api.githubcopilot.com` are not reachable. But I don't know how to put them into the allow-list. Could you please tell me the method? Besides, I'm not sure whether `Is "win-ca" installed?: false` is relevant to the error massage? Should I install the extension `win-ca`? Thanks for your attention.

## Copilot

- Version: 1.219.0
- Build: prod
- Editor: vscode/1.91.1

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: enabled
- Chat: enabled

## Node setup

- Number of root certificates: 141
- Operating system: Windows_NT
- Operating system version: 10.0.22631
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- _**github.com: read ECONNRESET**_
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- _**api.githubcopilot.com: read ECONNRESET**_
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- _**Is `win-ca` installed?: false**_
- _**Is `mac-ca` installed?: false**_

## Authentication

- GitHub username: Willaaaaaaa

**Comment by chrmarti** [comment]
@Willaaaaaaa Is this in a company network? If so, please share the following documentation with your IT department asking them to allow-list the required hosts: https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot

**Comment by Willaaaaaaa** [comment]
@chrmarti No, sir. I'm at home. Is there any possible solution?
Sorry to bother you, but I'm really a beginner in computer science learning and have no idea on how to deal with such problem. It's so kind of you for replying me.

**Comment by chrmarti** [comment]
@Willaaaaaaa The mixed reachability results look similar to what you might see with a firewall that needs to allow-list more hosts:
- _**github.com: read ECONNRESET**_
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- _**api.githubcopilot.com: read ECONNRESET**_
- default.exp-tas.com: HTTP 200

Maybe you are using some VPN? Could you also run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the result here?

**Comment by Willaaaaaaa** [comment]
@chrmarti Yes, sir. I use VPN sometimes because I'm in China. But regardless of whether I use VPN or not, it will display an error message. Here are the results. Thanks again for your reply.

- # **This is the result when I use VPN:**

## GitHub Copilot Chat

- Extension Version: 0.17.1 (prod)
- VS Code: vscode/1.91.1
- OS: Windows

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": false,
    "debug.useNodeFetcher": false
  }
```

DNS Lookup api.githubcopilot.com: 140.82.113.22

Fetching https://api.githubcopilot.com/_ping:
- Electron Fetcher: HTTP 200
- Node Fetcher: HTTP 200
- Helix Fetcher (configured): Error: read ECONNRESET

------------------------------------------------------------------

- # **And the result when not using VPN and only using home network:**

## GitHub Copilot Chat

- Extension Version: 0.17.1 (prod)
- VS Code: vscode/1.91.1
- OS: Windows

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": false,
    "debug.useNodeFetcher": false
  }
```

DNS Lookup api.githubcopilot.com: 140.82.113.21

Fetching https://api.githubcopilot.com/_ping:
- Electron Fetcher: Error: net::ERR_CONNECTION_RESET
- Node Fetcher: HTTP 200
- Helix Fetcher (configured): Error: read ECONNRESET

**Comment by chrmarti** [comment]
Given these results you could try adding the follow to your user settings (`F1` > `Preferences: Open User Settings (JSON)`):
```json
  "github.copilot.advanced": {
    "debug.useNodeFetcher": true
  }
```
And then restart VS Code.

**Comment by Willaaaaaaa** [comment]
@chrmarti OMG!! It really works!!!! You really are the smartest programmer I have ever met so far! Thank you, sir! Love you!

**Comment by Willaaaaaaa** [comment]
@chrmarti  Bad news, sir. My coplilot seems to be unable to access the internet normally again. The diagnostic reports of `Electron Fetcher`, `Node Fetcher` and `Helix Fetcher` sometimes report error at the same time. I tried to change the DNS of `api.githubcopilot.com` to `140.82.113.21`, which made `Node Extractor` work properly yesterday, but it still didn't work. What should I do now? Sorry to bother you again, but you are the best man I can think of.

The network issue is a bit strange, sometimes it can connect normally, and sometimes it cannot. And based on my observation, it have nothing to do with VPN. It more likely to be a probabilistic event.

**Comment by sdheepakdba** [comment]
Thanks , Please close the request
