### ISSUE TITLE
Unable to resolve chat model with family selection: gpt-4

### ISSUE THREAD

**Issue by catJoeIrving** [microsoft/vscode-copilot-release#1370]
- Copilot Chat Extension Version: v0.17.0
- VS Code Version: 1.91
- OS Version: Windows 10
- Logs:

2024-07-05 15:06:36.558 [info] [ModelMetadataFetcher] Failed to fetch models, see: read ECONNRESET
    at m2e (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:29562)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Kit (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:31587)
    at $T.fetch (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1285:2373)
    at UA._fetchModels (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:3167)
    at UA.getChatModel (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2329)
    at ZT.getChatEndpoint (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
    at t.invoke (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:839:3611)
    at aM._provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
    at aM.provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
    at n.y (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
    at g.$invokeAgent (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)
2024-07-05 15:06:36.559 [info] [extension] Error: Unable to resolve chat model with family selection: gpt-4
    at UA.getChatModel (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2578)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZT.getChatEndpoint (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
    at t.invoke (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:839:3611)
    at aM._provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
    at aM.provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
    at n.y (c:\Users\User\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
    at g.$invokeAgent (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)

Steps to Reproduce:

1. Type something into GitHub Copilot Chat
2. Hit enter

**Comment by chrmarti** [comment]
Please run `F1` > `Developer: GitHub Copilot Chat Diagnostics` and share the output here.

**Comment by CathySoMcK** [comment]
@chrmarti 
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

GitHub Copilot Chat: v0.17.2024062801 (pre-release)

I get this when I try to run F1 > Developer: GitHub Copilot Chat Diagnostics

![image](https://github.com/microsoft/vscode-copilot-release/assets/32909317/eb120772-2b27-424b-afdc-2dc161cd4dc2)

**Comment by mcfalld** [comment]
I'm having the exact same problem as @CathySoMcK

**Comment by AgidensKevinG** [comment]
Exactly same versions and errors here as mentioned above (it worked two weeks ago but suddenly broke).

Important side note: it is broken when I use it inside a Dev Container, works fine outside (GitHub Copilot + GitHub Copilot Chat are both installed inside the Dev Container).

**Comment by catJoeIrving** [comment]
@chrmarti I get the same error message as Cathy

**Comment by zacharymuehlich** [comment]
Same issue here @chrmarti ...

Copilot Chat Diagnostics: Failed with the same message as Cathy.

GitHub Copilot: Collect Diagnostics:

```
## Copilot

- Version: 1.211.0
- Build: prod
- Editor: vscode/1.91.0

## Environment

- http_proxy: n/a
- https_proxy: n/A
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: c:\Users\zacharymuehlich\.vscode\extensions\ukoloff.win-ca-3.5.1\node_modules\win-ca\pem
- OPENSSL_CONF: n/a

## Feature FLAGS

- Send Restricted Telemetry: DISABLED
- Chat: enabled

## Node setup

- Number of root certificates: 141
- Operating system: Windows_NT
- Operating system version: 10.0.22631
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: C:\ProgramData\companyname\companyrootcert.pem
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: HTTP 200 - OK
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: true
- Is `mac-ca` installed?: false

## Authentication

- GitHub username: zacharymuehlich
```

GitHub Copilot: Open Chat Logs:

```
2024-07-09 11:55:14.063 [info] [FetcherService] Using the Helix fetcher.
2024-07-09 11:55:14.064 [info] [gitExtensionService] Initializing Git extension service.
2024-07-09 11:55:14.064 [info] [auth] Logged in as zacharymuehlich
2024-07-09 11:55:14.064 [info] [auth] Logged in as zacharymuehlich
2024-07-09 11:55:14.487 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-09 11:55:14.487 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-09 11:55:14.487 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-09 11:55:53.260 [info] [FetcherService] Using the Helix fetcher.
2024-07-09 11:55:53.261 [info] [gitExtensionService] Initializing Git extension service.
2024-07-09 11:55:53.261 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-09 11:55:53.261 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-09 11:55:53.261 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-09 11:55:53.261 [info] [auth] Logged in as zacharymuehlich
2024-07-09 11:55:53.261 [info] [auth] Logged in as zacharymuehlich
2024-07-09 11:56:00.990 [info] [chat] copilot token chat_enabled: true
2024-07-09 11:56:00.990 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-09 11:56:00.997 [info] [auth] Got Copilot token for zacharymuehlich
2024-07-09 11:56:01.008 [info] [chat] copilot token chat_enabled: true
2024-07-09 11:56:01.008 [info] [auth] Got Copilot token for zacharymuehlich
2024-07-09 11:56:02.330 [info] [auth] Logged in as zacharymuehlich
2024-07-09 11:56:02.420 [info] [chat] copilot token chat_enabled: true
2024-07-09 11:56:02.420 [info] [auth] Got Copilot token for zacharymuehlich
2024-07-09 11:56:08.528 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:13994)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09 11:56:09.452 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:13994)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09 11:59:46.329 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:13994)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09 12:11:08.833 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:13994)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09 12:17:41.094 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:74:13994)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09 12:17:41.098 [info] [extension] Error: Unable to resolve chat model with family selection: gpt-4
    at UA.getChatModel (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:2578)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZT.getChatEndpoint (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:1317:5768)
    at _M.invoke (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:900:16802)
    at aM._provideResponseWithProgress (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:872:1222)
    at aM.provideResponseWithProgress (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:870:4601)
    at n.y (c:\Users\zacharymuehlich\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:882:1826)
    at g.$invokeAgent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:50217)
```

**Comment by ahanyyev** [comment]
Once I started on the new project same issue started to appear tried to switch Gateway worked for a while then again started to show above issue.

**Comment by root-hbx** [comment]
2024-07-10 11:03:14.443 [info] [FetcherService] Using the Helix fetcher.
2024-07-10 11:03:14.443 [info] [gitExtensionService] Initializing Git extension service.
2024-07-10 11:03:14.443 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-10 11:03:14.443 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-10 11:03:14.443 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-10 11:03:14.596 [info] [auth] Logged in as copilot_haha
2024-07-10 11:03:14.596 [info] [auth] Logged in as copilot_haha
2024-07-10 11:03:15.090 [info] [chat] copilot token chat_enabled: true
2024-07-10 11:03:15.090 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-10 11:03:15.096 [info] [auth] Got Copilot token for copilot_haha
2024-07-10 11:03:15.104 [info] [auth] Logged in as copilot_haha
2024-07-10 11:03:15.108 [info] [chat] copilot token chat_enabled: true
2024-07-10 11:03:15.108 [info] [auth] Got Copilot token for copilot_haha
2024-07-10 11:03:15.591 [info] [chat] copilot token chat_enabled: true
2024-07-10 11:03:15.591 [info] [auth] Got Copilot token for copilot_haha
2024-07-10 11:03:16.131 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
at JSON.parse ()
at t.json (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:66:28638)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at UA._fetchModels (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:3403)
at UA.getAllChatModels (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2201)
at ZT.getAllChatEndpoints (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:6310)
at p (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1115:593)
at sRe (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1115:1332)
at Kct (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:7703)
at c.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6384)
at c.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6347)
at c.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:5804)
2024-07-10 11:03:16.461 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
at JSON.parse ()
at t.json (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:66:28638)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at UA._fetchModels (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:3403)
at UA.getEmbeddingsModel (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2685)
at ZT.getEmbeddingsEndpoint (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:6119)
at sRe (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1115:1436)
at Kct (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:7703)
at c.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6384)
at c.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6347)
at c.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:5804)
2024-07-10 11:03:17.224 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
at JSON.parse ()
at t.json (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:66:28638)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at UA._fetchModels (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:3403)
at UA.getChatModel (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2329)
at ZT.getChatEndpoint (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:5768)
at t.invoke (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:839:3611)
at aM._provideResponseWithProgress (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:872:1222)
at aM.provideResponseWithProgress (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:870:4562)
at n.y (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:882:1826)
at g.$invokeAgent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:50217)
2024-07-10 11:03:17.225 [info] [extension] Error: Unable to resolve chat model with family selection: gpt-4
at UA.getChatModel (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2578)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ZT.getChatEndpoint (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:5768)
at t.invoke (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:839:3611)
at aM._provideResponseWithProgress (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:872:1222)
at aM.provideResponseWithProgress (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:870:4562)
at n.y (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:882:1826)
at g.$invokeAgent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:50217)
2024-07-10 11:05:10.449 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
at JSON.parse ()
at t.json (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:66:28638)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at UA._fetchModels (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:3403)
at UA.getEmbeddingsModel (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2685)
at ZT.getEmbeddingsEndpoint (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:6119)
at t.getRemoteContainer (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:3234)
at t.getRemoteCacheLatestUpdateURL (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:3599)
at t.fetchRemoteCacheLatest (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:4228)
at t.getCache (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:4526)
at t.getCache (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:6114)
at RU._calculateEmbeddings (/Users/huluobo/.vscode/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:182:8420)

I have also encountered the same problem.
I checked the network proxy and it was fine. However, my vscode login interface showed two accounts, one was my personal account that was not registered with copilot, and the other was an account that the company had registered with copilot.
Is it because of the account?

I think maybe this logging statement showcases the reason?

2024-07-10 11:03:16.131 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON

**Comment by mahisat** [comment]
I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.

Here are the steps I took to resolve it:

1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:

```
 "github.copilot.advanced": {
  "debug.useNodeFetcher": true
}

```
2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.

**Comment by sshamim-3cps** [comment]
> I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> 
> Here are the steps I took to resolve it:
> 
> 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> 
> ```
>  "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```
> 
> 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.

Didn't work for me, still getting the same. This seems to be a fresh issue and impacting a lot users.

Did you explore any other workarounds?

**Comment by SathyaLab** [comment]
I am also facing the same issue. - 
unable to resolve chat model with family selection: gpt-4

**Comment by mahisat** [comment]
> > I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> > Here are the steps I took to resolve it:
> > 
> > 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> > 
> > ```
> >  "github.copilot.advanced": {
> >   "debug.useNodeFetcher": true
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.
> 
> Didn't work for me, still getting the same. This seems to be a fresh issue and impacting a lot users.
> 
> Did you explore any other workarounds?

Just now my friend faced same issue we resolved it by updating vscode's user level settings

C:\Users\<Your Username>\AppData\Roaming\Code\User\settings.json

Add the following line and then reload/reopen VS Code

"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}

**Comment by AgidensKevinG** [comment]
Thank you, this worked for me :)

**Comment by CathySoMcK** [comment]
> > > I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> > > Here are the steps I took to resolve it:
> > > 
> > > 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> > > 
> > > ```
> > >  "github.copilot.advanced": {
> > >   "debug.useNodeFetcher": true
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.
> > 
> > 
> > Didn't work for me, still getting the same. This seems to be a fresh issue and impacting a lot users.
> > Did you explore any other workarounds?
> 
> Just now my friend faced same issue we resolved it by updating vscode's user level settings
> 
> C:\Users<Your Username>\AppData\Roaming\Code\User\settings.json
> 
> Add the following line and then reload/reopen VS Code
> 
> "github.copilot.advanced": { "debug.useNodeFetcher": true }

None of these worked for me :(

**Comment by semihucari** [comment]
> I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> 
> Here are the steps I took to resolve it:
> 
> 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> 
> ```
>  "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```
> 
> 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.

Same here, none working

**Comment by CathySoMcK** [comment]
> if you are using copilot business, or copilot as part of a github org check your policy settings github->org->copilot->policy mine default to disable IDE

Ours is set to Enabled and I am a member of the correct group to use copilot chat.

**Comment by murilommm192** [comment]
> > > I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> > > Here are the steps I took to resolve it:
> > > 
> > > 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> > > 
> > > ```
> > >  "github.copilot.advanced": {
> > >   "debug.useNodeFetcher": true
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.
> > 
> > 
> > Didn't work for me, still getting the same. This seems to be a fresh issue and impacting a lot users.
> > Did you explore any other workarounds?
> 
> Just now my friend faced same issue we resolved it by updating vscode's user level settings
> 
> C:\Users<Your Username>\AppData\Roaming\Code\User\settings.json
> 
> Add the following line and then reload/reopen VS Code
> 
> "github.copilot.advanced": { "debug.useNodeFetcher": true }

This one worked for me, thanks!

**Comment by catJoeIrving** [comment]
> 2 issues make it difficult to investigate these errors:
> 
> * The generic errors message, we should surface the original error. (Fixed in main.)
> * The diagnostic command is not registered when loading of modules fails. (This seems to be fixed in latest pre-release versions.)
> 
> PR for 0.17.x: https://github.com/microsoft/vscode-copilot/pull/6661

I switched to PR version and still get the same error when trying to run diagnostics

**Comment by zacharymuehlich** [comment]
This was resolved for us by implementing firewall changes to allow traffic to/from the *presumably* new api.githubcopilot.com URL.

**Comment by saldanaj** [comment]
> I faced the same issue: "Unable to resolve chat model with family selection: gpt-4" in VS Code 1.91.0 with Copilot Chat 0.17.0 and Copilot version 1.211.0.
> 
> Here are the steps I took to resolve it:
> 
> 1. In VS Code's settings.json,  added the following configuration and reloaded VS Code. If this works for you, skip step 2:
> 
> ```
>  "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```
> 
> 2. If the issue persists, install the win-ca extension in VS Code and reload VS Code. This step worked for me.

This worked for me so thank you for that - but not finding any documentation that describes what this does or affects.  Any clues?

**Comment by chrmarti** [comment]
There is a new stable version GitHub Copilot Chat 0.17.1 improving the error reporting and fixing the diagnostic command `F1` > `Developer: GitHub Copilot Chat Diagnostics`. Please update to that version and open new bug reports with the updated error message and the output from that diagnostics command. Thanks!
