### ISSUE TITLE
[Copilot chat] Unexpected token 'u', "unauthoriz"... is not valid JSON

### ISSUE THREAD

**Issue by JuanSeBestiaStoerk** [microsoft/vscode-copilot-release#1410]
- Copilot Chat Extension Version: v0.17.1
- VS Code Version: 
```
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:46.768Z (1 wk ago)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.0.0
```
- OS Version: MacOS 14.0 (23A344)
- Logs:
```
2024-07-18 16:21:38.669 [info] [FetcherService] Using the Helix fetcher.
2024-07-18 16:21:38.669 [info] [gitExtensionService] Initializing Git extension service.
2024-07-18 16:21:38.670 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-18 16:21:38.670 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-18 16:21:38.670 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-18 16:21:38.670 [info] [auth] Logged in as JuanSeBestiaStoerk
2024-07-18 16:21:38.670 [info] [auth] Logged in as JuanSeBestiaStoerk
2024-07-18 16:21:39.007 [info] [chat] copilot token chat_enabled: false
2024-07-18 16:21:39.007 [info] [auth] Got Copilot token for JuanSeBestiaStoerk
2024-07-18 16:21:39.014 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-18 16:21:39.047 [info] [auth] Logged in as JuanSeBestiaStoerk
2024-07-18 16:21:39.072 [info] [chat] copilot token chat_enabled: false
2024-07-18 16:21:39.072 [info] [auth] Got Copilot token for JuanSeBestiaStoerk
2024-07-18 16:21:39.081 [info] [chat] copilot token chat_enabled: false
2024-07-18 16:21:39.081 [info] [auth] Got Copilot token for JuanSeBestiaStoerk
2024-07-18 16:21:39.579 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:88:17938)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UA._fetchModels (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:3447)
    at UA.getAllChatModels (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:2201)
    at ZT.getAllChatEndpoints (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1291:6404)
    at p (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1115:593)
    at sRe (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1115:1332)
    at Yct (/Users/JuanSeBestia/.vscode/extensions/github.copilot-chat-0.17.1/dist/extension.js:1317:883)
    at c.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6384)
    at c.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6347)
    at c.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:5804)
```

![image](https://github.com/user-attachments/assets/da295fa3-4bb3-4891-a6e7-5092e89cb5bb)

Steps to Reproduce:

1. Open VSCode
2. Write a message on chat

**Comment by jenssgb** [comment]
I'm facing the same problem with like 4 different clients. 

2024-07-19 07:34:05.729 [info] [extension] SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON

**Comment by knarayananroku99** [comment]
Seeing the same issue

**Comment by syouness-bc** [comment]
seeing the same issue

**Comment by heyitsbryanm** [comment]
> Also seeing the same issue across 3 different people in our organization

Turns out co-pilot chat was not enabled in GitHub. Our admin enabled it and it fixed the issue for our org.

**Comment by lramos15** [comment]
When you see `copilot token chat_enabled: false` this indicates that chat is not enabled by your organization. We've added some UI to explain this in the next release.

**Comment by kyranjamie** [comment]
I'm owner of an organisation with Copilot enabled, with a seat assigned to me, and I still see this issue.

**Comment by lramos15** [comment]
@kyranjamie You need to enable chat in your organization admin setting
