### ISSUE TITLE
[ModelMetadataFetcher] Failed to fetch models Error: Failed to fetch models: too many requests

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode-copilot-release#1415]
- VS Code Version: 1.92.0-insider
- OS Version: Sonoma 14.5

Steps to Reproduce:

1. Create a chat participant with `vscode.chat.createChatParticipant()` (the API is called once, all Copilot policies are enabled on GitHub)
2. Check `Debug Console`
3. Observe about 300 identical errors. While they are being printed the chat UI hangs and does not react on submitting prompts

```
[ModelMetadataFetcher] Failed to fetch models Error: Failed to fetch models: too many requests

    at yA._fetchModels (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14574)
    at processTicksAndRejections (/Users/alena.khineika/www/vscode/lib/internal/process/task_queues.js:95:5)
    at yA.getChatModel (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13516)
    at bT.getChatEndpoint (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17127)
    at W0 (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2993)
    at Nx.chunkFileNaive (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:813)
    at tH.getBasicChunks (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7193)
    at async Promise.all (index 55)
    at cf.getChunksToSearch (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:31007)
    at /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:32813
    at cf.tryPreInit (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:32313) {stack: 'Error: Failed to fetch models: too many reque…-0.18.2024071701/dist/extension.js:250:32313)', message: 'Failed to fetch models: too many requests
'}
arg2: Error: Failed to fetch models: too many requests\n\n    at yA._fetchModels (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14574)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at yA.getChatModel (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13516)\n    at bT.getChatEndpoint (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17127)\n    at W0 (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2993)\n    at Nx.chunkFileNaive (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:813)\n    at tH.getBasicChunks (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7193)\n    at async Promise.all (index 55)\n    at cf.… …
f @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:6
e @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:47874
<anonymous> @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:47742
logIt @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:6600
<anonymous> @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:5843
logIt @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:5830
log @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:6966
error @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:7360
_fetchModels @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14922
processTicksAndRejections @ internal/process/task_queues:95:5
◀ await ▶
processTicksAndRejections @ internal/process/task_queues:95:5
◀ await ▶
getChatModel @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13527
getChatEndpoint @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17152
W0 @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:3009
yse @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2833
chunkFileNaive @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:819
<anonymous> @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7140
```

There is also another error that is printed once at the very beginning:

```
[RemoteAgents] Unable to fetch remote agents because user is not signed in.
```

**Comment by lramos15** [comment]
We're seeing this fixed in the latest pre-release + vscode insiders. Let me know if you still have issues!
