### ISSUE TITLE
[default] Error sending telemetry FetchError: connect ETIMEDOUT 140.82.114.21:443

### ISSUE THREAD

**Issue by gilmar-oliveira** [microsoft/vscode-copilot-release#1428]
2024-07-27 15:21:01.850 [error] [default] Error sending telemetry FetchError: connect ETIMEDOUT 140.82.114.21:443
    at fetch (c:\Users\gilma\.vscode\extensions\github.copilot-1.219.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (c:\Users\gilma\.vscode\extensions\github.copilot-1.219.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:288:16)
    at XO.fetch (c:\Users\gilma\.vscode\extensions\github.copilot-1.219.0\lib\src\network\helix.ts:96:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ETIMEDOUT',
  errno: -4039,
  erroredSysCall: 'connect'
}
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

![image](https://github.com/user-attachments/assets/d2937812-e425-4550-af8a-1115dee126b7)

**Comment by Patric-BM** [comment]
Cara, agora a pouco eu tava com esse problema. Resolvi da seguinte maneira:
No vscode, vá até File > Preferences > Settings (ou use o atalho Ctrl + ,). Clique no ícone de página com um sinal de adição no canto superior direito para abrir as configurações JSON(Esse botão fica do lado do botão de dividir a tela). Adicione a seguinte configuração no arquivo settings.json:
"github.copilot.advanced": { "debug.useElectronFetcher": true}
Salve o arquivo.
Reinicie o VS Code.
Pelo menos pra mim parou o erro do helix.ts. Tenta aí. ;)

**Comment by ScorchMC** [comment]
> "debug.useElectronFetcher": true

Patric you legend, works perfect now

**Comment by gilmar-oliveira** [comment]
estranho.... mas deu certo... valeuu
