### ISSUE TITLE
Copilot Chat Extension SyntaxError :  [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<html>

### ISSUE THREAD

**Issue by vinod-vaddi** [microsoft/vscode-copilot-release#1433]
- Copilot Chat Extension Version: v0.17.1
- VS Code Version: 1.19.1 (user setup)
- OS Version: 
- Logs:
2024-07-30 07:42:29.213 [info] [auth] Logged in as user1

2024-07-30 07:42:29.229 [info] [chat] copilot token chat_enabled: true

2024-07-30 07:42:29.229 [info] [auth] Got Copilot token for user1

2024-07-30 07:42:29.659 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<html>

<h"... is not valid JSON

    at JSON.parse (<anonymous>)

    at t.json (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:88:17938)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at UA._fetchModels (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:3447)

    at UA.getAllChatModels (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:2201)

    at ZT.getAllChatEndpoints (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:6404)

    at p (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1115:593)

    at sRe (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1115:1332)

    at Yct (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1317:883)

    at c.n (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6384)

    at c.m (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6347)

    at c.l (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5804)

2024-07-30 07:42:29.737 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<html>

<h"... is not valid JSON

    at JSON.parse (<anonymous>)

    at t.json (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:88:17938)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at UA._fetchModels (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:3447)

    at UA.getEmbeddingsModel (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:2707)

    at ZT.getEmbeddingsEndpoint (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1291:6213)

    at sRe (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1115:1436)

    at Yct (c:\Users\XXXXXXX\.vscode\extensions\github.copilot-chat-0.17.1\dist\extension.js:1317:883)

    at c.n (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6384)

    at c.m (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6347)

    at c.l (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5804)

Steps to Reproduce:

1. Open VS Code
2. Try installing GitHub Copilot Chat throws this exception

**Comment by lman34** [comment]
getting a similar error with:
[ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token '<', "<!--# qJfn"... is not valid JSON

**Comment by lramos15** [comment]
Are you behind a corporate firewall of some sorts? 

Please also try the latest 0.18 that was just released
