### ISSUE TITLE
Chat Error: qne is not a constructor

### ISSUE THREAD

**Issue by timhagel** [microsoft/vscode-copilot-release#1437]
- Copilot Chat Extension Version: v0.18.0 and v0.18.2024072603 (pre-release)
- VS Code Version: Version: 1.92.0-insider
- OS Version: Mac OS 15 Beta 2
- Logs:
```
2024-07-30 19:19:40.233 [info] [extension] TypeError: qne is not a constructor
    at t.reference2 (/Users/timothyhagel/.vscode-insiders/extensions/github.copilot-chat-0.18.2024072603/dist/extension.js:220:402)
    at yT._provideResponseWithProgress (/Users/timothyhagel/.vscode-insiders/extensions/github.copilot-chat-0.18.2024072603/dist/extension.js:1281:2456)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at yT.handleRequest (/Users/timothyhagel/.vscode-insiders/extensions/github.copilot-chat-0.18.2024072603/dist/extension.js:1279:2011)
    at t.y (/Users/timothyhagel/.vscode-insiders/extensions/github.copilot-chat-0.18.2024072603/dist/extension.js:1290:1839)
    at s.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:51233)
```

I did fix it once by going to stable and back to pre-release, but that didn't fix it this time

Steps to Reproduce:

1. Prompt GitHub Copilot Chat with anything 
2. Then it will error with `qne is not a constructor`

**Comment by timhagel** [comment]
Updating VS Code seems to fix the issue.

**Comment by rahulmehtas** [comment]
Same question here.

**Comment by rahulmehtas** [comment]
After vscode updated, this question seems to be gone. But Why?

**Comment by lramos15** [comment]
Glad to hear it's resolved 👍
