### ISSUE TITLE
[info] [ModelMetadataFetcher] Failed to fetch models (a5549708-0828-43ab-b21a-e87e0792bcbd), DV: read ECONNRESET

### ISSUE THREAD

**Issue by llifangyin** [microsoft/vscode-copilot-release#1459]
- Copilot Chat Extension Version: v1.221.0
- VS Code Version:1.92.0
- OS Version:win 11
- Logs:

Steps to Reproduce:

1. Open Github CoplitChat and enter something
2.  err: read ECONNRESET
3.  ouput :
 ``` 
[info] [ModelMetadataFetcher] Failed to fetch models (a5549708-0828-43ab-b21a-e87e0792bcbd), DV: read ECONNRESET
    at gde (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:21:29514)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at J7e (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:21:31536)
    at pI.fetch (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:647:2373)
    at Vm._fetchModels (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1356:14828)
    at Vm.getChatModel (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1356:13860)
    at IT.getChatEndpoint (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1356:17758)
    at ta.invoke (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:321:3302)
    at yT._provideResponseWithProgress (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1281:1451)
    at yT.handleRequest (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1279:2011)
    at t.y (c:\Users\ctsi\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1290:1839)
    at s.$invokeAgent (c:\Users\ctsi\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:51474)
```

**Comment by llifangyin** [comment]
![image](https://github.com/user-attachments/assets/c776e864-28b6-474b-87f1-e10d7d97664c)
![image](https://github.com/user-attachments/assets/c8081b82-288d-4ebc-a460-aed8b33c0756)

**Comment by llifangyin** [comment]
Is there any progress? Guys, I can’t use it for a month. Is there any place I can apply for compensation?

**Comment by llifangyin** [comment]
Is there any progress? Guys, I can’t use it for a month. Is there any place I can apply for compensation? 
🥹

**Comment by chrmarti** [comment]
Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.

**Comment by llifangyin** [comment]
> Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.

![image](https://github.com/user-attachments/assets/c4a954de-a322-4bca-a95b-3a6b523dba37)
just like this

**Comment by chrmarti** [comment]
Please add the following to your user settings JSON (`F1` > `Preferences: Open User Settings (JSON)`):
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true
  }
```
This will be the default for the next stable release.

Does this resolve the issue?

**Comment by llifangyin** [comment]
> Please add the following to your user settings JSON (`F1` > `Preferences: Open User Settings (JSON)`):
> 
> ```json
>   "github.copilot.advanced": {
>     "debug.useElectronFetcher": true
>   }
> ```
> 
> This will be the default for the next stable release.
> 
> Does this resolve the issue?

Yes, it worked
Thanks! 👍👍👍
![image](https://github.com/user-attachments/assets/5c7ba644-eca9-4370-9095-98b682a7ffc3)

**Comment by llifangyin** [comment]
"github.copilot.advanced": {
    "debug.useElectronFetcher": true
  }
Changed this to normal use

**Comment by llifangyin** [comment]
"github.copilot.advanced": {
"debug.useElectronFetcher": true
}
Changed this to normal use
