### ISSUE TITLE
unable to get issuer certificate

### ISSUE THREAD

**Issue by idmedia-kannengiesser** [microsoft/vscode-copilot-release#1460]
- Copilot Chat Extension Version:
- VS Code Version: Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Datum: 2024-07-31T23:26:45.634Z (Vor 1 Woche(n))
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
Betriebssystem: Darwin x64 23.5.0
- OS Version: MacOS 14.5 (23F79)
- Logs:
2024-08-08 09:16:35.386 [info] [FetcherService] Using the Helix fetcher.
2024-08-08 09:16:35.386 [info] [gitExtensionService] Initializing Git extension service.
2024-08-08 09:16:35.386 [info] [RemoteAgents] Unable to fetch remote agents because user is not signed in.
2024-08-08 09:16:35.386 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-08-08 09:16:35.386 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-08-08 09:16:35.386 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-08-08 09:16:35.766 [info] [auth] Logged in as user
2024-08-08 09:16:35.766 [info] [auth] Logged in as user
2024-08-08 09:16:35.766 [info] [auth] Logged in as user
2024-08-08 09:16:35.766 [info] [auth] Logged in as user
2024-08-08 09:16:35.766 [info] [auth] Logged in as user
2024-08-08 09:16:36.652 [info] [auth] Got Copilot token for user
2024-08-08 09:16:36.752 [info] [auth] Got Copilot token for user
2024-08-08 09:16:36.761 [info] [chat] copilot token chat_enabled: true
2024-08-08 09:16:36.761 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-08-08 09:16:36.862 [info] [auth] Got Copilot token for user
2024-08-08 09:16:36.897 [info] [auth] Got Copilot token for user
2024-08-08 09:16:36.908 [info] [auth] Got Copilot token for user
2024-08-08 09:16:37.176 [info] [RemoteAgents] Failed to load remote slash commands, DV: unable to get issuer certificate
    at gde (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:29514)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at J7e (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:31536)
    at pI.fetch (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:647:2373)
    at OS._doRefreshRemoteAgents (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:636:4538)
2024-08-08 09:16:37.411 [info] [ModelMetadataFetcher] Failed to fetch models (1659c9ee-8bc1-4b5c-9863-b851092a5842), DV: unable to get issuer certificate
    at gde (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:29514)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at J7e (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:31536)
    at pI.fetch (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:647:2373)
    at Vm._fetchModels (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1356:14828)
2024-08-08 09:16:37.412 [info] [contributions] activationBlocker from 'languageModelAccess' took for 2102ms
2024-08-08 09:18:41.519 [info] [ModelMetadataFetcher] Failed to fetch models (780ec510-9054-4282-b833-2f0136b92394), DV: unable to get issuer certificate
    at gde (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:29514)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at J7e (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:21:31536)
    at pI.fetch (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:647:2373)
    at Vm._fetchModels (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1356:14828)
    at Vm.getChatModel (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1356:13860)
    at IT.getChatEndpoint (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1356:17758)
    at ta.invoke (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:321:3302)
    at yT._provideResponseWithProgress (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1281:1451)
    at yT.handleRequest (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1279:2011)
    at t.y (/Users/user/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1290:1839)
    at s.$invokeAgent (/private/var/folders/qd/_xw26yk562vf0368jf3rxvx40000gn/T/AppTranslocation/7054C01E-11E6-4387-BA23-8C9F659A83BB/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:51474)

Steps to Reproduce:

1. Just using Copilot Chat or chat in Editor
2.Error: unable to get issuer certificate

What I did until now:
- Reinstall VS Code
- Reinstall Copilot
- Sing out, refresh, sign in
- remove check from Http: Proxy Strict SSL
security verify-cert https://api.github.com
...certificate verification successful.
---
No extended validation result found
Certificate Transparency (CT) status: verified

**Comment by charlesvardeman** [comment]
I have the same error. 
Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z (22 hrs ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

2024-08-08 14:50:36.528 [info] [FetcherService] Using the Helix fetcher.
2024-08-08 14:50:36.528 [info] [gitExtensionService] Initializing Git extension service.
2024-08-08 14:50:36.528 [info] [RemoteAgents] Unable to fetch remote agents because user is not signed in.
2024-08-08 14:50:36.528 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-08-08 14:50:36.528 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-08-08 14:50:36.528 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-08-08 14:50:36.668 [info] [CopilotTokenManager] Logged in as charlesvardeman
2024-08-08 14:50:37.230 [info] [CopilotTokenManager] Got Copilot token for charlesvardeman
2024-08-08 14:50:37.352 [info] [chat] copilot token chat_enabled: true
2024-08-08 14:50:37.352 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-08-08 14:50:37.495 [info] [ModelMetadataFetcher] Failed to fetch models (df8f9600-a1f5-4ca7-8853-223c6d7cd81d), AV: unable to get issuer certificate
    at bde (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:21:29516)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at eUe (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:21:31538)
    at uI.fetch (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:653:2373)
    at jm._fetchModels (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:1362:14563)
2024-08-08 14:50:37.495 [info] [contributions] activationBlocker from 'languageModelAccess' took for 1460ms
2024-08-08 14:50:37.598 [info] [RemoteAgents] Failed to load remote slash commands, AV: unable to get issuer certificate
    at bde (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:21:29516)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at eUe (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:21:31538)
    at uI.fetch (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:653:2373)
    at DS._doRefreshRemoteAgents (/Users/cvardema/.vscode/extensions/github.copilot-chat-0.19.2024073102/dist/extension.js:642:4508)

**Comment by charlottemcclintock** [comment]
I also have the same error: "unable to get issuer certificate" in chat window after rebooting, reinstalling, signing in/out, and testing alternate versions of VS code. 

Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z (1 day ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

logs: 
2024-08-09 07:43:40.807 [info] [fetcher] Using Helix fetcher.
2024-08-09 07:43:40.807 [info] [code-referencing] Public code references are enabled.
2024-08-09 07:43:40.819 [info] [auth] Sucessfully authenticated
2024-08-09 07:44:28.583 [info] [fetcher] Using Helix fetcher.
2024-08-09 07:44:28.583 [info] [code-referencing] Public code references are enabled.
2024-08-09 07:44:28.595 [info] [auth] Sucessfully authenticated

**Comment by stevesims** [comment]
I also have the same error

I have managed to find a temporary work-around, which was to revert the GitHub Copilot Chat plugin to use version 0.17.1. 

Updating from there to either 0.18.0 or 0.18.1 will have Copilot Chat fail again with "unable to get issuer certificate" errors

**Comment by ruddyscent** [comment]
I've been having the same issue for two days. Here are the results of the diagnosis

## Copilot

- Version: 1.221.0
- Build: prod
- Editor: vscode/1.92.1

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: enabled
- Chat: enabled

## Node setup

- Number of root certificates: 147
- Operating system: Darwin
- Operating system version: 23.6.0
- Operating system architecture: arm64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: unable to get issuer certificate
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: false
- Is `mac-ca` installed?: true

**Comment by charlesvardeman** [comment]
I just fixed the error by following the instructions in another thread. It's related to an expired cert in the MacOS KeyChain.
https://github.com/microsoft/vscode-copilot-release/issues/1439#issuecomment-2276428134

**Comment by andreamah** [comment]
/duplicate https://github.com/microsoft/vscode-copilot-release/issues/1439#issuecomment-2276428134

**Comment by SHoar** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1460#issuecomment-2284014828 This worked for me.
