### ISSUE TITLE
cant authenticate - last working version 0.17.1

### ISSUE THREAD

**Issue by AmosG** [microsoft/vscode-copilot-release#1480]
- Copilot Chat Extension Version: 0.18+
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
- Logs:
024-08-17 14:26:42.365 [info] [ContextKeysContribution] You are not signed in to GitHub. Please sign in to use Copilot.
2024-08-17 14:26:42.421 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-08-17 14:26:42.421 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-08-17 14:26:42.421 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-08-17 14:26:58.334 [info] [auth] GitHub login failed
2024-08-17 14:26:58.341 [info] [auth] GitHub login failed

sometimes getting:
2024-08-17 14:28:23.972 [info] [auth] GitHub login failed
2024-08-17 14:28:23.972 [info] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-08-17 14:28:23.972 [info] [LanguageModelAccess] Error: GitHubLoginFailed
    at RS.authShowWarnings (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:633:13828)
    at RS.getCopilotToken (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:633:11894)
    at Q_.getCopilotToken (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:144:2645)
    at PS._getAuthSession (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:634:2188)
    at /Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:634:1777
    at PS._registerEmbeddings (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:634:1747)
    at async Promise.all (index 1)
    at async Promise.allSettled (index 0)
    at Zct (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1365:4403)
    at Xct (/Users/amosg/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:1365:3372)
    at m.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6409)
    at m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6372)
    at m.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:5829)
Steps to Reproduce:

1. install 
2. try to login (in any way - profile, chat, copilot logo on bottom)

**Comment by tslominski** [comment]
same problem on Linux Mint, downgrading extension to v0.17.1 make authentication work again

**Comment by TylerLeonhardt** [comment]
Can you please try these steps?
https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021
