### ISSUE TITLE
Copilot chat response gets cut after one and a half line

### ISSUE THREAD

**Issue by AM99939** [microsoft/vscode-copilot-release#1491]
![image](https://github.com/user-attachments/assets/bc41c9ba-62ba-40c2-b550-accf3f43fb92)

- Copilot Chat Extension Version: 0.16.1
- VS Code Version: 1.90.0
- OS Version: Details below
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎14/‎07/‎2021
OS build	19045.4780
Experience	Windows Feature Experience Pack 1000.19060.1000.0

- Logs:
2024-08-21 17:52:26.163 [error] [default] Error sending telemetry FetchError: unable to get local issuer certificate
    at fetch (c:\Users\AM99939\.vscode\extensions\github.copilot-1.223.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (c:\Users\AM99939\.vscode\extensions\github.copilot-1.223.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:288:16)
    at MO.fetch (c:\Users\AM99939\.vscode\extensions\github.copilot-1.223.0\lib\src\network\helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  errno: undefined,
  erroredSysCall: undefined

Steps to Reproduce:

1. Ask any question in Copilot chat. See image above

**Comment by lramos15** [comment]
Your copilot chat extension version is quite old. Please update your VS Code and copilot chat. You should be using VS Code 1.92.2 and Copilot Chat 0.18.2

**Comment by AM99939** [comment]
I am going to get my VSCode and Copilot versions updated. Thank you for your help.
