### ISSUE TITLE
Copilot cannot use after 30 minutes

### ISSUE THREAD

**Issue by mjkokid** [microsoft/vscode-copilot-release#1547]
Issue happen every 30 mins using and have to restart extension copilot again :

2024-09-10 **15:06:56.257** [info] [auth] Got Copilot token for mjkokid
2024-09-10 15:06:56.266 [info] [chat] copilot token chat_enabled: true
2024-09-10 15:06:56.266 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-09-10 15:06:59.008 [info] [contributions] activationBlocker from 'languageModelAccess' took for 8596ms
2024-09-10 15:07:25.978 [info] [chat fetch] request.response: [https://api.business.githubcopilot.com/chat/completions], took 2040 ms
2024-09-10 15:07:26.002 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-09-10 15:07:26.003 [info] [streamChoices] request done: requestId: [5d78769c-10ad-4121-beee-1108c7357a53] model deployment ID: []
2024-09-10 15:07:28.060 [info] [chat fetch] request.response: [https://api.business.githubcopilot.com/chat/completions], took 2051 ms
2024-09-10 15:07:28.062 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-09-10 15:07:28.063 [info] [streamChoices] request done: requestId: [531d51a2-39f3-4ede-9a42-7f5ebd978ea1] model deployment ID: []
2024-09-10 15:31:56.332 [info] [auth] Logged in as mjkokid
2024-09-10 15:36:59.159 [info] [auth] Logged in as mjkokid
2024-09-10 **15:37:00.215** [info] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-10 15:37:00.215 [info] [LanguageModelAccess] SyntaxError: Unexpected token '<', "
<h"... is not valid JSON
at JSON.parse ()
at t.json (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:13:17068)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at kS.authFromGitHubToken (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:633:3978)
at kS.auth (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:633:13173)
at kS.authShowWarnings (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:633:13330)
at kS.getCopilotToken (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:633:12143)
at Q_.getCopilotToken (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:144:2645)
at AS._getAuthSession (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:634:2188)
at Timeout.r [as _onTimeout] (c:\Users\apo1hc.vscode\extensions\github.copilot-chat-0.18.2\dist\extension.js:634:627)

**Comment by mjkokid** [comment]
No update?

**Comment by chrmarti** [comment]
Please update to VS Code 1.93.1 and GitHub Copilot Chat 0.20.1 to get the latest fixes.
