### ISSUE TITLE
Failed to fetch model in wsl2

### ISSUE THREAD

**Issue by kkkkea** [microsoft/vscode-copilot-release#1561]
- Copilot Chat Extension Version: v0.20.0
- VS Code Version: 1.93
- OS Version: WSL2.2.4.0 ubuntu
- Logs:
2024-09-12 16:06:04.268 [info] Fetched model metadata in 1103ms c2bb7a21-790f-481a-ab3e-ae9fe06feb4f
2024-09-12 16:06:04.269 [error] Error: Failed to fetch models (c2bb7a21-790f-481a-ab3e-ae9fe06feb4f): access denied

    at Ah._fetchModels (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:21961)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ah.getEmbeddingsModel (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:20937)
    at pR.getEmbeddingsEndpoint (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:25516)
    at Hf.getRemoteContainer (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:16378)
    at Hf.getRemoteCacheLatestUpdateURL (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:16744)
    at Hf.fetchRemoteCacheLatest (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:17477)
    at Hf.getCache (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:17878)
    at Hf.getCache (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:19653)
    at uk._calculateEmbeddings (/home/kkkkea/.vscode-server/extensions/github.copilot-chat-0.20.0/dist/extension.js:141:22019): Failed to fetch models (c2bb7a21-790f-481a-ab3e-ae9fe06feb4f)

Steps to Reproduce:

1.It works fine on windows, but the above problems can occur on wsl

**Comment by kkkkea** [comment]
![image](https://github.com/user-attachments/assets/e30a9d7e-b571-4eae-ac18-12c0ee9b6d72)
