### ISSUE TITLE
Unexpected token 'o', "[object Rea"... is not valid JSON

### ISSUE THREAD

**Issue by Lioncky** [microsoft/vscode-copilot-release#1621]
Vsocde v1.93.1 and copilot both latest-update.
Last week it works well, today it shows error. 
Reinstall the copilot 'login to github' blue button no use.
```
2024-09-23 17:56:30.676 [info] Using the Electron fetcher.
2024-09-23 17:56:30.676 [info] Initializing Git extension service.
2024-09-23 17:56:30.891 [warning] Unable to fetch remote agents because user is not signed in.
2024-09-23 17:56:30.970 [info] Registering default platform agent...
2024-09-23 17:56:30.974 [info] Logged in as Lioncky
2024-09-23 17:56:31.016 [info] Successfully activated the vscode.git extension.
2024-09-23 17:56:31.016 [info] Enablement state of the vscode.git extension: true.
2024-09-23 17:56:31.016 [info] Successfully registered Git commit message provider.
2024-09-23 17:56:32.543 [warning] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)
2024-09-23 17:56:33.314 [info] Got Copilot token for Lioncky
2024-09-23 17:56:33.339 [info] copilot token chat_enabled: true, sku: trial_30_monthly_subscriber
2024-09-23 17:56:33.339 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-09-23 17:56:33.932 [info] Fetched model metadata in 611ms b1102252-7ddd-47fe-9a58-bd7f7e3cfc37
2024-09-23 17:56:33.940 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ah._fetchModels (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1507:22143): Failed to fetch models (b1102252-7ddd-47fe-9a58-bd7f7e3cfc37)
2024-09-23 17:56:33.940 [info] activationBlocker from 'languageModelAccess' took for 3049ms
2024-09-23 17:56:40.484 [info] Fetched model metadata in 537ms 92e9c301-b5bf-4451-b66e-69867ee930f1
2024-09-23 17:56:40.485 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ah._fetchModels (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1507:22143): Failed to fetch models (92e9c301-b5bf-4451-b66e-69867ee930f1)
2024-09-23 17:56:40.486 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ah._fetchModels (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1507:22143)

```
![image](https://github.com/user-attachments/assets/10e3ed86-b322-4216-8965-19e9b4c99bf9)

**Comment by Lioncky** [comment]
Tried re-login the bug appear.
```
2024-09-23 18:25:18.709 [info] Using the Electron fetcher.
2024-09-23 18:25:18.709 [info] Initializing Git extension service.
2024-09-23 18:25:19.081 [warning] Unable to fetch remote agents because user is not signed in.
2024-09-23 18:25:19.081 [warning] GitHub login failed
2024-09-23 18:25:19.082 [info] copilot token chat_enabled: undefined, sku: 
2024-09-23 18:25:19.235 [warning] GitHub login failed
2024-09-23 18:25:19.236 [error] Error: GitHubLoginFailed
	at rC._authShowWarnings (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:4200)
	at async rC.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:2644)
	at async nT.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:12074)
	at async h$.waitForChatEnabled (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:736:3227)
	at async h$.run (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:736:2952)
	at async Mfe (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:736:2636): Failed to get copilot token
2024-09-23 18:25:19.237 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-23 18:25:19.237 [error] Error: GitHubLoginFailed
	at rC._authShowWarnings (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:4200)
	at async rC.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:2644)
	at async nT.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:12074)
	at async iC._getAuthSession (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:2324)
	at async r (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:631)
	at async iC._registerLanguageModels (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:1638)
	at async Promise.all (index 0)
	at async Promise.allSettled (index 0)
	at async hmt (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1535:4033)
	at async fmt (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1535:3164)
	at async m.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6409)
	at async m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6372)
	at async m.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5829)
2024-09-23 18:25:19.237 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-23 18:25:19.237 [error] Error: GitHubLoginFailed
	at rC._authShowWarnings (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:4200)
	at async rC.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:2644)
	at async nT.getCopilotToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:12074)
	at async iC._getAuthSession (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:2324)
	at async c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:1902
	at async iC._registerEmbeddings (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:739:1872)
	at async Promise.all (index 1)
	at async Promise.allSettled (index 0)
	at async hmt (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1535:4033)
	at async fmt (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1535:3164)
	at async m.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6409)
	at async m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6372)
	at async m.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5829)
2024-09-23 18:25:19.237 [error] You are not signed in to GitHub. Please sign in to use Copilot.
2024-09-23 18:25:19.237 [error] You are not signed in to GitHub. Please sign in to use Copilot.
2024-09-23 18:25:19.237 [info] activationBlocker from 'languageModelAccess' took for 157ms
2024-09-23 18:25:19.604 [info] Successfully activated the vscode.git extension.
2024-09-23 18:25:19.604 [info] Enablement state of the vscode.git extension: true.
2024-09-23 18:25:19.604 [info] Successfully registered Git commit message provider.
2024-09-23 18:25:54.923 [info] Registering default platform agent...
2024-09-23 18:25:54.936 [info] Logged in as Lioncky
2024-09-23 18:25:55.584 [info] copilot token chat_enabled: undefined, sku: 
2024-09-23 18:25:55.595 [info] Logged in as Lioncky
2024-09-23 18:25:55.960 [warning] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)
2024-09-23 18:25:56.079 [error] GitHub Copilot could not connect to server. Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"
2024-09-23 18:25:56.079 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-23 18:25:56.079 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at rC.authFromGitHubToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:7745)
    at rC._auth (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:3229)
```

**Comment by TylerLeonhardt** [comment]
This appears to have something to do with RemoteAgents. Passing to @joyceerhl

**Comment by joyceerhl** [comment]
This also has to do with fetching models

```
2024-09-23 17:56:40.485 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Ah._fetchModels (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:1507:22143): Failed to fetch models (92e9c301-b5bf-4451-b66e-69867ee930f1)
```

**Comment by lramos15** [comment]
Something is weird about the auth here @TylerLeonhardt that's why the fetching is failing

```
2024-09-23 18:25:19.081 [warning] GitHub login failed
2024-09-23 18:25:19.082 [info] copilot token chat_enabled: undefined, sku: 
```

**Comment by Lioncky** [comment]
···```
```

**Comment by a1burning** [comment]
我也遇到了这个问题。版本一样。

**Comment by Lioncky** [comment]
@TylerLeonhardt No, the problem still exist, here is the log :
```
2024-09-28 19:43:13.504 [info] Using the Electron fetcher.
2024-09-28 19:43:13.504 [info] Initializing Git extension service.
2024-09-28 19:43:13.700 [warning] Unable to fetch remote agents because user is not signed in.
2024-09-28 19:43:13.775 [info] Registering default platform agent...
2024-09-28 19:43:13.783 [info] Logged in as Lioncky
2024-09-28 19:43:13.872 [info] Successfully activated the vscode.git extension.
2024-09-28 19:43:13.872 [info] Enablement state of the vscode.git extension: true.
2024-09-28 19:43:13.872 [info] Successfully registered Git commit message provider.
2024-09-28 19:43:15.572 [warning] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)
2024-09-28 19:43:15.632 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at rC.authFromGitHubToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:7745)
    at rC._auth (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:3229): Failed to get copilot token
2024-09-28 19:43:15.632 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-28 19:43:15.632 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at rC.authFromGitHubToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:7745)
    at rC._auth (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:3229)
2024-09-28 19:43:15.632 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-28 19:43:15.632 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DYC\.vscode\extensions\cnblogs.vscode-cnb-1.8.55-win32-x64\dist\extension.js:203:42608)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at rC.authFromGitHubToken (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:141:7745)
    at rC._auth (c:\Users\DYC\.vscode\extensions\github.copilot-chat-0.20.3\dist\extension.js:738:3229)
2024-09-28 19:43:15.632 [error] GitHub Copilot could not connect to server. Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"
2024-09-28 19:43:15.632 [info] activationBlocker from 'languageModelAccess' took for 1934ms

```

Another:
```
## GitHub Copilot Chat

- Extension Version: 0.20.3 (prod)
- VS Code: vscode/1.93.1
- OS: Windows

## Network

User Settings:
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }


Connecting to https://api.github.com:
- DNS Lookup: 20.205.243.168
- Electron Fetcher (configured): HTTP 200
- Node Fetcher: HTTP 200
- Helix Fetcher: HTTP 200

Connecting to https://api.githubcopilot.com/_ping:
- DNS Lookup: 140.82.113.22
- Electron Fetcher (configured): HTTP 200
- Node Fetcher: HTTP 200
- Helix Fetcher: HTTP 200

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
```
VS2022 works well, not sure why vscode error. I remeber last week is fine.

**Comment by Lioncky** [comment]
After I uninstall another plugin called `cnblogs` it works fine now. Thank you!

**Comment by shuangmuaigwu** [comment]
Again I uninstalled another plugin and he works fine!

**Comment by wangyinyuan** [comment]
Mostly to be plug-in conflicts. I didn't install `cnblogs` but I installed `Aide` which caused this auth issue, [see this](Mostly plug-in conflicts). After uninstalled aide everything works just fine.
