### ISSUE TITLE
undefined is not iterable in implicit '@workspace /tests' query

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-copilot-release#1631]
Type: <b>Bug</b>

```
2024-09-24 09:15:23.352 [info] message 0 returned. finish reason: [stop]
2024-09-24 09:15:23.353 [info] request done: requestId: [8b882ef9-f9a0-4ba5-8f80-a220b0482cb8] model deployment ID: []
2024-09-24 09:15:23.366 [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at zE.resolveDocContextProgrammatically (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:921:1648)
    at zE.invoke (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:921:768)
    at nN.getResult (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:371:3671)
    at nN.getResult (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:922:406)
    at gC.getResult (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:371:13520)
    at sS.y (c:\Users\aaron\.vscode-insiders\extensions\github.copilot-chat-0.21.2024092402\dist\extension.js:1584:1600)
    at Mg.$invokeAgent (file:///c:/Users/aaron/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:42557)
2024-09-24 09:15:23.387 [info] [🤫] ccreq:383ee785.copilotmd | success | gpt-4o-mini | 1002ms | [intentDetection]
```

Extension version: 0.21.2024092402
VS Code version: Code - Insiders 1.94.0-insider (f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e, 2024-09-24T05:04:12.797Z)
OS version: Windows_NT arm64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon(R) X 12-core X1E80100 @ 3.40 GHz (12 x 2976)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.57GB (11.18GB free)|
|Process Argv|--crash-reporter-id 8dc59ac4-06a1-44f4-bf7a-b9a7c128e443|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31144450
e80f6927:31120813
fje88620:31121564
i21gd607:31141543
iacca1:31138162
notype1:31143044
b50ed353:31138333
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by amunger** [comment]
![image](https://github.com/user-attachments/assets/45f634f0-0a62-4ee3-a5f1-68f1d7cd0fd9)
