### ISSUE TITLE
Unexpected token 'o', "[object Rea"... is not valid JSON

### ISSUE THREAD

**Issue by liliyigz** [microsoft/vscode-copilot-release#1678]
# Log
GitHub Copilot Chat

- Extension Version: 0.20.3 (prod)
- VS Code: vscode/1.93.1
- OS: Windows

Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

Connecting to https://api.github.com:
- DNS Lookup: 20.205.243.168
- Electron Fetcher (configured): HTTP 200
- Node Fetcher: HTTP 200
- Helix Fetcher: HTTP 200

Connecting to https://api.githubcopilot.com/_ping:
- DNS Lookup: 140.82.113.22
- Electron Fetcher (configured): HTTP 200
- Node Fetcher: HTTP 200
- Helix Fetcher: HTTP 200

Documentation:

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

# Error message

## Unexpected token 'o', "[object Rea"... is not valid JSON

![Screenshot 2024-10-01 114306](https://github.com/user-attachments/assets/de8eb95b-2450-45b7-90fa-031aa45a7729)

**Comment by liliyigz** [comment]
I've tried sign out and sign back in; remove and re-install extensions; switch copilot to previous versions; switch copilot to pre-released versitions.

**Comment by chrmarti** [comment]
Could be https://github.com/cnblogs/vscode-cnb/issues/303.

**Comment by liliyigz** [comment]
> Could be [cnblogs/vscode-cnb#303](https://github.com/cnblogs/vscode-cnb/issues/303).

I don't have the cnblogs extension

**Comment by liliyigz** [comment]
> Hi can you include your copilot chat output logs. It's `CMD / CTRL + SHIFT + U `-> `GitHub Copilot Chat`

2024-10-05 22:52:09.062 [info] Using the Electron fetcher.
2024-10-05 22:52:09.062 [info] Initializing Git extension service.
2024-10-05 22:52:09.062 [info] Successfully activated the vscode.git extension.
2024-10-05 22:52:09.062 [info] Enablement state of the vscode.git extension: true.
2024-10-05 22:52:09.063 [info] Successfully registered Git commit message provider.
2024-10-05 22:52:09.072 [info] Logged in as liliyigz
2024-10-05 22:52:09.728 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720): Failed to get copilot token
2024-10-05 22:52:09.732 [error] GitHub Copilot could not connect to server. Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"
2024-10-05 22:52:09.732 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-10-05 22:52:09.732 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720)
2024-10-05 22:52:09.733 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-10-05 22:52:09.733 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720)
2024-10-05 22:52:09.747 [info] Logged in as liliyigz
2024-10-05 22:52:10.067 [info] activationBlocker from 'languageModelAccess' took for 980ms
2024-10-05 22:52:31.334 [info] Using the Electron fetcher.
2024-10-05 22:52:31.334 [info] Initializing Git extension service.
2024-10-05 22:52:31.334 [info] Successfully activated the vscode.git extension.
2024-10-05 22:52:31.334 [info] Enablement state of the vscode.git extension: true.
2024-10-05 22:52:31.334 [info] Successfully registered Git commit message provider.
2024-10-05 22:52:31.380 [info] Logged in as liliyigz
2024-10-05 22:52:31.964 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720): Failed to get copilot token
2024-10-05 22:52:31.964 [error] GitHub Copilot could not connect to server. Extension activation failed: "Unexpected token 'o', "[object Rea"... is not valid JSON"
2024-10-05 22:52:31.964 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-10-05 22:52:31.965 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720)
2024-10-05 22:52:31.965 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-10-05 22:52:31.965 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\DELL\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AC.authFromGitHubToken (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:299:7809)
    at AC._auth (c:\Users\DELL\.vscode\extensions\github.copilot-chat-0.22.2024100401\dist\extension.js:627:2720)
2024-10-05 22:52:32.021 [info] Logged in as liliyigz
2024-10-05 22:52:32.352 [info] activationBlocker from 'languageModelAccess' took for 1123ms

**Comment by lramos15** [comment]
Please try uninstalling this extension 

`nicepkg.aide-pro-1.19.0`

**Comment by liliyigz** [comment]
> Please try uninstalling this extension
> 
> `nicepkg.aide-pro-1.19.0`

It worked!!!!

Thank you all for helping!
