### ISSUE TITLE
[error] [default] Error sending telemetry FetchError: unable to verify the first certificate

### ISSUE THREAD

**Issue by cidxb** [microsoft/vscode-copilot-release#1766]
Problem: Github copilot chat works properly, but the line completion is reporting error and not working.
Network Env: Corporate LAN with VPN, but coworkers copilot work just fine under same network.
**_OUTPUT MESSAGE_**

`2024-10-08 12:58:39.422 [info] [certificates] Removed 1 expired certificates
2024-10-08 12:58:40.147 [info] [fetcher] Using Helix fetcher.
2024-10-08 12:58:40.147 [info] [code-referencing] Public code references are enabled.
2024-10-08 12:58:40.154 [info] [auth] Successfully authenticated
2024-10-08 12:58:41.615 [error] [default] Error sending telemetry FetchError: unable to verify the first certificate
    at fetch (/home/xx/.vscode/extensions/github.copilot-1.236.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/xx/.vscode/extensions/github.copilot-1.236.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at rae.fetch (/home/xx/.vscode/extensions/github.copilot-1.236.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  errno: undefined,
  erroredSysCall: undefined`

_**Test RESULT :   Developer: Github Copilot Chat diagnose**_
## GitHub Copilot Chat

- Extension Version: 0.21.0 (prod)
- VS Code: vscode/1.94.0
- OS: Linux

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 20.205.243.168 (0 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.github.com
- Electron Fetcher (configured): HTTP 200 (86 ms)
- Node Fetcher: HTTP 200 (577 ms)
- Helix Fetcher: HTTP 200 (602 ms)

Connecting to https://api.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.113.21 (1 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.githubcopilot.com
- Electron Fetcher (configured): HTTP 200 (240 ms)
- Node Fetcher: Error: unable to verify the first certificate
- Helix Fetcher: Error: unable to verify the first certificate

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

_**TRIED SOLUTION **_
Reintall vscoede/extensions
Reinstall CA-certifacates
Contacted to IT, but since there are no other similar report, the issue should be a local PC problem.

**Comment by lramos15** [comment]
This repository does not cover inline completions and instead just chat (I know it is a bit confusing, apologies for that). It is recommended you file an issue over at https://github.com/orgs/community/discussions/categories/copilot or contact GitHub support
