### ISSUE TITLE
Failed to fetch models

### ISSUE THREAD

**Issue by AleksandrKashirin** [microsoft/vscode-copilot-release#1771]
Type: <b>Bug</b>

Failed to fetch models (91e25ecf-5d13-4ac5-a77a-1142b6ab2f01): access denied

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.68GB free)|
|Process Argv|--crash-reporter-id fbe93b9f-3ec7-41cf-942f-393d95b6a8ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by lramos15** [comment]
Can you include your logs via `CTRL + SHIFT +U` -> `GitHub Copilot Chat`

**Comment by egorodet** [comment]
> Can you include your logs via `CTRL + SHIFT +U` -> `GitHub Copilot Chat`

Struggling with the same problem. Here is my log:

```js
2024-10-09 22:37:00.495 [info] Using the Electron fetcher.
2024-10-09 22:37:00.495 [info] Initializing Git extension service.
2024-10-09 22:37:00.495 [info] Successfully activated the vscode.git extension.
2024-10-09 22:37:00.495 [info] Enablement state of the vscode.git extension: true.
2024-10-09 22:37:00.495 [info] Successfully registered Git commit message provider.
2024-10-09 22:37:00.782 [info] Logged in as egorodet
2024-10-09 22:37:02.205 [info] Got Copilot token for egorodet
2024-10-09 22:37:02.241 [info] copilot token chat_enabled: true, sku: trial_30_monthly_subscriber
2024-10-09 22:37:02.255 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-10-09 22:37:02.258 [info] Registering default platform agent...
2024-10-09 22:37:03.167 [info] Fetched model metadata in 955ms 0725374b-2c93-4007-953d-42aae4a6f621
2024-10-09 22:37:03.168 [error] Error: Failed to fetch models (0725374b-2c93-4007-953d-42aae4a6f621): access denied

    at Tm._fetchModels (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5): Failed to fetch models (0725374b-2c93-4007-953d-42aae4a6f621)
2024-10-09 22:37:03.168 [info] activationBlocker from 'languageModelAccess' took for 2710ms
2024-10-09 22:37:03.341 [info] Fetched model metadata in 173ms 5efcb84a-bdcf-4496-97a2-397f47ee534a
2024-10-09 22:37:03.341 [error] Error: Failed to fetch models (5efcb84a-bdcf-4496-97a2-397f47ee534a): access denied

    at Tm._fetchModels (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at r (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:824)
    at AT._registerLanguageModels (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:1790)
    at async Promise.all (index 0): Failed to fetch models (5efcb84a-bdcf-4496-97a2-397f47ee534a)
2024-10-09 22:37:11.747 [info] Fetched model metadata in 190ms 8ca03787-a154-4fde-82a4-35718e77ecfc
2024-10-09 22:37:11.748 [error] Error: Failed to fetch models (8ca03787-a154-4fde-82a4-35718e77ecfc): access denied

    at Tm._fetchModels (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at vA.getChatEndpoint (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22895)
    at Qp.provideParticipantDetection (c:\Users\egorodet\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:511:1698): Failed to fetch models (8ca03787-a154-4fde-82a4-35718e77ecfc)

```

**Comment by lramos15** [comment]
@egorodet Are you getting inline suggestions via the ghost text while typing in the editor? Trying to understand if this is only affecting chat.

**Comment by egorodet** [comment]
> @egorodet Are you getting inline suggestions via the ghost text while typing in the editor? Trying to understand if this is only affecting chat.

No, inline code completion also does not work with Copilot.

**Comment by lramos15** [comment]
@egorodet What country are you accessing copilot from?

**Comment by egorodet** [comment]
> [@egorodet](https://github.com/egorodet) What country are you accessing copilot from?

Using VPN server in Finland.

**Comment by lramos15** [comment]
@egorodet The error is not helpful I agree, but I did some investigating and it appears our systems have detected you may be trying to circumvent trade restrictions surrounding the Copilot product. Feel free to read more about trade restricted countries [here](https://docs.github.com/en/site-policy/other-site-policies/github-and-trade-controls#github-copilot).

**Comment by lramos15** [comment]
@AleksandrKashirin The same applies with your account so I will be closing this for now.
