### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by Zhongwei1986** [microsoft/vscode-copilot-release#1772]
Type: <b>Bug</b>

Failed to fetch models (5fa45ad4-9c1c-43b1-8557-49b225599481): access denied

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.19GB (33.19GB free)|
|Process Argv|--folder-uri file:///f%3A/C/RH850_U2B_FBL --crash-reporter-id e4105555-c6ae-421c-86c1-16b4706b5dcd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by Zhongwei1986** [comment]
2024-10-09 00:26:12.645 [info] Using the Electron fetcher.
2024-10-09 00:26:12.645 [info] Initializing Git extension service.
2024-10-09 00:26:12.645 [info] Successfully activated the vscode.git extension.
2024-10-09 00:26:12.645 [info] Enablement state of the vscode.git extension: true.
2024-10-09 00:26:12.645 [info] Successfully registered Git commit message provider.
2024-10-09 00:26:13.081 [info] Logged in as Zhongwei1986
2024-10-09 00:26:14.887 [info] Got Copilot token for Zhongwei1986
2024-10-09 00:26:14.918 [info] copilot token chat_enabled: true, sku: yearly_subscriber
2024-10-09 00:26:14.921 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-10-09 00:26:14.934 [info] Registering default platform agent...
2024-10-09 00:26:15.627 [info] Fetched model metadata in 733ms 68aa967b-f4d3-4fe8-bc67-0162da9f3117
2024-10-09 00:26:15.627 [error] Error: Failed to fetch models (68aa967b-f4d3-4fe8-bc67-0162da9f3117): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5): Failed to fetch models (68aa967b-f4d3-4fe8-bc67-0162da9f3117)
2024-10-09 00:26:15.628 [info] activationBlocker from 'languageModelAccess' took for 3090ms
2024-10-09 00:26:16.713 [info] Fetched model metadata in 1086ms 56df7178-0e69-4315-adb0-bc59a5af9d69
2024-10-09 00:26:16.714 [error] Error: Failed to fetch models (56df7178-0e69-4315-adb0-bc59a5af9d69): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at r (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:824)
    at AT._registerLanguageModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:1790)
    at async Promise.all (index 0): Failed to fetch models (56df7178-0e69-4315-adb0-bc59a5af9d69)
2024-10-09 00:26:27.817 [info] Logged in as Zhongwei1986
2024-10-09 00:26:29.220 [info] Got Copilot token for Zhongwei1986
2024-10-09 00:26:29.225 [info] copilot token chat_enabled: true, sku: yearly_subscriber
2024-10-09 00:26:29.495 [info] Fetched model metadata in 267ms 7183cdc4-49dd-4f0b-bf86-5d30a6752333
2024-10-09 00:26:29.495 [error] Error: Failed to fetch models (7183cdc4-49dd-4f0b-bf86-5d30a6752333): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getEmbeddingsModel (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:18570)
    at vA.getEmbeddingsEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:23375)
    at r (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:2120): Failed to fetch models (7183cdc4-49dd-4f0b-bf86-5d30a6752333)
2024-10-09 00:26:37.413 [info] Fetched model metadata in 278ms 34d8854f-4a6d-4697-adee-7d16521e800c
2024-10-09 00:26:37.414 [error] Error: Failed to fetch models (34d8854f-4a6d-4697-adee-7d16521e800c): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22895)
    at Qp.provideParticipantDetection (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:511:1698): Failed to fetch models (34d8854f-4a6d-4697-adee-7d16521e800c)
2024-10-09 00:27:02.472 [info] Fetched model metadata in 307ms 2adbbd72-f91d-4b8f-bf9c-221fac69fb0c
2024-10-09 00:27:02.472 [error] Error: Failed to fetch models (2adbbd72-f91d-4b8f-bf9c-221fac69fb0c): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22895)
    at Qp.provideParticipantDetection (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:511:1698): Failed to fetch models (2adbbd72-f91d-4b8f-bf9c-221fac69fb0c)
2024-10-09 00:29:35.785 [warning] Unable to fetch remote agents because user is not signed in.
2024-10-09 00:29:35.789 [warning] GitHub login failed
2024-10-09 00:29:35.812 [warning] GitHub login failed
2024-10-09 00:29:35.815 [info] copilot token chat_enabled: undefined, sku: 
2024-10-09 00:29:35.839 [warning] GitHub login failed
2024-10-09 00:29:35.841 [error] You are not signed in to GitHub. Please sign in to use Copilot.
2024-10-09 00:29:35.841 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-10-09 00:29:35.841 [error] Error: GitHubLoginFailed
    at TT._authShowWarnings (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:656:3691)
    at TT.getCopilotToken (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:656:2135)
    at Xw.getCopilotToken (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:299:12138)
    at AT._getAuthSession (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:2570)
    at r (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:2040)
2024-10-09 00:29:47.562 [info] Logged in as Zhongwei1986
2024-10-09 00:29:48.969 [info] Got Copilot token for Zhongwei1986
2024-10-09 00:29:49.002 [info] copilot token chat_enabled: true, sku: yearly_subscriber
2024-10-09 00:29:49.002 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-10-09 00:29:49.954 [info] Fetched model metadata in 927ms e74a6262-3852-4ead-901a-ce5b9f598c1c
2024-10-09 00:29:49.955 [error] Error: Failed to fetch models (e74a6262-3852-4ead-901a-ce5b9f598c1c): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getEmbeddingsModel (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:18570)
    at vA.getEmbeddingsEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:23375)
    at r (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:657:2120): Failed to fetch models (e74a6262-3852-4ead-901a-ce5b9f598c1c)
2024-10-09 00:29:53.390 [info] Fetched model metadata in 315ms 5fa45ad4-9c1c-43b1-8557-49b225599481
2024-10-09 00:29:53.391 [error] Error: Failed to fetch models (5fa45ad4-9c1c-43b1-8557-49b225599481): access denied

    at Tm._fetchModels (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:19564)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Tm.getChatModelFromFamily (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:17654)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22532)
    at vA.getChatEndpoint (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:1726:22895)
    at Qp.provideParticipantDetection (c:\Users\Wayne\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:511:1698): Failed to fetch models (5fa45ad4-9c1c-43b1-8557-49b225599481)

**Comment by Zhongwei1986** [comment]
found the reason, it because the proxy using, close this issue
