### ISSUE TITLE
Stuck inline chat widget

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#211]
- Open chat widget, type a query, press enter
- Try to accept the result by pressing enter again
- Then immediately remember to press cmd+enter
- At that point the widget was open and wouldn't be dismissed with escape
- Switch tabs, switch back, have widget floating over editor text

<img width="829" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/323878/60182231-f5fa-4f88-a929-cf66ac54482d">

It handled this prompt perfectly though

**Comment by jrieken** [comment]
stacktrace

```
ERR Unexpected type: Error: Unexpected type
    at assertType (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/types.js:92:19)
    at InteractiveEditorController.APPLY_RESPONSE (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:385:36)
    at InteractiveEditorController._nextState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:132:48)
    at InteractiveEditorController._nextState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:134:28)
    at async InteractiveEditorController._nextState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:134:17)
    at async InteractiveEditorController._nextState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:134:17)
    at async InteractiveEditorController._nextState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:134:17)
    at async InteractiveEditorController.run (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.js:114:13)
```

**Comment by jrieken** [comment]
Steps are actually quite simple

* open inline chat
* make request
* while the request is pending, select `cmd+enter` to apply changes
* 💥
