### ISSUE TITLE
Language model unavailable

### ISSUE THREAD

**Issue by zhang002coder** [microsoft/vscode-copilot-release#2222]
github copilot chat is not available, here is the output log of github copilot chat:

2024-11-04 00:08:20.960 [info] activationBlocker from 'languageModelAccess' took for 4170ms
2024-11-04 00:08:21.028 [warning] Invalid remote agent response: [object ReadableStream] (SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON)
2024-11-04 00:08:21.379 [info] Fetched model metadata in 419ms 27baec35-28a3-4841-a035-55c0216811bd
2024-11-04 00:08:21.380 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\Administrator\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Wm._fetchModels (c:\Users\Administrator\.vscode\extensions\github.copilot-chat-0.22.1\dist\extension.js:1773:17431)
    at Wm.getChatModelFromFamily (c:\Users\Administrator\.vscode\extensions\github.copilot-chat-0.22.1\dist\extension.js:1773:15511)
    at a2.getChatEndpoint (c:\Users\Administrator\.vscode\extensions\github.copilot-chat-0.22.1\dist\extension.js:1773:20787)
    at t (c:\Users\Administrator\.vscode\extensions\github.copilot-chat-0.22.1\dist\extension.js:628:825)
    at pE._registerLanguageModels (c:\Users\Administrator\.vscode\extensions\github.copilot-chat-0.22.1\dist\extension.js:628:1810)
    at async Promise.all (index 0): Failed to fetch models (27baec35-28a3-4841-a035-55c0216811bd)

My github copilot can prompt normally, only copilot chat is not working

**Comment by zhang002coder** [comment]
![Image](https://github.com/user-attachments/assets/00b978fc-6fa5-4554-ae0c-e204aada835c)

**Comment by zhang002coder** [comment]
After restarting the IDE, the github copilot chat shows that you are logged in to github.com, but nothing happens when you click the button

![Image](https://github.com/user-attachments/assets/6be77410-5659-43cb-ad00-72d8fb454c93)

**Comment by SaifLau** [comment]
Same problem, same time.  Have you got it fixed yet?

**Comment by zhang002coder** [comment]
> Same problem, same time. Have you got it fixed yet?

When it is fixed, uninstall the nicepkg.aide-pro plug-in

**Comment by roblourens** [comment]
That extension seems to be breaking chat, I'll open an issue on them- thanks!
