### ISSUE TITLE
GitHub.copilot-chat-0.23.2024110702.vsix not compatible with VSCode 1.95.1

### ISSUE THREAD

**Issue by Aimp91** [microsoft/vscode-copilot-release#2381]
- Copilot Chat Extension Version: GitHub.copilot-chat-0.23.2024110702.vsix
- VS Code Version:  1.95.1
- OS Version: Ubuntu 24.04.1 LTS
- Logs:

Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.95.1'.
    at Lc.install (file:///usr/lib/code-server/lib/vscode/out/server-main.js:51:11834)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fc.h (file:///usr/lib/code-server/lib/vscode/out/server-main.js:64:951)
    at async file:///usr/lib/code-server/lib/vscode/out/server-main.js:63:35352
    at async Promise.all (index 0)
    at async Fc.installExtensions (file:///usr/lib/code-server/lib/vscode/out/server-main.js:63:35289)
    at async file:///usr/lib/code-server/lib/vscode/out/server-main.js:71:7835
    at async M9.run (file:///usr/lib/code-server/lib/vscode/out/server-main.js:71:7668)
    at async BO (file:///usr/lib/code-server/lib/vscode/out/server-main.js:71:7152)
Failed Installing Extensions: file:///coder/GitHub.copilot-chat-0.23.2024110702.vsix

Steps to Reproduce:

1. Trying to install GitHub Copilot Chat on VsCode

**Comment by aeschli** [comment]
How exactly did you try to install that extension? From the extensions view, from the terminal? Please give the exact steps.

**Comment by isidorn** [comment]
This should work much better with the latest VS Code Stable and GH Copilot. If you still see issues like this feel free to open a new one with reproducible steps. Thank you
