### ISSUE TITLE
always display "GitHub Copilot 正在生成..."

### ISSUE THREAD

**Issue by xiaolitongxue5** [microsoft/vscode-copilot-release#2646]
# always display "GitHub Copilot 正在生成..."/一直显示 "GitHub Copilot 正在生成..."

# GitHub Copilot Chat Diagnostics
## GitHub Copilot Chat

- Extension Version: 0.22.2 (prod)
- VS Code: vscode/1.95.3
- OS: Windows

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 20.205.243.168 (21 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.github.com
- Electron Fetcher (configured): HTTP 200 (524 ms)
- Node Fetcher: HTTP 200 (280 ms)
- Helix Fetcher: HTTP 200 (659 ms)

Connecting to https://api.individual.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.114.21 (4 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.individual.githubcopilot.com
- Electron Fetcher (configured): HTTP 200 (771 ms)
- Node Fetcher: HTTP 200 (733 ms)
- Helix Fetcher: HTTP 200 (734 ms)

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

# LOG
## GitHub Copilot
2024-11-17 09:58:39.319 [info] [certificates] Removed 86 expired certificates
2024-11-17 09:58:39.986 [info] [fetcher] Using Helix fetcher.
2024-11-17 09:58:39.987 [info] [code-referencing] Public code references are enabled.
2024-11-17 09:58:39.987 [info] [auth] Successfully authenticated
2024-11-17 10:08:48.902 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 433 ms
2024-11-17 10:08:48.905 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:08:48.907 [info] [streamChoices] request done: headerRequestId: [6241e9e7-369a-4447-8060-9318db4bcaf7] model deployment ID: [d031-20241014223512]
2024-11-17 10:08:55.518 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 220 ms
2024-11-17 10:08:55.519 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:08:55.519 [info] [streamChoices] request done: headerRequestId: [5d05ea4c-645d-4308-af5c-7edfec35d864] model deployment ID: [d031-20241014223512]
2024-11-17 10:08:55.910 [info] [code-referencing] Calling Match
2024-11-17 10:08:56.810 [info] [code-referencing] No match found
2024-11-17 10:08:59.486 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 196 ms
2024-11-17 10:08:59.487 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:08:59.487 [info] [streamChoices] request done: headerRequestId: [cff5961e-dff3-42e8-b768-9d8e4f7a70d4] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:02.231 [info] [code-referencing] Calling Match
2024-11-17 10:09:02.539 [info] [code-referencing] No match found
2024-11-17 10:09:05.250 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 410 ms
2024-11-17 10:09:05.251 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:05.252 [info] [streamChoices] request done: headerRequestId: [61bc372e-5a2b-4a28-9888-2220d6b94027] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:06.751 [info] [code-referencing] Calling Match
2024-11-17 10:09:07.055 [info] [code-referencing] No match found
2024-11-17 10:09:07.078 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 187 ms
2024-11-17 10:09:07.079 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:07.079 [info] [streamChoices] request done: headerRequestId: [d01f269f-a9ad-456d-8ccc-0367e1001843] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:07.450 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 201 ms
2024-11-17 10:09:07.451 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:07.451 [info] [streamChoices] request done: headerRequestId: [935ee554-dfd2-4aed-be10-15b9ec1fc9fc] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:08.236 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 163 ms
2024-11-17 10:09:08.237 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:08.237 [info] [streamChoices] request done: headerRequestId: [15a53232-4e6d-4f08-9928-abe7c956dd81] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:08.604 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 171 ms
2024-11-17 10:09:08.605 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:08.605 [info] [streamChoices] request done: headerRequestId: [1e484c76-8880-448c-95e9-61c7ceb91d12] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:09.182 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 217 ms
2024-11-17 10:09:09.190 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:09.190 [info] [streamChoices] request done: headerRequestId: [1b83af0b-6be4-48b9-bdf6-9a9969e1b3aa] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:17.397 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 253 ms
2024-11-17 10:09:17.399 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:17.402 [info] [streamChoices] request done: headerRequestId: [5810793a-b143-402e-a8b5-c0ef74ff8fbd] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:18.120 [info] [code-referencing] Calling Match
2024-11-17 10:09:18.426 [info] [code-referencing] No match found
2024-11-17 10:09:22.078 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 185 ms
2024-11-17 10:09:22.079 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:22.080 [info] [streamChoices] request done: headerRequestId: [abfa0aa6-2d58-41a9-9a32-5fc043eac0da] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:24.450 [info] [fetchCompletions] request.response: [https://proxy.individual.githubcopilot.com/v1/engines/copilot-codex/completions] took 224 ms
2024-11-17 10:09:24.451 [info] [streamChoices] solution 0 returned. finish reason: [stop]
2024-11-17 10:09:24.452 [info] [streamChoices] request done: headerRequestId: [93685c18-7c45-4482-9a85-a2ba465df91e] model deployment ID: [d031-20241014223512]
2024-11-17 10:09:27.474 [info] [code-referencing] Calling Match
2024-11-17 10:09:27.782 [info] [code-referencing] No match found
2024-11-17 10:21:23.958 [info] [certificates] Removed 86 expired certificates
2024-11-17 10:21:35.035 [info] [fetcher] Using Helix fetcher.
2024-11-17 10:21:35.035 [info] [code-referencing] Public code references are enabled.
2024-11-17 10:21:38.922 [info] [fetcher] Using Helix fetcher.
2024-11-17 10:21:38.922 [info] [code-referencing] Public code references are enabled.
2024-11-17 10:21:38.923 [info] [auth] Successfully authenticated

## GitHub Copilot Chat
2024-11-17 09:58:39.317 [info] Using the Electron fetcher.
2024-11-17 09:58:39.317 [info] Initializing Git extension service.
2024-11-17 09:58:39.317 [info] Successfully activated the vscode.git extension.
2024-11-17 09:58:39.317 [info] Enablement state of the vscode.git extension: true.
2024-11-17 09:58:39.318 [info] Successfully registered Git commit message provider.
2024-11-17 09:58:39.321 [info] Logged in as xiaolitongxue5
2024-11-17 09:58:52.600 [info] Got Copilot token for xiaolitongxue5
2024-11-17 09:58:52.724 [info] copilot token chat_enabled: true, sku: free_educational
2024-11-17 09:58:52.724 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-11-17 09:58:52.736 [info] Registering default platform agent...
2024-11-17 09:58:53.905 [info] Fetched model metadata in 1295ms 01a622af-2524-4969-b801-52650e29f7dc
2024-11-17 09:58:54.202 [info] activationBlocker from 'languageModelAccess' took for 15645ms
2024-11-17 10:09:42.268 [info] Fetched model metadata in 1189ms 0fb06c17-bf26-4b67-baa5-49d223f08ba2
2024-11-17 10:21:23.874 [info] Using the Electron fetcher.
2024-11-17 10:21:23.874 [info] Initializing Git extension service.
2024-11-17 10:21:23.874 [info] Successfully activated the vscode.git extension.
2024-11-17 10:21:23.874 [info] Enablement state of the vscode.git extension: true.
2024-11-17 10:21:23.874 [info] Successfully registered Git commit message provider.
2024-11-17 10:21:24.035 [warning] GitHub login failed
2024-11-17 10:21:24.037 [error] Error: GitHubLoginFailed
    at iE._authShowWarnings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:3586)
    at iE.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:2135)
    at jk.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:37843)
    at EN.waitForChatEnabled (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:611:3181)
    at EN.run (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:611:2900)
    at eE.askToUpgradeAuthPermissions (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:611:2338): Failed to get copilot token
2024-11-17 10:21:24.037 [error] You are not signed in to GitHub. Please sign in to use Copilot.
2024-11-17 10:21:24.037 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-11-17 10:21:24.037 [error] Error: GitHubLoginFailed
    at iE._authShowWarnings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:3586)
    at iE.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:2135)
    at jk.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:37843)
    at fE._getAuthSession (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2597)
    at t (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:631)
    at fE._registerLanguageModels (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:1810)
    at async Promise.all (index 0)
    at async Promise.allSettled (index 0)
    at Ev.waitForActivationBlockers (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:25616)
    at c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:1817:4068
    at qPt (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:1817:3881)
    at B0.n (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4447)
    at B0.m (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4410)
    at B0.l (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:3866)
2024-11-17 10:21:24.037 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-11-17 10:21:24.037 [error] Error: GitHubLoginFailed
    at iE._authShowWarnings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:3586)
    at iE.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:2135)
    at jk.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:37843)
    at fE._getAuthSession (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2597)
    at t (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2060)
    at fE._registerEmbeddings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2559)
    at async Promise.all (index 1)
    at async Promise.allSettled (index 0)
    at Ev.waitForActivationBlockers (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:25616)
    at c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:1817:4068
    at qPt (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:1817:3881)
    at B0.n (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4447)
    at B0.m (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4410)
    at B0.l (file:///c:/Users/25319/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:3866)
2024-11-17 10:21:24.037 [info] activationBlocker from 'languageModelAccess' took for 205ms
2024-11-17 10:21:24.043 [warning] GitHub login failed
2024-11-17 10:21:24.044 [info] copilot token chat_enabled: undefined, sku: 
2024-11-17 10:21:24.048 [warning] GitHub login failed
2024-11-17 10:21:24.049 [error] You are not signed in to GitHub. Please sign in to use Copilot.
2024-11-17 10:21:24.049 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-11-17 10:21:24.049 [error] Error: GitHubLoginFailed
    at iE._authShowWarnings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:3586)
    at iE.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:2135)
    at jk.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:37843)
    at fE._getAuthSession (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2597)
    at t (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2060)
2024-11-17 10:21:24.049 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-11-17 10:21:24.049 [error] Error: GitHubLoginFailed
    at iE._authShowWarnings (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:3586)
    at iE.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:613:2135)
    at jk.getCopilotToken (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:282:37843)
    at fE._getAuthSession (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:2597)
    at t (c:\Users\25319\.vscode\extensions\github.copilot-chat-0.22.2\dist\extension.js:628:631)
2024-11-17 10:21:34.404 [info] Logged in as xiaolitongxue5
2024-11-17 10:21:35.515 [info] Got Copilot token for xiaolitongxue5
2024-11-17 10:21:35.568 [info] copilot token chat_enabled: true, sku: free_educational
2024-11-17 10:21:35.568 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-11-17 10:21:35.575 [info] Registering default platform agent...
2024-11-17 10:21:36.554 [info] Fetched model metadata in 945ms 5f62824a-73af-4788-91aa-b65c976a5454
2024-11-17 10:31:49.370 [info] Fetched model metadata in 1039ms d318906d-9c39-4fc5-b265-82a134547403
2024-11-17 10:35:26.874 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:35:37.792 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:35:46.060 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:35:48.122 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:35:56.280 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:36:14.074 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:36:17.153 [trace] Resolving embedding model
2024-11-17 10:36:17.153 [trace] Resolved embedding model
2024-11-17 10:36:22.163 [info] Removed 86 expired certificates
2024-11-17 10:36:24.053 [debug] [LanguageModelAccess] UPDATING language models
2024-11-17 10:36:24.053 [debug] [LanguageModelAccess] UPDATING language models
2024-11-17 10:36:24.054 [trace] Resolving chat model
2024-11-17 10:36:24.054 [trace] Resolving chat model
2024-11-17 10:36:24.054 [trace] Resolved chat model
2024-11-17 10:36:24.054 [trace] Resolved chat model
2024-11-17 10:36:36.813 [debug] [LanguageModelAccess] UPDATING language models
2024-11-17 10:36:36.813 [trace] Resolving chat model
2024-11-17 10:36:36.813 [trace] Resolved chat model
2024-11-17 10:37:21.972 [trace] Resolving chat model
2024-11-17 10:37:21.972 [trace] Resolved chat model
2024-11-17 10:37:21.974 [trace] [inline] chat request received from extension host
2024-11-17 10:37:21.974 [trace] Building intent detector
2024-11-17 10:37:21.975 [trace] Resolving chat model
2024-11-17 10:37:21.975 [trace] Resolved chat model
2024-11-17 10:37:21.979 [trace] Built intent detector
2024-11-17 10:37:42.362 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:37:49.627 [trace] Resolving chat model
2024-11-17 10:37:49.627 [trace] Resolved chat model
2024-11-17 10:37:49.731 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:38:01.078 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:38:28.885 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:38:33.302 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:38:37.771 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:38:50.664 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:38:50.740 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:39:36.541 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:39:36.602 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:40:02.219 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:40:02.293 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:41:02.946 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: false.
2024-11-17 10:41:02.973 [debug] [context keys] Window state change. Needs offline check: false, active: true, focused: true.
2024-11-17 10:42:02.488 [trace] Resolving embedding model
2024-11-17 10:42:03.507 [info] Fetched model metadata in 1019ms 818d6d92-ef51-4d5d-8db2-9e6450f8e2fb
2024-11-17 10:42:03.507 [trace] Resolved embedding model

**Comment by roblourens** [comment]
Does it look like you are logged in to your github account in vscode? Can you try logging out and logging back in to your github account in vscode?

**Comment by xiaolitongxue5** [comment]
> Does it look like you are logged in to your github account in vscode? Can you try logging out and logging back in to your github account in vscode?

Sorry, I forget close the issue, this problem has been resolved.
Yes,I have try loginng out and loginng back twice. But this problem still happened. 
Finally, I found it is because the plugin “Fitten Code” and "github copilot" are conflict. After I unable  the “Fitten Code” ,"github copilot" is working.  : )
