### ISSUE TITLE
Copilot Chat error: unhandled status from server: 400 (Response filtered)

### ISSUE THREAD

**Issue by Akash1134** [microsoft/vscode-copilot-release#265]
- Error

`unhandled status from server: 400 {"error":{"code":"content_filter","message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","param":"prompt","status":400,"type":null}}`

- VS Code Version: 1.2023052901
- OS Version: macOS 13.4
- Logs: 
Customer using Copilot along with GitHub Codespace when they got this message. 
Here is the console log for that error
``` javascript
vscs:sw:b17a:LiveShareHttpClient Failed to respond with asset {shouldCacheResponse: true, sessionId: '5A6CF23005348D37FD4DE6FBCB987E9563ED', port: 33321, originalUrl: URL, containerUrl: URL, …}containerUrl: URL {origin: 'https://localhost:80', protocol: 'https:', username: '', password: '', host: 'localhost:80', …}originalUrl: URL {origin: 'https:/my-codespace-example.github.dev', protocol: 'https:', username: '', password: '', host: 'mishra-saksham-glowing-pancake-j6w99pjxrg72jp.github.dev', …}port: 33321sessionId: "5A6CF23005348D37FD4DE6FBCB981234567"shouldCacheResponse: truevscodeConnectionDetails: connectionToken: "c574397e-e230-470c-8f9f-uvwxyz"[[Prototype]]: Object[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() Error: Cannot establish a VSCode connection.
    at service-worker.js:1:653295
    at service-worker.js:1:653477
    at Object.<anonymous> (service-worker.js:1:1691288)
    at Generator.next (<anonymous>)
    at s (service-worker.js:1:1689154)
writeEvent @ service-worker.js:1
traceEvent @ service-worker.js:1
(anonymous) @ service-worker.js:1
traceEvent @ service-worker.js:1
error @ service-worker.js:1
(anonymous) @ service-worker.js:1
s @ service-worker.js:1
Promise.then (async)
c @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
respondWithAssetFromEnvironment @ service-worker.js:1
(anonymous) @ service-worker.js:1
s @ service-worker.js:1
Promise.then (async)
c @ service-worker.js:1
s @ service-worker.js:1
Promise.then (async)
c @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
fetch @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
vscode-remote-resource:1     
```

Reported threads:

https://github.com/orgs/community/discussions/58084
https://github.com/orgs/community/discussions/58222
https://github.com/orgs/community/discussions/56693

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
