### ISSUE TITLE
[ghostText] Error on ghost text request: FetchError: The pending stream has been canceled (caused by: self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by stribus** [microsoft/vscode-copilot-release#2704]
Type: <b>Bug</b>

 [error] [ghostText] Error on ghost text request: FetchError: The pending stream has been canceled (caused by: self signed certificate in certificate chain)
    at fetch (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:288:16)
    at pue.fetch (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\lib\src\network\helix.ts:93:22)
    at nY.fetchWithParameters (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\lib\src\openai\fetch.ts:451:26)
    at nY.fetchAndStreamCompletions (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\lib\src\openai\fetch.ts:354:26)
    at genericGetCompletionsFromNetwork (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\lib\src\ghostText\ghostText.ts:149:21)
    at getGhostText (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\lib\src\ghostText\ghostText.ts:698:23)
    at calculateInlineCompletions (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\extension\src\ghostText\ghostText.ts:77:20)
    at provideInlineCompletions (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\extension\src\ghostText\ghostText.ts:140:20)
    at Rue.provideInlineCompletionItems (c:\Users\USER\.vscode\extensions\github.copilot-1.245.0\extension\src\ghostText\ghostText.ts:153:27)
    at RH.provideInlineCompletions (file:///c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:142456) {
  type: 'system',
  _name: 'FetchError',
  code: 'ERR_HTTP2_STREAM_CANCEL',
  errno: undefined,
  erroredSysCall: undefined
}

Extension version: 0.22.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 PRO 2200G with Radeon Vega Graphics (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.93GB (2.96GB free)|
|Process Argv|--crash-reporter-id d603eaae-d102-4557-a22b-9763dc803302|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by stribus** [comment]
DIAGNOSTIC

## Copilot

- Version: 1.245.0
- Build: prod
- Editor: vscode/1.95.3

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: c:\Users\USER\.vscode\extensions\ukoloff.win-ca-3.5.1\node_modules\win-ca\pem
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: enabled
- Chat: enabled
- Content exclusion: unavailable

## Node setup

- Number of root certificates: 147
- Operating system: Windows_NT
- Operating system version: 10.0.19045
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- proxy.individual.githubcopilot.com: The pending stream has been canceled (caused by: self signed certificate in certificate chain)
- api.individual.githubcopilot.com: HTTP 200
- telemetry.individual.githubcopilot.com: The pending stream has been canceled (caused by: self signed certificate in certificate chain)
- default.exp-tas.com: The pending stream has been canceled (caused by: self signed certificate in certificate chain)

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: false
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: true
- Is `mac-ca` installed?: false

**Comment by stribus** [comment]
Consegui contornar o problema seguindo os seguintes passos:
1-entrei na URL https://telemetry.individual.githubcopilot.com pelo chrome.
2-acessei os detalhes dos  certificados
3-exportei todos os certificados apresentados na da hierarquia de certificados
4-concatenei todos os certificados em único arquivo
5-criei a seguinte variavel de ambiente ```NODE_EXTRA_CA_CERTS=C:\caminho\para\certificados-concatenados.crt```
6-tambem criei a variavel de ambiente ```NODE_TLS_REJECT_UNAUTHORIZED=0```
7-Reiniciei o computador e com isso o github copilot voltou a funcionar normalmente

-----------------
_#translation by chatgpt_ :
I managed to resolve the issue by following these steps:

Opened the URL https://telemetry.individual.githubcopilot.com/ in Chrome.
Accessed the certificate details.
Exported all certificates displayed in the certificate hierarchy.
Concatenated all certificates into a single file.
Created the following environment variable:
```NODE_EXTRA_CA_CERTS=C:\path\to\concatenated-certificates.crt```
Also created the environment variable:
```NODE_TLS_REJECT_UNAUTHORIZED=0```
Restarted the computer.
After these steps, GitHub Copilot started working normally again.
