### ISSUE TITLE
fails with attached message in Visual Studio

### ISSUE THREAD

**Issue by johnpyrce** [microsoft/vscode-copilot-release#276]
On start up, get these messages in GitHub Copilot Chat output window in Visual Studio 2022:

StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.VisualStudio.Conversations.CopilotClient.CopilotAuthTokenManager.GetTokenAsync(CancellationToken cancellationToken, TelemetryScope`1 scope) in D:\a\_work\1\s\CopilotClient\CopilotAuthTokenManager.cs:line 131
      at Microsoft.VisualStudio.Conversations.CopilotClient.CopilotAuthTokenManager.GetAuthInfoAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\CopilotClient\CopilotAuthTokenManager.cs:line 98
      at Microsoft.VisualStudio.Conversations.Service.ServiceTarget.GetAuthInfoAsync(CancellationToken cancellationToken)

(Regualr) CoPilot works, but CoPilot chat does not work.

**Comment by jrieken** [comment]
Wrong repo. This is about VS Code
