### ISSUE TITLE
Unable to use Copilot Chat

### ISSUE THREAD

**Issue by phithiencuti** [microsoft/vscode-copilot-release#2895]
- Copilot Chat Extension Version: v1.246.0
- VS Code Version: 1.95.3
- OS Version: Windows 11 Pro 64-bit (10.0, build 22631)
- Logs: 2024-11-28 09:28:29.632 [info] Using the Electron fetcher.
2024-11-28 09:28:29.633 [info] Initializing Git extension service.
2024-11-28 09:28:29.633 [info] Successfully activated the vscode.git extension.
2024-11-28 09:28:29.633 [info] Enablement state of the vscode.git extension: true.
2024-11-28 09:28:29.633 [info] Successfully registered Git commit message provider.
2024-11-28 09:28:29.633 [info] Logged in as PD0A6174_ebazy1
2024-11-28 09:28:30.425 [info] Got Copilot token for PD0A6174_ebazy1
2024-11-28 09:28:31.115 [info] copilot token chat_enabled: true, sku: copilot_standalone_seat
2024-11-28 09:28:31.119 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-11-28 09:28:31.151 [info] Registering default platform agent...
2024-11-28 09:28:31.275 [info] Fetched model metadata in 835ms e17d074c-bf9c-4de5-befe-cfd3cffc1137
2024-11-28 09:28:31.345 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431): Failed to fetch models (e17d074c-bf9c-4de5-befe-cfd3cffc1137)
2024-11-28 09:28:31.345 [info] activationBlocker from 'languageModelAccess' took for 1817ms
2024-11-28 09:28:31.541 [warning] Invalid remote agent response: <!DOCTYPE html><html><head><style>html,body {height:100%; margin:0; padding:0; overflow:hidden;}</style></head><body><iframe src="https://121.166.148.217/Policy_Denied.html?user=172.20.183.2-172.20.183.230_32&addr=172.20.183.15&pno=322&cate=241121%5FGithub%20Copilot%5FTEST&pname=VDI%5FDev%5FIps%5Finternet%5Fdeny%28VDI%5FDev%5F%EC%9D%B8%ED%84%B0%EB%84%B7%EC%B0%A8%EB%8B%A8%29&svr_ip=140.82.112.21&url=api.business.githubcopilot.com/agents" width="100%" height="100%" style="border:none;">This browser does not support iframe.</iframe></body></htm (SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON)
2024-11-28 09:28:33.456 [info] Fetched model metadata in 2111ms f5fdc78c-4988-4e9a-ba30-18e2454727a4
2024-11-28 09:28:33.461 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431): Failed to fetch models (f5fdc78c-4988-4e9a-ba30-18e2454727a4)
2024-11-28 09:28:54.151 [info] Using the Electron fetcher.
2024-11-28 09:28:54.151 [info] Initializing Git extension service.
2024-11-28 09:28:54.418 [info] Logged in as PD0A6174_ebazy1
2024-11-28 09:28:55.279 [info] Successfully activated the vscode.git extension.
2024-11-28 09:28:55.279 [info] Enablement state of the vscode.git extension: true.
2024-11-28 09:28:55.279 [info] Successfully registered Git commit message provider.
2024-11-28 09:28:55.606 [info] Got Copilot token for PD0A6174_ebazy1
2024-11-28 09:28:55.838 [info] copilot token chat_enabled: true, sku: copilot_standalone_seat
2024-11-28 09:28:55.838 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-11-28 09:28:55.886 [info] Registering default platform agent...
2024-11-28 09:28:58.194 [info] Fetched model metadata in 2562ms 25f7d60e-e5ed-43fb-b6d6-61910ac7d60b
2024-11-28 09:28:58.209 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431): Failed to fetch models (25f7d60e-e5ed-43fb-b6d6-61910ac7d60b)
2024-11-28 09:28:58.210 [info] activationBlocker from 'languageModelAccess' took for 4084ms
2024-11-28 09:28:58.215 [warning] Invalid remote agent response: <!DOCTYPE html><html><head><style>html,body {height:100%; margin:0; padding:0; overflow:hidden;}</style></head><body><iframe src="https://121.166.148.217/Policy_Denied.html?user=172.20.183.2-172.20.183.230_32&addr=172.20.183.15&pno=322&cate=241121%5FGithub%20Copilot%5FTEST&pname=VDI%5FDev%5FIps%5Finternet%5Fdeny%28VDI%5FDev%5F%EC%9D%B8%ED%84%B0%EB%84%B7%EC%B0%A8%EB%8B%A8%29&svr_ip=140.82.112.21&url=api.business.githubcopilot.com/agents" width="100%" height="100%" style="border:none;">This browser does not support iframe.</iframe></body></htm (SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON)
2024-11-28 09:28:58.678 [info] Fetched model metadata in 468ms 248958d4-918c-45d5-b499-92a119ad4ae6
2024-11-28 09:28:58.679 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431)
    at Wm.getChatModelFromFamily (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:15511)
    at l2.getChatEndpoint (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:20787)
    at t (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:628:825)
    at fE._registerLanguageModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:628:1810)
    at async Promise.all (index 0): Failed to fetch models (248958d4-918c-45d5-b499-92a119ad4ae6)
2024-11-28 09:31:51.620 [info] Using the Electron fetcher.
2024-11-28 09:31:51.620 [info] Initializing Git extension service.
2024-11-28 09:31:51.620 [info] Successfully activated the vscode.git extension.
2024-11-28 09:31:51.620 [info] Enablement state of the vscode.git extension: true.
2024-11-28 09:31:51.620 [info] Successfully registered Git commit message provider.
2024-11-28 09:31:51.629 [info] Logged in as PD0A6174_ebazy1
2024-11-28 09:31:52.622 [info] Got Copilot token for PD0A6174_ebazy1
2024-11-28 09:31:52.671 [info] copilot token chat_enabled: true, sku: copilot_standalone_seat
2024-11-28 09:31:52.671 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-11-28 09:31:52.692 [info] Registering default platform agent...
2024-11-28 09:31:53.077 [info] Fetched model metadata in 446ms 6842c28c-1758-4984-b6c3-a3abe773ae97
2024-11-28 09:31:53.079 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431): Failed to fetch models (6842c28c-1758-4984-b6c3-a3abe773ae97)
2024-11-28 09:31:53.080 [info] activationBlocker from 'languageModelAccess' took for 1627ms
2024-11-28 09:31:53.083 [warning] Invalid remote agent response: <!DOCTYPE html><html><head><style>html,body {height:100%; margin:0; padding:0; overflow:hidden;}</style></head><body><iframe src="https://121.166.148.217/Policy_Denied.html?user=172.20.183.2-172.20.183.230_32&addr=172.20.183.15&pno=324&cate=241121%5FGithub%20Copilot%5FTEST&pname=VDI%5FDev%5FIps%5Finternet%5Fdeny%28VDI%5FDev%5F%EC%9D%B8%ED%84%B0%EB%84%B7%EC%B0%A8%EB%8B%A8%29&svr_ip=140.82.113.21&url=api.business.githubcopilot.com/agents" width="100%" height="100%" style="border:none;">This browser does not support iframe.</iframe></body></htm (SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON)
2024-11-28 09:31:53.530 [info] Fetched model metadata in 450ms ac236d54-bb95-4427-b1cd-0000ca1ca02b
2024-11-28 09:31:53.530 [error] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
    at successSteps (node:internal/deps/undici/undici:5470:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:5479:7)
    at Wm._fetchModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:17431)
    at Wm.getChatModelFromFamily (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:15511)
    at l2.getChatEndpoint (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1773:20787)
    at t (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:628:825)
    at fE._registerLanguageModels (c:\Users\pd0a6174\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:628:1810)
    at async Promise.all (index 0): Failed to fetch models (ac236d54-bb95-4427-b1cd-0000ca1ca02b)

Steps to Reproduce:
 The copilot account is provided by company and running on virtual machine with most of the domain blocked. Which domain need to be unlocked in order for the Copilot chat to be used by both VS Code and Intellij Idea?
1.  When opening Copilot Chat Extension on VS CODE

**Comment by srsajjad** [comment]
not working on my m1 macbook either, i click on the copilot icon, the chat box on the right side isn't showing up, working fine on my ubuntu though @mjbvz

**Comment by srsajjad** [comment]
Here's a screen record. When I am clicking on open chat, nothing is happening
https://www.loom.com/share/ff324a902f62485f81a0b0216142ed8b?sid=31ce29af-6749-48b7-994d-a2ed827dd9b8

**Comment by srsajjad** [comment]
@lramos15 thanks working now, after installing that extension manually
