### ISSUE TITLE
Language model unavailable

### ISSUE THREAD

**Issue by lgyz123** [microsoft/vscode-copilot-release#3215]
Type: <b>Bug</b>

Language model unavailable

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details><summary>Prompt Details</summary>
<pre>
Info: Can't use the Electron fetcher in this environment.
Info: Using the Node fetch fetcher.
Info: Initializing Git extension service.
Debug: [context keys] Updating context keys.
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13850HX (28 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.61GB (4.87GB free)|
|Process Argv|--crash-reporter-id 9cfd0538-5b46-47af-89e5-8677df8e920d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: OneDriving Devcontainer - Docker Compose|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13850HX (28 x 0)|
|Memory (System)|15.62GB (10.94GB free)|
|VM|0%|
</details>

**Comment by nbrinks** [comment]
I am also getting this error in the UI after updating to 0.23.1. Everything appears to work correctly when switching back to 0.22.4.

Error in chat:
![Image](https://github.com/user-attachments/assets/1c2eaf71-5f79-4d3b-982d-11190037af62)


Error notification:
![Image](https://github.com/user-attachments/assets/852ced13-21f1-4732-85ac-30e8689f8d24)



Also, I noticed when switching to 0.23.1 I get an additional error message about a different plugin. Incompatibility maybe?
![Image](https://github.com/user-attachments/assets/5a6d5b9a-243a-4fce-8c3c-4b7ed89763e1)


<details>
<summary>0.23.1 "Run Diagnostics"</summary>

```
## GitHub Copilot Chat

- Extension Version: 0.23.1 (prod)
- VS Code: vscode/1.96.0
- OS: Linux
- Remote Name: wsl

## Network

User Settings:

  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true


Connecting to https://api.github.com:
- DNS ipv4 Lookup: 140.82.113.5 (25 ms)
- DNS ipv6 Lookup: Error (262 ms): getaddrinfo ENOTFOUND api.github.com
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: HTTP 200 (184 ms)
- Node.js fetch (configured): HTTP 200 (195 ms)
- Helix fetch: HTTP 200 (266 ms)

Connecting to http://localhost:5000/_ping:
- DNS ipv4 Lookup: 127.0.0.1 (1 ms)
- DNS ipv6 Lookup: ::1 (175 ms)
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: Error (2 ms): connect ECONNREFUSED 127.0.0.1:5000
- Node.js fetch (configured): Error (1 ms): fetch failed
  connect ECONNREFUSED 127.0.0.1:5000
- Helix fetch: Error (2 ms): connect ECONNREFUSED 127.0.0.1:5000

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
```

</details>

<details>
<summary>Output from 0.22.4</summary>

```
2024-12-13 11:11:31.923 [info] Can't use the Electron fetcher in this environment.
2024-12-13 11:11:31.923 [info] Using the Helix fetcher.
2024-12-13 11:11:31.923 [info] Initializing Git extension service.
2024-12-13 11:11:31.932 [info] Successfully activated the vscode.git extension.
2024-12-13 11:11:31.932 [info] Enablement state of the vscode.git extension: true.
2024-12-13 11:11:31.932 [info] Successfully registered Git commit message provider.
2024-12-13 11:11:32.520 [info] Logged in as b_REDACTED_n
2024-12-13 11:11:32.677 [info] Removed 1 expired certificates
2024-12-13 11:11:34.315 [info] Got Copilot token for b_REDACTED_n
2024-12-13 11:11:34.586 [info] copilot token chat_enabled: true, sku: copilot_for_business_seat
2024-12-13 11:11:34.586 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-13 11:11:34.595 [info] Registering default platform agent...
2024-12-13 11:11:35.043 [info] Fetched model metadata in 724ms 329b68b7-34ab-4678-99cc-e506bfce784e
2024-12-13 11:11:35.275 [info] activationBlocker from 'languageModelAccess' took for 3169ms
```
</details>

<details>
<summary>Output from 0.23.1</summary>

```
2024-12-13 11:09:02.199 [info] Can't use the Electron fetcher in this environment.
2024-12-13 11:09:02.199 [info] Using the Node fetch fetcher.
2024-12-13 11:09:02.199 [info] Initializing Git extension service.
2024-12-13 11:09:02.199 [info] Successfully activated the vscode.git extension.
2024-12-13 11:09:02.199 [info] Enablement state of the vscode.git extension: true.
2024-12-13 11:09:02.199 [info] Successfully registered Git commit message provider.
2024-12-13 11:09:03.149 [info] Logged in as b_REDACTED_n
2024-12-13 11:09:04.064 [info] Got Copilot token for b_REDACTED_n
2024-12-13 11:09:04.195 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405): Failed to fetch models (600ca856-8409-4c3e-bbf4-047f875a295e)
2024-12-13 11:09:04.195 [info] activationBlocker from 'languageModelAccess' took for 1832ms
2024-12-13 11:09:04.346 [info] copilot token chat_enabled: true, sku: copilot_for_business_seat
2024-12-13 11:09:04.347 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-13 11:09:04.356 [info] Registering default platform agent...
2024-12-13 11:09:04.379 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at V0._doRefreshRemoteAgents (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:491:8964): Failed to load remote copilot agents
2024-12-13 11:09:04.380 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getChatModelFromFamily (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:10055)
    at WO.getChatEndpoint (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:14751)
    at Object.A [as task] (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:834)
    at xC._processQueue (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): Failed to fetch models (711e2856-56a2-44c2-958b-9511255b2731)
2024-12-13 11:09:04.380 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getChatModelFromFamily (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:10055)
    at WO.getChatEndpoint (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:14751)
    at Object.A [as task] (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:834)
    at xC._processQueue (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): [LanguageModelAccess] FAILED to update language models
2024-12-13 11:09:04.592 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405): Failed to fetch models (8a23ae8a-e540-472c-91fe-97bac3c1ff51)
2024-12-13 11:09:04.627 [info] Subscription based route failed when legacy route succeeded. Retrying in 5 seconds. Error: http://localhost:5000/_ping failed with error: fetch failed
  connect ECONNREFUSED 127.0.0.1:5000
2024-12-13 11:09:04.746 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getChatModelFromFamily (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:10055)
    at WO.getChatEndpoint (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:14751)
    at Object.A [as task] (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:834)
    at xC._processQueue (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): Failed to fetch models (012f6a45-92ea-42d4-a57b-d3b85105fe82)
2024-12-13 11:09:04.746 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getChatModelFromFamily (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:10055)
    at WO.getChatEndpoint (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:14751)
    at Object.A [as task] (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:834)
    at xC._processQueue (/home/b_REDACTED_n/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): [LanguageModelAccess] FAILED to update language models
2024-12-13 11:09:09.825 [info] Subscription based route failed when legacy route succeeded. Retrying in 5 seconds. Error: http://localhost:5000/_ping failed with error: fetch failed
  connect ECONNREFUSED 127.0.0.1:5000
2024-12-13 11:09:15.022 [error] Subscription based route failed when legacy route succeeded. Error: http://localhost:5000/_ping failed with error: fetch failed
  connect ECONNREFUSED 127.0.0.1:5000
```
</details>

The obvious thing I notice is switching from the "Helix" fetcher to the "Node Fetch" fetcher.

**Comment by nbrinks** [comment]
For some reason my user settings included this setting. This could have been an experiment I did. I don't remember. 🤷‍♂ 

```json
  "github.copilot.advanced": {
    "debug.overrideCapiUrl": "http://localhost:5000"
  },
```

Removing this setting fixed my problem.

<details>
<summary>Output from 0.23.1</summary>

```
2024-12-13 12:01:50.110 [info] Can't use the Electron fetcher in this environment.
2024-12-13 12:01:50.110 [info] Using the Node fetch fetcher.
2024-12-13 12:01:50.110 [info] Initializing Git extension service.
2024-12-13 12:01:50.110 [info] Successfully activated the vscode.git extension.
2024-12-13 12:01:50.110 [info] Enablement state of the vscode.git extension: true.
2024-12-13 12:01:50.110 [info] Successfully registered Git commit message provider.
2024-12-13 12:01:51.352 [info] Logged in as b_REDACTED_n
2024-12-13 12:01:52.528 [info] Got Copilot token for b_REDACTED_n
2024-12-13 12:01:52.822 [info] copilot token chat_enabled: true, sku: copilot_for_business_seat
2024-12-13 12:01:52.822 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-13 12:01:52.831 [info] Registering default platform agent...
2024-12-13 12:01:53.290 [info] Fetched model metadata in 759ms 01e33e65-3092-4334-9b7e-7a816e0fc369
2024-12-13 12:01:53.292 [info] activationBlocker from 'languageModelAccess' took for 2739ms
```

</details>
