### ISSUE TITLE
keeps crashing if gitignore files are included in explorer and search

### ISSUE THREAD

**Issue by anandmurali-pw** [microsoft/vscode-copilot-release#3344]
Type: <b>Bug</b>

I have enabled 
Explorer: Exclude Git ignore
and
Search: Use ignore files

this enables me to search and work on folders added in .gitignore

When these are enabled, github copilot doesn't work after sometime and crashes are seen in chat

2024-12-18 09:23:27.007 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getAllChatModels (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:9332)
    at WO.getAllChatEndpoints (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:15770)
    at Object.A [as task] (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:781)
    at xC._processQueue (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): Failed to fetch models (21dbdacd-a662-4c8b-a87f-b6a76d061a08)

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-127-generic
Remote OS version: Linux x64 5.15.0-127-generic

<details><summary>Prompt Details</summary>
<pre>
Info: Can't use the Electron fetcher in this environment.
Info: Using the Node fetch fetcher.
Info: Initializing Git extension service.
Info: Successfully activated the vscode.git extension.
Info: Enablement state of the vscode.git extension: true.
Info: Successfully registered Git commit message provider.
Debug: [context keys] Updating context keys.
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (4.42GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B10.146.9.95/root/CLONES/automation/automation-core --crash-reporter-id 504804bb-5edb-4ad4-bebf-06acb8321bae|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.146.9.95|
|OS|Linux x64 5.15.0-127-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (8 x 0)|
|Memory (System)|15.61GB (9.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.146.9.95|
|OS|Linux x64 5.15.0-127-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (8 x 0)|
|Memory (System)|15.61GB (9.28GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by anandmurali-pw** [comment]
Not seen after updating Python extension to pre-release
```
Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2024.23.2024121901
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
```
