### ISSUE TITLE
chat keeps crashing

### ISSUE THREAD

**Issue by anandmurali-pw** [microsoft/vscode-copilot-release#3348]
Type: <b>Bug</b>

after updating vscode to latest, copilot stops working after sometime
in Copilot Chat output i keep seeing crashes

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-127-generic
Remote OS version: Linux x64 5.15.0-127-generic

<details><summary>Prompt Details</summary>
<pre>
Info: Can't use the Electron fetcher in this environment.
Info: Using the Node fetch fetcher.
Info: Initializing Git extension service.
Info: Successfully activated the vscode.git extension.
Info: Enablement state of the vscode.git extension: true.
Info: Successfully registered Git commit message provider.
Debug: [context keys] Updating context keys.
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (5.29GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B10.146.9.95/root/CLONES/automation/automation-core --crash-reporter-id 504804bb-5edb-4ad4-bebf-06acb8321bae|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.146.9.95|
|OS|Linux x64 5.15.0-127-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (8 x 0)|
|Memory (System)|15.61GB (8.44GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.146.9.95|
|OS|Linux x64 5.15.0-127-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (8 x 0)|
|Memory (System)|15.61GB (8.44GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by anandmurali-pw** [comment]
# Github Copilot Chat Output
`
2024-12-18 11:18:49.204 [info] Can't use the Electron fetcher in this environment.
2024-12-18 11:18:49.204 [info] Using the Node fetch fetcher.
2024-12-18 11:18:49.204 [info] Initializing Git extension service.
2024-12-18 11:18:49.204 [info] Successfully activated the vscode.git extension.
2024-12-18 11:18:49.204 [info] Enablement state of the vscode.git extension: true.
2024-12-18 11:18:49.204 [info] Successfully registered Git commit message provider.
2024-12-18 11:18:49.883 [info] Logged in as anandmurali-pw
2024-12-18 11:18:50.790 [info] Got Copilot token for anandmurali-pw
2024-12-18 11:18:51.188 [info] copilot token chat_enabled: true, sku: copilot_for_business_seat
2024-12-18 11:18:51.188 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-18 11:18:51.198 [info] Registering default platform agent...
2024-12-18 11:18:52.291 [info] Fetched model metadata in 1495ms 3599edb7-239b-4515-a855-e9c9b082f54d
2024-12-18 11:18:52.294 [info] activationBlocker from 'languageModelAccess' took for 2666ms
2024-12-18 11:34:03.490 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getAllChatModels (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:9332)
    at WO.getAllChatEndpoints (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:15770)
    at Object.A [as task] (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:781)
    at xC._processQueue (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): Failed to fetch models (a9cf9d35-8a24-47f2-a10c-4b21ac24ba1f)
2024-12-18 11:34:14.061 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at _p._fetchModels (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:11405)
    at _p.getChatModelFromFamily (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:10055)
    at WO.getChatEndpoint (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:14751)
    at Object.A [as task] (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:488:834)
    at xC._processQueue (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:487:1101): Failed to fetch models (8e8824ed-d6d9-4312-96c6-80ff79c9f11f)
2024-12-18 11:43:50.820 [info] Logged in as anandmurali-pw
2024-12-18 11:44:01.450 [info] Logged in as anandmurali-pw
2024-12-18 11:44:12.001 [info] copilot token chat_enabled: undefined, sku: 
2024-12-18 11:44:12.102 [info] Logged in as anandmurali-pw
2024-12-18 11:44:22.651 [error] GitHub Copilot could not connect to server. Extension activation failed: "fetch failed"
2024-12-18 11:44:22.651 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-18 11:44:22.651 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:334:21634)
    at B0._auth (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:446:3023)
2024-12-18 11:44:22.651 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-18 11:44:22.651 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:334:21634)
    at B0._auth (/root/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:446:3023)

`

**Comment by anandmurali-pw** [comment]
marked closed by mistake

**Comment by anandmurali-pw** [comment]
similar to https://github.com/microsoft/vscode-copilot-release/issues/3344

**Comment by chrmarti** [comment]
Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.

**Comment by anandmurali-pw** [comment]
# Diagnostics on vscode restart

## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.2
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:
```json
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 20.207.73.85 (79 ms)
- DNS ipv6 Lookup: Error (3 ms): getaddrinfo ENOTFOUND api.github.com
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: HTTP 200 (283 ms)
- Node.js fetch (configured): HTTP 200 (111 ms)
- Helix fetch: HTTP 200 (324 ms)

Connecting to https://api.business.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.113.22 (8 ms)
- DNS ipv6 Lookup: Error (1 ms): getaddrinfo ENOTFOUND api.business.githubcopilot.com
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: HTTP 200 (780 ms)
- Node.js fetch (configured): HTTP 200 (815 ms)
- Helix fetch: HTTP 200 (841 ms)

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).


# Diagnostics after sometime

## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.2
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:
```json
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: timed out after 10 seconds
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

Connecting to https://api.business.githubcopilot.com/_ping:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: timed out after 10 seconds
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

**Comment by anandmurali-pw** [comment]
Issue is only with latest version of vscode
I went back to 1.95.3 and it is working even after few hours

Extension version on 1.95.3:
github.copilot: v1.250.0
github.copilot-chat: 0.22.4

# Diagnostics
## GitHub Copilot Chat

- Extension Version: 0.22.4 (prod)
- VS Code: vscode/1.95.3
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 20.207.73.85 (1 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.github.com
- Electron Fetcher: Unavailable
- Node Fetcher: HTTP 200 (301 ms)
- Helix Fetcher (configured): HTTP 200 (432 ms)

Connecting to https://api.business.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.113.22 (8 ms)
- DNS ipv6 Lookup: Error: getaddrinfo ENOTFOUND api.business.githubcopilot.com
- Electron Fetcher: Unavailable
- Node Fetcher: HTTP 200 (760 ms)
- Helix Fetcher (configured): HTTP 200 (855 ms)

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

**Comment by anandmurali-pw** [comment]
unfortunately same issue came on 1.95.3 as well

copilot chat output
```
2024-12-21 10:41:41.382 [info] Can't use the Electron fetcher in this environment.
2024-12-21 10:41:41.382 [info] Using the Helix fetcher.
2024-12-21 10:41:41.382 [info] Initializing Git extension service.
2024-12-21 10:41:41.382 [info] Successfully activated the vscode.git extension.
2024-12-21 10:41:41.382 [info] Enablement state of the vscode.git extension: true.
2024-12-21 10:41:41.382 [info] Successfully registered Git commit message provider.
2024-12-21 10:41:42.684 [info] Logged in as anandmurali-pw
2024-12-21 10:41:42.770 [info] Removed 1 expired certificates
2024-12-21 10:41:44.091 [info] Got Copilot token for anandmurali-pw
2024-12-21 10:41:44.410 [info] copilot token chat_enabled: true, sku: copilot_for_business_seat
2024-12-21 10:41:44.410 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-21 10:41:44.423 [info] Registering default platform agent...
2024-12-21 10:41:45.331 [info] Fetched model metadata in 1233ms 2912fb64-0cee-44fc-9306-ada16884729f
2024-12-21 10:41:45.820 [info] activationBlocker from 'languageModelAccess' took for 5679ms
2024-12-21 10:46:59.253 [error] CodeExpectedError: cannot open vscode-remote://ssh-remote%2B<vm_ip>/<file_location>. Detail: Unable to read file 'vscode-remote://ssh-remote+<vm_ip>/<file_location>' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+<vm_ip>/<file_location>')
    at OFe.$tryOpenDocument (vscode-file://vscode-app/c:/Users/amurali/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:8481): Error opening context for file:///<file_location>
2024-12-21 10:47:00.711 [info] message 0 returned. finish reason: [stop]
2024-12-21 10:47:00.712 [info] request done: requestId: [ca48f42d-922f-4d87-8c89-34ba0a540c8e] model deployment ID: []
```

I have renamed vm ip and file location for policy reasons

**Comment by chrmarti** [comment]
This looks like https://github.com/microsoft/vscode-copilot-release/issues/3357. Do you have the Python extension installed? If so, could you update it to the latest pre-release version to get a fix for a known issue?

**Comment by anandmurali-pw** [comment]
yes after installing pre-release version of Python extension, working without any crash for at least few hours now

Python version for reference:
```
Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2024.23.2024121901
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
```
