### ISSUE TITLE
Keeps hanging: TypeError: fetch failed     at node:internal/deps/undici/undici:13392:13

### ISSUE THREAD

**Issue by etmoore** [microsoft/vscode-copilot-release#3357]
Type: <b>Bug</b>

Chat keeps failing. See "Sorry, your request failed. Please try again. Request id: e06234e0-3530-440a-8f5b-550713d60e33". Logs show errors like: 
```
2024-12-17 18:40:47.280 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:763:5811)
    at Mat (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2212:5824)
    at OO.fetchMany (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:1912)
    at OO.fetchOne (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2213:959)
    at Hw.fetchConversationResponse (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:1072:22350)
    at Hw.getResult (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:1072:20348)
    at wD.getResult (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:1075:8718)
    at o$.y (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.1/dist/extension.js:2212:1764)
    at fh.$invokeAgent (file:///nail/home/evanm/.vscode-server/cli/servers/Stable-138f619c86f1199955d53b4166bef66ef252935c/server/out/vs/workbench/api/node/extensionHostProcess.js:138:46609): Error on conversation request
```

Extension version: 0.23.1
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 6.2.0-1016-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: dev' could not be established  Canceled

Connection to 'SSH: dev' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 6.2.0-1016-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz (32 x 0)|
|Memory (System)|247.74GB (197.32GB free)|
|VM|0%|

Connection to 'SSH: dev' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by etmoore** [comment]
> Can you do F1 -> GitHub Copilot Chat Diagnostics and attach that output

## GitHub Copilot Chat

- Extension Version: 0.23.1 (prod)
- VS Code: vscode/1.96.0
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:
```json
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: timed out after 10 seconds
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

Connecting to https://api.business.githubcopilot.com/_ping:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: timed out after 10 seconds
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

**Comment by chrmarti** [comment]
Please append the Copilot Chat and the Remote Extension Host log from when this happens. (`F1` > `Output: Show Output Channels...` > `GitHub Copilot Chat` / `Remote Extension Host`)

Have you tried updating WSL as suggested in the discussion you linked to?

**Comment by jascomp** [comment]
@chrmarti correct.  WSL should not apply, but I do think it is a possible clue.  Are you able to confirm the remote Linux machine has been updated?

**Comment by chrmarti** [comment]
Missed that you're not on Windows. Could you try adding the following to your user settings (`F1` > `Preferences: Open User Settings (JSON)`):
```json
"github.copilot.advanced.debug.useNodeFetcher": true
```
Then reload VS Code and retry.

**Comment by etmoore** [comment]
update: I rebooted the remote linux host, and so far, copilot + chat are working again  🎉 
wish I had tried that earlier  😊   appreciate the help y'all provided. 

If I start having trouble again, I will try `useNodeFetcher` as you recommend @chrmarti  and report back.

**Comment by ahmadomira** [comment]
I'm experiencing the same issue. It appears related to VS Code's extension server. Whenever Copilot malfunctions, I also encounter problems launching the Python debugger. I've tried clearing VS Code's cache, uninstalling and reinstalling all extensions, and even reinstalling VS Code itself. Unfortunately, nothing has resolved the problem. 

## System Information 
Apple M3 Max (16 x 2400)
Load (avg)	3, 3, 3
Memory (System)	128.00GB (85.95GB free)

## Extensions
copilot v1.253.0
copilot-chat v0.23.2
debugpy	v2024.14.0
python	v2024.22.0
vscode-pylance v2024.12.1
datawrangler	v1.14.0
wolfram	v2.0.0


Here's Copilot's diagnostic report:

## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.1
- OS: Mac

## Network

User Settings:
```json
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": true,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (5 ms)
- Electron fetch (configured): HTTP 200 (61 ms)
- Node.js https: timed out after 10 seconds
- Node.js fetch: timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

Connecting to https://api.individual.githubcopilot.com/_ping:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (9 ms)
- Electron fetch (configured): HTTP 200 (105 ms)
- Node.js https: timed out after 10 seconds
- Node.js fetch: timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).


I have no network issues or whatsoever.

**Comment by etmoore** [comment]
I'm sad to report it's happening again to me.

**Comment by chrmarti** [comment]
@ahmadomira Since you mention SCM: There is an issue in the Python extension that seems to affect SCM. Could you try without the Python extension or update to its latest pre-release version that has a fix to check if that affects this issue? (https://github.com/microsoft/vscode-python/pull/24611)

**Comment by ahmadomira** [comment]
Hi @chrmarti,

Updating the Python extension to the latest pre-release version ([microsoft/vscode-python#24611](https://github.com/microsoft/vscode-python/pull/24611)) appears to have fixed all issues immediately. Copilot, SCM, and the Python debugger are all working correctly. I've been using it for a couple of hours without encountering any problems. Thank you!

**Comment by chrmarti** [comment]
@etmoore Could you try the same? The timeouts you are seeing in the diagnostics suggest this might be the same problem.

**Comment by etmoore** [comment]
@chrmarti :(  switched to Python plugin pre-release version, but unfortunately did not fix the issue.  Still seeing the same error: 

<img width="915" alt="Image" src="https://github.com/user-attachments/assets/b009f1a5-f638-4450-9723-8d6aeb469ba9" />

```
2024-12-23 09:01:34.581 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:454:9)
    at ek._fetch (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at Mat (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:2212:5858)
    at OO.fetchMany (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:2213:1912)
    at CD.detectIntent (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:1072:27728)
    at wD.selectIntent (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:1075:10638)
    at wD.getResult (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:1075:8080)
    at o$.y (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:2212:1798)
    at fh.$invokeAgent (file:///nail/home/evanm/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/workbench/api/node/extensionHostProcess.js:138:46609): Error on conversation request
2024-12-23 09:02:08.662 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at Mat (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:2212:5858)
    at OO.fetchMany (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:2213:1912)
    at CD.detectIntent (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:1072:27728)
    at CD.provideParticipantDetection (/nail/home/evanm/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:1072:26566): Error on conversation request
```

**Comment by jalenzz** [comment]
@chrmarti Same problem here. I tried the pre-release Python extension, but the problem was not solved. I also tried disabling all extensions except Copilot, but the problem was not solved.

I think this problem may be related to the proxy. Copilot did not use the proxy correctly.，I used SSH connect to a remote machine, it is network-isolated and can only access the network through a proxy, and I set env `http_proxy` and `https_proxy`.

I tested my connection according to https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot#diagnosing-network-issues.

`curl` use my proxy, no error. My proxy is correct and can connect to Copilot.

```sh
curl --verbose https://copilot-proxy.githubusercontent.com/_ping
```

```txt
* Uses proxy env variable https_proxy == 'http://192.168.1.108:7892'
*   Trying 192.168.1.108:7892...
* Connected to 192.168.1.108 (192.168.1.108) port 7892 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to copilot-proxy.githubusercontent.com:443
> CONNECT copilot-proxy.githubusercontent.com:443 HTTP/1.1
> Host: copilot-proxy.githubusercontent.com:443
> User-Agent: curl/7.87.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /opt/anaconda3/ssl/cacert.pem
*  CApath: /usr/lib/ssl/certs
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):

* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.githubusercontent.com
*  start date: Jun 20 00:00:00 2024 GMT
*  expire date: Jun 19 23:59:59 2025 GMT
*  subjectAltName: host "copilot-proxy.githubusercontent.com" matched cert's "*.githubusercontent.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /_ping]
* h2h3 [:scheme: https]
* h2h3 [:authority: copilot-proxy.githubusercontent.com]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x9e23b0)
> GET /_ping HTTP/2
> Host: copilot-proxy.githubusercontent.com
> user-agent: curl/7.87.0
> accept: */*
> 
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< content-security-policy: default-src 'none'; sandbox
< content-type: application/json
< strict-transport-security: max-age=31536000
< content-length: 48
< date: Thu, 26 Dec 2024 08:44:45 GMT
< x-github-backend: Kubernetes
< x-github-request-id: 35D3:1379B9:5E540C:605FCC:676D177D
< 
{"now":1735202685,"status":"ok","ns1":"200 OK"}
* Connection #0 to host 192.168.1.108 left intact
```

---

# But when I try `GitHub Copilot Chat Diagnostics and attach that output` 

```md
## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.2
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:

  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true


Connecting to https://api.github.com:
- DNS ipv4 Lookup: Error (6160 ms): getaddrinfo EAI_AGAIN api.github.com
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: Error (6949 ms): getaddrinfo EAI_AGAIN api.github.com
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

Connecting to https://api.githubcopilot.com/_ping:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https: timed out after 10 seconds
- Node.js fetch (configured): timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
```

# with `"github.copilot.advanced.debug.useNodeFetcher": true`

```md
## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.2
- OS: Linux
- Remote Name: ssh-remote

## Network

User Settings:

  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": true,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true


Connecting to https://api.github.com:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https (configured): timed out after 10 seconds
- Node.js fetch: timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

Connecting to https://api.githubcopilot.com/_ping:
- DNS ipv4 Lookup: timed out after 10 seconds
- DNS ipv6 Lookup: timed out after 10 seconds
- Proxy URL: None (0 ms)
- Electron fetch: Unavailable
- Node.js https (configured): timed out after 10 seconds
- Node.js fetch: timed out after 10 seconds
- Helix fetch: timed out after 10 seconds

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
```

If more information is required, please do tell me! I earnestly hope this problem can be resolved properly and satisfactorily! 😊

**Comment by chrmarti** [comment]
@jalenzz Are you still seeing this with the latest Python extension version 2024.22.1? (Yours also looks like https://github.com/microsoft/vscode-python/pull/24611 which is now fixed in the latest stable Python extension release.)

**Comment by jalenzz** [comment]
@chrmarti The problem seems to be gone with the latest Python extension version 2024.22.1. Thanks !

**Comment by etmoore** [comment]
I'm no longer seeing the issue 🎉 
Using python plugin pre-release version 2024.23.2024121901

**Comment by chrmarti** [comment]
Great, thanks for the update. Closing the issue.
