### ISSUE TITLE
@workspace invalid file pattern provided

### ISSUE THREAD

**Issue by cristopherpds** [microsoft/vscode-copilot-release#3387]
Type: <b>Bug</b>

cristopherpds: @workspace 

Workspace: 

cristopherpds: @workspace o que e

Workspace: 

cristopherpds: @workspace de que se trata el proyecto

Workspace: 

cristopherpds: @workspace de que se trata el proyecto

Workspace: 

Extension version: 0.23.2024102903
VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.71GB (1.54GB free)|
|Process Argv|. --crash-reporter-id e2e4a94a-8fb5-4b1c-ac38-cf1bbb1b8bdd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by mjbvz** [comment]
Can you please run `Developer: Toggle developer tools` and then share the full error message from the developer console. It should also mention what the invalid file pattern was

**Comment by cmawhorter** [comment]
I updated vscode this morning and now I'm getting this error. Prior to this update i.e. since last update, I was getting a different error when trying to use workspace (which was being tracked in other issues here)

Here is the full error stack. I'm not seeing any file pattern mentioned apart from `[object Object]`.
```
Error: Invalid file pattern provided [object Object]
	at V0.z (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48882)
	at V0.findFiles2 (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48698)
	at Object.findFiles2 (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at KR.findFiles (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1118:21172)
	at KR._findFilesWithDefaultExcludesAndExcludes (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:348:11504)
	at KR.findFilesWithDefaultExcludes (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:348:11200)
	at XR.addWorkspace (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:10272)
	at vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:9877
	at XR.init (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:9894)
	at vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:4566
	at n.invokeFunction (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:276:941)
	at ZVe (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:4537)
	at jPt (vscode-file://vscode-app/Users/blah/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:3867)
	at Pw.kb (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at /Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
```

I thought it might have something to do with multiple tab groups or tabs open, so I closed them all and tried again and same issue.

**Comment by DemonMartin** [comment]
Having the same issue at the moment too.

These seem to be all errors, including "Invalid file pattern" in the console.

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Invalid file pattern provided [object Object]
EYi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: Error: Invalid file pattern provided [object Object]
	at V0.z (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48882)
	at V0.findFiles2 (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48698)
	at Object.findFiles2 (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at KR.findFiles (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1118:21172)
	at KR._findFilesWithDefaultExcludesAndExcludes (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:348:11504)
	at KR.findFilesWithDefaultExcludes (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:348:11200)
	at XR.addWorkspace (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:10272)
	at c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:9877
	at XR.init (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:9894)
	at c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:4566
	at n.invokeFunction (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:276:941)
	at ZVe (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:4537)
	at jPt (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:3867)
	at Pw.kb (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
EYi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [GitHub.copilot-chat]Invalid file pattern provided [object Object]
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: Invalid file pattern provided [object Object]
	at V0.z (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48882)
	at V0.findFiles2 (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48698)
	at Object.findFiles2 (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at KR.findFiles (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1118:21172)
	at KR._findFilesWithDefaultExcludesAndExcludes (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:348:11504)
	at KR.findFilesWithDefaultExcludes (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:348:11200)
	at XR.addWorkspace (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:10272)
	at c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:9877
	at XR.init (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1120:9894)
	at c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:4566
	at n.invokeFunction (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:276:941)
	at ZVe (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:4537)
	at jPt (c:\Users\skubi\.vscode\extensions\github.copilot-chat-0.23.2024102903\dist\extension.js:1824:3867)
	at Pw.kb (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at /c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (/c:/Users/skubi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
```

Hope the errors can somehow help resolve the issue. The "workspace" feature seems to be completely unusable for me right now.

**Comment by mjbvz** [comment]
Thanks for the logs. Can anyone seeing this please share the list of other extensions you have installed as well? It's possible that another extension is interfering with copilot so I'd like to see if there's a common extension that's causing this

**Comment by mjbvz** [comment]
Thanks, I think actually you just need to update the extension

`0.23.2024102903 ` is pretty old at this point so please try updating to latest copilot chat release.  If you're using the stable version of VS Code you should also switch to use the stable version of the chat extension too

Let me know if that fixes the issue

**Comment by cristopherpds** [comment]
﻿I apologize for the delay, I still have this problem.


```
console.ts:137 [Extension Host] TypeError: Cannot read properties of undefined (reading 'uri')
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:30:55
    at Array.filter (<anonymous>)
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:28:57
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:105082)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Ow.acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:11525)
    at Ow.$acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:10121)
    at Dy.S (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
log.ts:425  INFO Settings Sync: Token updated for the account cristopherpds
log.ts:445   ERR [Extension Host] Received response message without id. No further error information provided.
console.ts:137 [Extension Host] Received response message without id. No further error information provided.
20
console.ts:137 [Extension Host] TypeError: Cannot read properties of undefined (reading 'uri')
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:30:55
    at Array.filter (<anonymous>)
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:28:57
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:105082)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Ow.acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:11525)
    at Ow.$acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:10121)
    at Dy.S (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
console.ts:137 [Extension Host] ApplicationInsights:Sender 
Array(1)
console.ts:137 [Extension Host] ApplicationInsights:Sender 
Array(1)
```

```
Extension Host] TypeError: Cannot read properties of undefined (reading 'uri')
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:30:55
    at Array.filter (<anonymous>)
    at c:\Users\josue\.vscode\extensions\dotenv.dotenv-vscode-0.28.1\lib\autocloaking.js:28:57
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:105082)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Ow.acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:11525)
    at Ow.$acceptDocumentsAndEditorsDelta (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:10121)
    at Dy.S (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
workbench.desktop.main.js:sourcemap:35   ERR TreeError [DebugRepl] Tree input not set: Error: TreeError [DebugRepl] Tree input not set
    at lf.C (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:415:28817)
    at lf.updateChildren (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:415:28724)
    at oee.value (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20…20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2038:35810)
    at x.B (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.C (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:818)
    at x.fire (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:1036)
    at Rbe.setVisible (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:518:2801)
    at vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:780:11845
    at Array.map (<anonymous>)
    at jh.setVisible (vscode-file://vscode-app/c:/Users/josue/AppData/Local/Programs/Microsoft%20…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:780:11836)
```
﻿

**Comment by cmawhorter** [comment]
I can confirm switching to release version fixed the issue for me -- thanks @DemonMartin! I switched to pre-release to get some feature at some point and I'd forgotten. 

@mjbvz FWIW: To me, it looked like 0.23.2024102903 was the latest pre-release version available in vscode extensions.
