### ISSUE TITLE
Since new version it stops working on vscode dev tunnels.

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-copilot-release#3411]
Since new version it stops working on vscode dev tunnels.

- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Enter to a dev tunnel
2. Install github copilot chat
3. Not work github copilot chat

Logs of Github Copilot on dev tunnel

```
2024-12-19 18:30:56.014 [info] Can't use the Electron fetcher in this environment.
2024-12-19 18:30:56.014 [info] Using the Node fetch fetcher.
2024-12-19 18:30:56.014 [info] Initializing Git extension service.
2024-12-19 18:30:56.014 [info] Successfully activated the vscode.git extension.
2024-12-19 18:30:56.014 [info] Enablement state of the vscode.git extension: true.
2024-12-19 18:30:56.014 [info] Successfully registered Git commit message provider.
2024-12-19 18:30:58.586 [info] Logged in as aleleba
2024-12-19 18:31:10.324 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023): Failed to get copilot token
2024-12-19 18:31:10.324 [error] GitHub Copilot could not connect to server. Extension activation failed: "fetch failed"
2024-12-19 18:31:10.324 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-19 18:31:10.324 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-19 18:31:10.324 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-19 18:31:10.324 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-19 18:31:10.324 [info] activationBlocker from 'languageModelAccess' took for 10068ms
```
@digitarald any idea? It start failing since yesterday, thank you in advance

**Comment by lramos15** [comment]
Can you do F1 -> GitHub Copilot Chat diagnostics

**Comment by aleleba** [comment]
This still an issue, I use the paid version, please take it as an priority, thank you in advance.

**Comment by aleleba** [comment]
The information was provided

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/fbee0b72-1e32-4896-96da-c91ac2604ca6" />

```
## GitHub Copilot Chat

- Extension Version: 0.23.2 (prod)
- VS Code: vscode/1.96.2
- OS: Linux
- Remote Name: tunnel

## Network

User Settings:
```json
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 140.82.112.5 (4001 ms)
- DNS ipv6 Lookup: Error (4003 ms): getaddrinfo ENOTFOUND api.github.com
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: HTTP 200 (4236 ms)
- Node.js fetch (configured): HTTP 200 (4308 ms)
- Helix fetch: HTTP 200 (4492 ms)

Connecting to https://api.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.112.22 (4083 ms)
- DNS ipv6 Lookup: Error (4003 ms): getaddrinfo ENOTFOUND api.githubcopilot.com
- Proxy URL: None (1 ms)
- Electron fetch: Unavailable
- Node.js https: HTTP 200 (4242 ms)
- Node.js fetch (configured): HTTP 200 (4267 ms)
- Helix fetch: HTTP 200 (4271 ms)

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
```

**Comment by aleleba** [comment]
I have provided the 8nformation needed, please let me know if you found the issue, thank you in advance 😁

**Comment by lastboy1228** [comment]
wsl can not use node-fetch, you should add this settings:
```
    "github.copilot.advanced": {
        "debug.useElectronFetcher": false,
        "debug.useNodeFetcher": true,
        "debug.useNodeFetchFetcher": false,
    },
```

**Comment by aleleba** [comment]
I am not using wsl, I am running it on a container on a linux OS.

**Comment by aleleba** [comment]
I am using vscode.dev and still failing:

```
2024-12-20 14:39:39.466 [info] Can't use the Electron fetcher in this environment.
2024-12-20 14:39:39.466 [info] Using the Node fetch fetcher.
2024-12-20 14:39:39.466 [info] Initializing Git extension service.
2024-12-20 14:39:39.466 [info] Successfully activated the vscode.git extension.
2024-12-20 14:39:39.466 [info] Enablement state of the vscode.git extension: true.
2024-12-20 14:39:39.466 [info] Successfully registered Git commit message provider.
2024-12-20 14:39:44.423 [error] Timed out waiting for authentication provider to register: Failed to get copilot token
2024-12-20 14:39:44.423 [error] GitHub Copilot could not connect to server. Extension activation failed: "Timed out waiting for authentication provider to register"
2024-12-20 14:39:44.423 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-20 14:39:44.423 [error] Timed out waiting for authentication provider to register
2024-12-20 14:39:44.423 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-20 14:39:44.423 [error] Timed out waiting for authentication provider to register
2024-12-20 14:39:44.423 [error] Error getting a session: Timed out waiting for authentication provider to register
2024-12-20 14:39:44.423 [error] Error getting a session: Timed out waiting for authentication provider to register
2024-12-20 14:39:44.423 [info] activationBlocker from 'languageModelAccess' took for 1367ms
2024-12-20 14:40:21.453 [info] Logged in as aleleba
2024-12-20 14:40:32.366 [info] copilot token chat_enabled: undefined, sku: 
2024-12-20 14:40:33.464 [info] Logged in as aleleba
2024-12-20 14:40:43.850 [error] GitHub Copilot could not connect to server. Extension activation failed: "fetch failed"
2024-12-20 14:40:43.850 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-20 14:40:43.850 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-20 14:40:43.850 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-20 14:40:43.850 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/aleleba/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-20 14:40:50.563 [info] Logged in as aleleba
```

**Comment by aleleba** [comment]
Any update?, thank you in advance

**Comment by aleleba** [comment]
Do you find a fix @chrmarti @digitarald  ?

**Comment by aleleba** [comment]
Do you need more information?

**Comment by aleleba** [comment]
Any update @digitarald @chrmarti ?

**Comment by chrmarti** [comment]
@aleleba Could you try adding the following to your user settings JSON (`F1` > `Preference: Open User Settings (JSON)`):
```json
"github.copilot.advanced.debug.useNodeFetchFetcher": false
```
The restart VS Code and retry with the tunnel.

**Comment by githubbar** [comment]
seems to have fixed it for me.
- Alex Leykin

**Comment by aleleba** [comment]
I tried and still failing, Im using vscodedev:

![Screenshot_20241222_110546_Chrome.jpg](https://github.com/user-attachments/assets/f19c09af-ae92-45e7-b531-1ef2cb507c84)

**Comment by aleleba** [comment]
For give context I run vscode tunnel on a container, since I delete container and rerun it and change the configuration, it start working again. I think you can close the issue.


![Screenshot_20241222_232715_Chrome.jpg](https://github.com/user-attachments/assets/44b0809b-0eb2-4fca-ab0c-9874b73a7728)
