### ISSUE TITLE
request failed 28354fe3-28d5-4dba-b1fc-32de61d5a816

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-copilot-release#3427]
Type: <b>Bug</b>

https://github.com/chrisdias/vscode-settingsview repo
opened in insiders
prompt: the default theme is not picked up correct on startup. it always defaults to "abyss" regardless of what the theme actually is
result was the "Sorry your request failed..."

Extension version: 0.24.2024121901
VS Code version: Code - Insiders 1.97.0-insider (225d1ca870a984369bde1a7fcd75f863fc69fee1, 2024-12-19T12:16:05.024Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 3072)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (7.21GB free)|
|Process Argv|--crash-reporter-id 26ae5cbd-0f12-42b8-90be-67559bef8fef|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-24.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 0)|
|Memory (System)|15.44GB (10.18GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-24.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 0)|
|Memory (System)|15.44GB (10.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupytercf:31046870
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
parsetypescript:31116713
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31183120
5b1c1929:31184661
6074i472:31201624

```

</details>

**Comment by rebornix** [comment]
@chrisdias Can you share logs from Output Channel "GitHub Copilot Chat" to see if there is anything suspicious?

**Comment by rebornix** [comment]
Were you using Claude?

**Comment by chrisdias** [comment]
yes i was

**Comment by chrisdias** [comment]
```
2024-12-19 16:02:14.146 [info] Can't use the Electron fetcher in this environment.
2024-12-19 16:02:14.146 [info] Using the Node fetch fetcher.
2024-12-19 16:02:14.146 [info] Initializing Git extension service.
2024-12-19 16:02:14.146 [info] Successfully activated the vscode.git extension.
2024-12-19 16:02:14.146 [info] Enablement state of the vscode.git extension: true.
2024-12-19 16:02:14.146 [info] Successfully registered Git commit message provider.
2024-12-19 16:02:14.620 [info] Logged in as chrisdias
2024-12-19 16:02:15.731 [info] Got Copilot token for chrisdias
2024-12-19 16:02:16.055 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 16:02:16.055 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-19 16:02:16.071 [info] Registering default platform agent...
2024-12-19 16:02:16.072 [info] [🤫] Using inline edit provider: FineTunedModelInlineEditProvider
2024-12-19 16:02:16.175 [info] TypeScript server plugin installed.
2024-12-19 16:02:16.640 [info] Fetched model metadata in 895ms 67dd51c1-cd07-4365-b000-151c8bb15732
2024-12-19 16:02:16.647 [info] activationBlocker from 'languageModelAccess' took for 2325ms
2024-12-19 16:02:17.178 [info] Fetched content exclusion rules in 1124ms
2024-12-19 16:17:18.388 [info] Fetched model metadata in 657ms 86dca2b9-795e-4b29-a632-58dde4df8f3d
2024-12-19 16:30:44.618 [info] Logged in as chrisdias
2024-12-19 16:30:46.019 [info] Got Copilot token for chrisdias
2024-12-19 16:38:44.574 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 16:38:45.151 [info] Fetched model metadata in 240433ms 7724b721-b4a7-486e-8850-6a74f3e87e66
2024-12-19 16:57:54.968 [info] Logged in as chrisdias
2024-12-19 16:57:56.344 [info] Got Copilot token for chrisdias
2024-12-19 16:57:56.632 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 16:57:56.998 [info] Fetched model metadata in 647ms 0f5ea036-6e06-4361-a96f-7defd146988e
2024-12-19 16:59:30.868 [info] [🤫] Using NES fine-tuned model: url: 'https://copilot-proxy.githubusercontent.com/v1/engines/copilot-chat-fine-raw/completions', apiKey: 'ti...'
2024-12-19 16:59:30.890 [info] [🤫] TypeScript Copilot context: Completion Context: method, stats: {"unknown":0,"blueprints":0,"signatures":0,"superClasses":0,"generalScopes":0} in 207ms. Timed out.
2024-12-19 17:12:57.884 [info] Fetched model metadata in 673ms 6746a36e-a116-4e04-85c9-0f6e59b82210
2024-12-19 17:22:57.277 [info] Logged in as chrisdias
2024-12-19 17:22:58.747 [info] Got Copilot token for chrisdias
2024-12-19 17:22:58.969 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 17:22:59.746 [info] Fetched model metadata in 671ms 50821670-3c95-4ec2-9282-a9526f5b9422
2024-12-19 17:33:22.840 [info] Fetched model metadata in 849ms 4b5150e1-3a30-4a0c-9efe-66806d897206
2024-12-19 17:33:23.055 [info] [🤫] Latest entry: ccreq:latestrequest.copilotmd
2024-12-19 17:36:16.183 [info] request done: requestId: [4ebac532-5c37-45b1-a43c-d97812c160a4] model deployment ID: []
2024-12-19 17:36:16.197 [error] Error: Response stream has been closed
    at r._push (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:464:647)
    at r.push (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:464:1067)
    at r._push (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:464:647)
    at r.markdown (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:464:728)
    at Fde._emitMarkdownLine (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:1089:4287)
    at Fde._processLine (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:1089:6719)
    at Fde.flush (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:1089:6785)
    at ly.finish (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:1089:4901)
    at Object.processResponse (/home/chris/.vscode-server-insiders/extensions/github.copilot-chat-0.24.2024121901/dist/extension.js:1089:19903)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-19 17:36:16.374 [info] [🤫] ccreq:da46f4bc.copilotmd | canceled | claude-3.5-sonnet | 173190ms | [editingSession/edit]
2024-12-19 17:36:58.336 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:36:58.339 [info] request done: requestId: [4c28f810-9c8b-45cc-a5b1-360f5c59dd13] model deployment ID: []
2024-12-19 17:36:58.694 [info] [🤫] ccreq:aa139874.copilotmd | success | claude-3.5-sonnet | 36100ms | [editingSession/edit]
2024-12-19 17:37:38.698 [info] srequest done: requestId: [a72b472f-810c-4087-9cbe-8578c4e1467c]
2024-12-19 17:37:38.698 [info] [🤫] srequest | success | SD | 40642ms | [codeMapper]
2024-12-19 17:37:38.898 [info] [🤫] ccreq:cb8305ad.copilotmd | success | undefined | 40640ms | [editingSession/speculate]
2024-12-19 17:39:21.751 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:39:21.753 [info] request done: requestId: [78bf6cf2-4d6a-4530-af96-9d62f92decbc] model deployment ID: []
2024-12-19 17:39:21.855 [info] [🤫] ccreq:b6439fc8.copilotmd | success | claude-3.5-sonnet | 18668ms | [editingSession/edit]
2024-12-19 17:39:33.836 [info] srequest done: requestId: [a73a89ba-58f9-4aeb-8057-8e371921eaa4]
2024-12-19 17:39:33.836 [info] [🤫] srequest | success | SD | 12111ms | [codeMapper]
2024-12-19 17:39:34.056 [info] [🤫] ccreq:e77634b6.copilotmd | success | undefined | 12109ms | [editingSession/speculate]
2024-12-19 17:42:41.883 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:42:41.885 [info] request done: requestId: [cae04441-4f93-46f9-8a87-87594b447b37] model deployment ID: []
2024-12-19 17:42:42.004 [info] [🤫] ccreq:10792fb6.copilotmd | success | claude-3.5-sonnet | 32365ms | [editingSession/edit]
2024-12-19 17:43:00.518 [info] srequest done: requestId: [c5e18d24-64c7-4338-895c-67e8cc2a9761]
2024-12-19 17:43:00.518 [info] [🤫] srequest | success | SD | 20174ms | [codeMapper]
2024-12-19 17:43:00.664 [info] [🤫] ccreq:cb6a1c37.copilotmd | success | undefined | 20174ms | [editingSession/speculate]
2024-12-19 17:44:07.250 [info] Fetched model metadata in 516ms e246186d-b3bb-4c99-b32a-5e39b08d6b65
2024-12-19 17:44:29.734 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:44:29.735 [info] request done: requestId: [25ae31b9-9bc4-4264-b313-26c98a8e4373] model deployment ID: []
2024-12-19 17:44:29.843 [info] [🤫] ccreq:70352fee.copilotmd | success | claude-3.5-sonnet | 22437ms | [editingSession/edit]
2024-12-19 17:44:47.662 [info] srequest done: requestId: [775dff70-3bb0-4361-9d4f-dc7472dfe257]
2024-12-19 17:44:47.662 [info] [🤫] srequest | success | SD | 18882ms | [codeMapper]
2024-12-19 17:44:47.865 [info] [🤫] ccreq:7d0fff9a.copilotmd | success | undefined | 18881ms | [editingSession/speculate]
2024-12-19 17:46:09.447 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:46:09.449 [info] request done: requestId: [bcc1c524-7bff-4930-a685-4f7ce8d4d305] model deployment ID: []
2024-12-19 17:46:09.563 [info] [🤫] ccreq:e60c01df.copilotmd | success | claude-3.5-sonnet | 18938ms | [editingSession/edit]
2024-12-19 17:46:16.124 [info] srequest done: requestId: [1a220687-d1de-4f13-86bc-1ff9c205adf2]
2024-12-19 17:46:16.124 [info] [🤫] srequest | success | SD | 6852ms | [codeMapper]
2024-12-19 17:46:16.278 [info] [🤫] ccreq:2308539f.copilotmd | success | undefined | 6851ms | [editingSession/speculate]
2024-12-19 17:47:21.468 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:47:21.469 [info] request done: requestId: [c2a936ba-4023-4bf5-9245-dfd0739674e4] model deployment ID: []
2024-12-19 17:47:21.564 [info] [🤫] ccreq:66ccc66d.copilotmd | success | claude-3.5-sonnet | 22288ms | [editingSession/edit]
2024-12-19 17:47:55.267 [info] srequest done: requestId: [d27b6cda-d741-4ba5-b908-0043baa75c7d]
2024-12-19 17:47:55.267 [info] [🤫] srequest | success | SD | 33854ms | [codeMapper]
2024-12-19 17:47:55.439 [info] [🤫] ccreq:0bc69994.copilotmd | success | undefined | 33853ms | [editingSession/speculate]
2024-12-19 17:48:04.018 [info] Logged in as chrisdias
2024-12-19 17:48:05.289 [info] Got Copilot token for chrisdias
2024-12-19 17:48:05.461 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 17:49:41.193 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:49:41.194 [info] request done: requestId: [d1a0f8c2-f374-45c2-b1cd-c6e6960fe922] model deployment ID: []
2024-12-19 17:49:41.306 [info] [🤫] ccreq:350754da.copilotmd | success | claude-3.5-sonnet | 23057ms | [editingSession/edit]
2024-12-19 17:49:56.764 [info] srequest done: requestId: [b270712c-b453-48f1-8737-caf60597c190]
2024-12-19 17:49:56.764 [info] [🤫] srequest | success | SD | 15632ms | [codeMapper]
2024-12-19 17:49:56.876 [info] [🤫] ccreq:9e088b3b.copilotmd | success | undefined | 15631ms | [editingSession/speculate]
2024-12-19 17:51:32.037 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:51:32.038 [info] request done: requestId: [b213f044-7fed-43d4-b6bc-a2cb239c4aec] model deployment ID: []
2024-12-19 17:51:32.143 [info] [🤫] ccreq:40ee4086.copilotmd | success | claude-3.5-sonnet | 19522ms | [editingSession/edit]
2024-12-19 17:52:03.113 [info] srequest done: requestId: [19e933d6-6529-4ed0-b8a7-71149c31d581]
2024-12-19 17:52:03.114 [info] [🤫] srequest | success | SD | 31555ms | [codeMapper]
2024-12-19 17:52:03.336 [info] [🤫] ccreq:55806747.copilotmd | success | undefined | 31554ms | [editingSession/speculate]
2024-12-19 17:53:29.351 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:53:29.352 [info] request done: requestId: [af080ab1-1735-49e6-acea-4897dccd4d86] model deployment ID: []
2024-12-19 17:53:29.421 [info] [🤫] ccreq:2bf54da3.copilotmd | success | claude-3.5-sonnet | 14319ms | [editingSession/edit]
2024-12-19 17:53:44.378 [info] srequest done: requestId: [e3007c03-5a7a-4417-bf7e-ae709c258085]
2024-12-19 17:53:44.378 [info] [🤫] srequest | success | SD | 15081ms | [codeMapper]
2024-12-19 17:53:44.580 [info] [🤫] ccreq:1bce5729.copilotmd | success | undefined | 15080ms | [editingSession/speculate]
2024-12-19 17:54:52.865 [info] Fetched model metadata in 643ms 4c8011b8-03bb-4cc3-864a-b07f5bfe5de0
2024-12-19 17:55:44.256 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:55:44.259 [info] request done: requestId: [5fbbc399-699c-4d93-b27a-837a51065e7c] model deployment ID: []
2024-12-19 17:55:44.374 [info] [🤫] ccreq:608f569a.copilotmd | success | claude-3.5-sonnet | 51360ms | [editingSession/edit]
2024-12-19 17:56:49.592 [info] srequest done: requestId: [f3c05688-f969-458b-8afd-22429581b475]
2024-12-19 17:56:49.592 [info] [🤫] srequest | success | SD | 66040ms | [codeMapper]
2024-12-19 17:56:49.767 [info] [🤫] ccreq:edc6b89f.copilotmd | success | undefined | 66039ms | [editingSession/speculate]
2024-12-19 17:57:32.129 [info] Fetched content exclusion rules in 633ms
2024-12-19 17:57:32.620 [info] Fetched content exclusion rules in 491ms
2024-12-19 17:59:12.860 [info] message 0 returned. finish reason: [stop]
2024-12-19 17:59:12.863 [info] request done: requestId: [9dbe80b7-e33e-41b3-853e-25667c64d23b] model deployment ID: []
2024-12-19 17:59:12.981 [info] [🤫] ccreq:c2af5331.copilotmd | success | claude-3.5-sonnet | 34737ms | [editingSession/edit]
2024-12-19 17:59:46.632 [info] srequest done: requestId: [cc6a2b9c-822e-4979-a866-67a6b23aa4d9]
2024-12-19 17:59:46.632 [info] [🤫] srequest | success | SD | 34427ms | [codeMapper]
2024-12-19 17:59:46.777 [info] [🤫] ccreq:b654e565.copilotmd | success | undefined | 34427ms | [editingSession/speculate]
2024-12-19 18:02:35.706 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:02:35.707 [info] request done: requestId: [8513be00-b1d7-4c61-ad1d-eba507393f46] model deployment ID: []
2024-12-19 18:02:35.813 [info] [🤫] ccreq:de0a9bb4.copilotmd | success | claude-3.5-sonnet | 18039ms | [editingSession/edit]
2024-12-19 18:02:39.691 [info] srequest done: requestId: [3a297f7b-181b-484b-997f-15c4b26b3489]
2024-12-19 18:02:39.691 [info] [🤫] srequest | success | SD | 4055ms | [codeMapper]
2024-12-19 18:02:39.839 [info] [🤫] ccreq:183f470c.copilotmd | success | undefined | 4055ms | [editingSession/speculate]
2024-12-19 18:09:37.139 [info] Fetched model metadata in 693ms c0f12708-b782-4fb7-b9fb-5cf772cb1133
2024-12-19 18:09:55.674 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:09:55.675 [info] request done: requestId: [52ee3706-ab25-46e3-b67c-70e45613e761] model deployment ID: []
2024-12-19 18:09:55.780 [info] [🤫] ccreq:0927f690.copilotmd | success | claude-3.5-sonnet | 18489ms | [editingSession/edit]
2024-12-19 18:10:04.728 [info] srequest done: requestId: [d32cd2e3-011e-4593-8b5f-d7410887797b]
2024-12-19 18:10:04.729 [info] [🤫] srequest | success | SD | 9075ms | [codeMapper]
2024-12-19 18:10:04.880 [info] [🤫] ccreq:67a3cbd6.copilotmd | success | undefined | 9074ms | [editingSession/speculate]
2024-12-19 18:11:12.301 [info] srequest done: requestId: [cdc065d0-92e1-45c5-b6a9-3b049890a946]
2024-12-19 18:11:12.301 [info] [🤫] srequest | success | SD | 5249ms | [codeMapper]
2024-12-19 18:11:12.385 [info] [🤫] ccreq:1b46dd13.copilotmd | success | undefined | 5248ms | [editingSession/speculate]
2024-12-19 18:11:15.902 [info] srequest done: requestId: [0b45fd55-2564-4729-8005-5cc2b857236e]
2024-12-19 18:11:15.902 [info] [🤫] srequest | success | SD | 3662ms | [codeMapper]
2024-12-19 18:11:16.037 [info] [🤫] ccreq:fb55e025.copilotmd | success | undefined | 3661ms | [editingSession/speculate]
2024-12-19 18:11:18.534 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:11:18.535 [info] request done: requestId: [805e3d6e-ff06-4ae7-940f-c3f82d7ad2eb] model deployment ID: []
2024-12-19 18:11:18.670 [info] [🤫] ccreq:b433a060.copilotmd | success | claude-3.5-sonnet | 31418ms | [editingSession/edit]
2024-12-19 18:11:19.045 [info] srequest done: requestId: [0421d92a-d365-44cd-9f69-60e0c1090b10]
2024-12-19 18:11:19.045 [info] [🤫] srequest | success | SD | 3000ms | [codeMapper]
2024-12-19 18:11:19.148 [info] [🤫] ccreq:9ec04c4a.copilotmd | success | undefined | 3000ms | [editingSession/speculate]
2024-12-19 18:13:28.352 [info] Logged in as chrisdias
2024-12-19 18:13:29.628 [info] Got Copilot token for chrisdias
2024-12-19 18:13:29.851 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 18:14:15.288 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:14:15.291 [info] request done: requestId: [4b91100e-cec8-404f-be19-506103b20f84] model deployment ID: []
2024-12-19 18:14:15.395 [info] [🤫] ccreq:67d0458d.copilotmd | success | claude-3.5-sonnet | 24063ms | [editingSession/edit]
2024-12-19 18:14:29.962 [info] srequest done: requestId: [39fcb119-98c8-447f-96ab-15290d7bd508]
2024-12-19 18:14:29.962 [info] [🤫] srequest | success | SD | 15575ms | [codeMapper]
2024-12-19 18:14:30.159 [info] [🤫] ccreq:f50bbb9a.copilotmd | success | undefined | 15575ms | [editingSession/speculate]
2024-12-19 18:17:05.553 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:17:05.555 [info] request done: requestId: [5f06295e-8af2-4569-94dd-bdc9a2a15b93] model deployment ID: []
2024-12-19 18:17:05.612 [info] [🤫] ccreq:679a6054.copilotmd | success | claude-3.5-sonnet | 32858ms | [editingSession/edit]
2024-12-19 18:17:14.906 [info] srequest done: requestId: [9a3385f2-d3d3-45d7-ba7f-d7baa345c3e8]
2024-12-19 18:17:14.906 [info] [🤫] srequest | success | SD | 9415ms | [codeMapper]
2024-12-19 18:17:15.121 [info] [🤫] ccreq:90bcb069.copilotmd | success | undefined | 9415ms | [editingSession/speculate]
2024-12-19 18:17:57.694 [info] [🤫] Using NES fine-tuned model (endpoint change): old: url: 'https://copilot-proxy.githubusercontent.com/v1/engines/copilot-chat-fine-raw/completions', apiKey: 'ti...', new: url: 'https://copilot-proxy.githubusercontent.com/v1/engines/copilot-chat-fine-raw/completions', apiKey: 'ti...'
2024-12-19 18:17:58.342 [info] [🤫] ccreq:9f28be9e.copilotmd | markdown
2024-12-19 18:18:02.692 [info] [🤫] ccreq:694ec55d.copilotmd | markdown
2024-12-19 18:18:16.341 [info] [🤫] ccreq:7427ca7c.copilotmd | markdown
2024-12-19 18:18:19.451 [info] [🤫] ccreq:1c81e764.copilotmd | markdown
2024-12-19 18:18:40.916 [info] [🤫] ccreq:d87eee9c.copilotmd | markdown
2024-12-19 18:21:56.640 [info] [🤫] ccreq:eb4df5cc.copilotmd | markdown
2024-12-19 18:22:01.234 [info] [🤫] ccreq:0c9cebde.copilotmd | markdown
2024-12-19 18:22:02.718 [info] [🤫] ccreq:b9f7da9a.copilotmd | markdown
2024-12-19 18:22:07.642 [info] [🤫] TypeScript Copilot context: Completion Context: method, stats: {"unknown":0,"blueprints":0,"signatures":1,"superClasses":0,"generalScopes":0} in 17ms.
2024-12-19 18:22:09.422 [info] [🤫] ccreq:aee48211.copilotmd | markdown
2024-12-19 18:22:11.177 [info] [🤫] ccreq:b3e736aa.copilotmd | markdown
2024-12-19 18:22:12.058 [info] [🤫] ccreq:5ad3a627.copilotmd | markdown
2024-12-19 18:24:23.424 [info] Fetched content exclusion rules in 886ms
2024-12-19 18:28:47.494 [info] Fetched model metadata in 694ms 933c98a7-439a-4180-90e0-cb764c76d5e5
2024-12-19 18:32:07.005 [info] [🤫] ccreq:000f3a79.copilotmd | markdown
2024-12-19 18:33:09.375 [info] [🤫] ccreq:b9460228.copilotmd | markdown
2024-12-19 18:33:15.603 [info] message 0 returned. finish reason: [stop]
2024-12-19 18:33:15.605 [info] request done: requestId: [0f946d65-be5c-42dd-9be7-70b73c68f961] model deployment ID: []
2024-12-19 18:33:15.695 [info] [🤫] ccreq:eda72201.copilotmd | success | gpt-4o | 1657ms | [debugCommandIdentifier]
2024-12-19 18:36:03.748 [info] [🤫] TypeScript Copilot context: Completion Context: none, stats: {"unknown":0,"blueprints":0,"signatures":0,"superClasses":0,"generalScopes":0} in 26ms.
2024-12-19 18:36:03.932 [info] [🤫] TypeScript Copilot context: Completion Context: none, stats: {"unknown":0,"blueprints":0,"signatures":0,"superClasses":0,"generalScopes":0} in 21ms.
2024-12-19 18:36:04.261 [info] [🤫] TypeScript Copilot context: Completion Context: none, stats: {"unknown":0,"blueprints":0,"signatures":0,"superClasses":0,"generalScopes":0} in 9ms.
2024-12-19 18:36:04.961 [info] [🤫] ccreq:04fb2444.copilotmd | markdown
2024-12-19 18:38:58.051 [info] Logged in as chrisdias
2024-12-19 18:38:59.485 [info] Got Copilot token for chrisdias
2024-12-19 18:38:59.699 [info] copilot token chat_enabled: true, sku: copilot_enterprise_seat
2024-12-19 18:39:00.493 [info] Fetched model metadata in 684ms 5023dcbc-6f71-4c79-b706-606c38b15e70
2024-12-19 18:44:25.336 [info] request done: requestId: [28354fe3-28d5-4dba-b1fc-32de61d5a816] model deployment ID: []
2024-12-19 18:44:25.351 [error] TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:11020:53)
    at Fetch.emit (node:events:518:28)
    at Fetch.terminate (node:internal/deps/undici/undici:10178:14)
    at Object.onError (node:internal/deps/undici/undici:11141:38)
    at Request.onError (/home/chris/.vscode-server-insiders/bin/225d1ca870a984369bde1a7fcd75f863fc69fee1/node_modules/undici/lib/core/request.js:299:27)
    at Object.errorRequest (/home/chris/.vscode-server-insiders/bin/225d1ca870a984369bde1a7fcd75f863fc69fee1/node_modules/undici/lib/core/util.js:638:13)
    at TLSSocket.<anonymous> (/home/chris/.vscode-server-insiders/bin/225d1ca870a984369bde1a7fcd75f863fc69fee1/node_modules/undici/lib/dispatcher/client-h1.js:736:12)
    at TLSSocket.emit (node:events:530:35)
    at node:net:343:12
    at TCP.done (node:_tls_wrap:648:7): Error on conversation request
2024-12-19 18:44:25.440 [info] [🤫] ccreq:c5331573.copilotmd | failed | claude-3.5-sonnet | 23042ms | [editingSession/edit]
2024-12-19 18:44:30.539 [info] srequest done: requestId: [b9479778-b15a-4cb3-ba8a-14fc342d108a]
2024-12-19 18:44:30.539 [info] [🤫] srequest | success | SD | 5171ms | [codeMapper]
2024-12-19 18:44:30.722 [info] [🤫] ccreq:e4f7a2f5.copilotmd | success | undefined | 5171ms | [editingSession/speculate]
2024-12-19 18:54:19.411 [info] Fetched model metadata in 627ms 2a9c08ed-a1d3-474f-b3e5-19dc1c215709
```

**Comment by chrisdias** [comment]
near the top of the logs, you see `2024-12-19 17:36:16.197 [error] Error: Response stream has been closed` that was when I cancelled a request that seemed to be hung.

**Comment by lramos15** [comment]
Claude is currently known to have some issues at the moment, hence the preview designation.
