### ISSUE TITLE
Cannot sign in to VS Code (opened a project in Ubuntu WSL)

### ISSUE THREAD

**Issue by Kenya-West** [microsoft/vscode-copilot-release#3554]
Type: <b>Bug</b>

1. Open a repository inside Ubuntu 24.04 WSL while having VS Code on Windows 11 installed
2. Try to sign in to Copilot.

It does not sign in despite I have already signed in to GitHub account and have paid (student) tire:

![Image](https://github.com/user-attachments/assets/5dd58548-fa0e-41c6-b79a-aa751814b7e5)

**Additional logs** are:

```log
2024-12-25 17:28:43.959 [info] Can't use the Electron fetcher in this environment.
2024-12-25 17:28:43.959 [info] Using the Node fetch fetcher.
2024-12-25 17:28:43.959 [info] Initializing Git extension service.
2024-12-25 17:28:43.959 [info] Successfully activated the vscode.git extension.
2024-12-25 17:28:43.959 [info] Enablement state of the vscode.git extension: true.
2024-12-25 17:28:43.959 [info] Successfully registered Git commit message provider.
2024-12-25 17:28:44.507 [info] Logged in as Kenya-West
2024-12-25 17:28:55.334 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023): Failed to get copilot token
2024-12-25 17:28:55.334 [error] GitHub Copilot could not connect to server. Extension activation failed: "fetch failed"
2024-12-25 17:28:55.334 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-25 17:28:55.334 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-25 17:28:55.334 [warning] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-12-25 17:28:55.334 [error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ek._fetch (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:763:5811)
    at B0.fetchCopilotToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:23966)
    at B0.authFromGitHubToken (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:334:21634)
    at B0._auth (/home/kenyawest/.vscode-server/extensions/github.copilot-chat-0.23.2/dist/extension.js:446:3023)
2024-12-25 17:28:55.334 [info] activationBlocker from 'languageModelAccess' took for 6408ms
2024-12-25 17:29:37.689 [info] Logged in as Kenya-West
2024-12-25 17:33:17.753 [info] Logged in as Kenya-West
```

Extension version: 0.23.2
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details><summary>Prompt Details</summary>
<pre>
Info: Can't use the Electron fetcher in this environment.
Info: Using the Node fetch fetcher.
Info: Initializing Git extension service.
Info: Successfully activated the vscode.git extension.
Info: Enablement state of the vscode.git extension: true.
Info: Successfully registered Git commit message provider.
Info: Logged in as Kenya-West
Debug: [context keys] Updating context keys.
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.92GB (36.24GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/kenyawest/ansible-my --crash-reporter-id 12f06456-3cad-4606-a49b-9d4b361a94d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 0)|
|Memory (System)|7.76GB (5.66GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by Kenya-West** [comment]
Looks like it was server side issue. After some time, it fetched the auth token:

```log
2024-12-25 17:56:53.156 [info] Got Copilot token for Kenya-West
2024-12-25 17:56:53.364 [info] copilot token chat_enabled: true, sku: free_educational
2024-12-25 17:56:53.364 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-12-25 17:56:53.365 [info] Registering default platform agent...
2024-12-25 17:56:59.073 [info] Fetched model metadata in 5911ms 94e9ec12-088d-4cc5-8d1e-f6777a04208c
2024-12-25 18:13:42.899 [info] Fetched model metadata in 10262ms e065f56d-ae52-4cd3-b526-3433292c79b0
2024-12-25 18:24:28.341 [info] Logged in as Kenya-West
```
