### ISSUE TITLE
Autocompletion doesn't work for Python files on a Linux remote server

### ISSUE THREAD

**Issue by tianzeliu** [microsoft/vscode-copilot-release#3581]
Copilot throws an out-of-memory error when I try to edit a Python file on a Linux remote server. However, it works fine for all other file types. The problem only arose today.

- Copilot Chat Extension Version: 0.23.2
- VS Code Version: 1.96.2
- OS Version: Red Hat Enterprise Linux 9.5 (Plow)
- Logs: 

```
2024-12-27 05:40:02.779 [error] [ghostText] provideInlineCompletionItems: RangeError: WebAssembly.Memory(): could not allocate memory
    at /fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/node_modules/web-tree-sitter/tree-sitter.js:1:5037
    at new Promise (<anonymous>)
    at Function.init (/fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/node_modules/web-tree-sitter/tree-sitter.js:1:393)
    at parseTreeSitter (/fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/prompt/src/parse.ts:91:18)
    at po.isEmptyBlockStart (/fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/prompt/src/parseBlock.ts:327:28)
    at Object.isEmptyBlockStart (/fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/prompt/src/parseBlock.ts:878:39)
    at MessagePort.<anonymous> (/fp/homes01/u01/ec-tianzel/.vscode-server/extensions/github.copilot-1.254.0/prompt/src/worker.js:17:35)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: undefined
}
```

**Comment by tianzeliu** [comment]
Any update on this?

**Comment by roblourens** [comment]
Is it just this particular file or all python files? Is it a large file?

**Comment by tianzeliu** [comment]
This happens to all my Python files, and none of them are exceedingly large.

**Comment by roblourens** [comment]
I noticed that this stack is in the Copilot extension, not Copilot Chat. Could you open a topic on https://github.com/community/community/discussions/categories/copilot with the stack? Thanks
