### ISSUE TITLE
Extension activation failed: "r.chat.registerVariable is not a function"

### ISSUE THREAD

**Issue by yoieh** [microsoft/vscode-copilot-release#367]
- VS Code Version: `1.82.0-insider`
- OS Version:
 
```bash
> lsb_release -a 
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.0.0
Codename:       Uranos
```

```bash
> uname -r
Kernal: 5.15.125-1-MANJARO
```

- Logs:
```
2023-08-17T13:02:36.236Z [INFO] [auth] Logged in as yoieh
2023-08-17T13:02:40.990Z [INFO] [chat] copilot token chat_enabled: true
2023-08-17T13:02:40.995Z [ERROR] [extension] {"constructionStack":["    at new t.ServicesAccessor (/home/yoieh/.vscode-insiders/extensions/github.copilot-chat-0.7.2023081701/dist/extension.js:8:993630)","    at t.createProductionContext (/home/yoieh/.vscode-insiders/extensions/github.copilot-chat-0.7.2023081701/dist/extension.js:8:761927)","    at G (/home/yoieh/.vscode-insiders/extensions/github.copilot-chat-0.7.2023081701/dist/extension.js:8:1368854)","    at e.activate (/home/yoieh/.vscode-insiders/extensions/github.copilot-chat-0.7.2023081701/dist/extension.js:8:1371590)","    at Function.eb (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:13084)","    at Function.db (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:12802)","    at /opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10842","    at y.n (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6206)","    at y.m (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6169)","    at y.l (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:5626)"],"instances":{},"isSealed":false},GitHub Copilot could not connect to server. Extension activation failed: "r.chat.registerVariable is not a function"
```

Steps to Reproduce:

1. Have Pre-release of GitHub Copilot (v1.103.340) and Pre-release of GitHub Copilot Chat (v0.7.2023081701)
2. Start vs code insider.
3. Getting the error and cant open the chat as in side bar.

If i use a switch to using a Release version of GitHub Copilot Chat (v0.6.0) it works fine.

**Comment by ulugbekna** [comment]
Hi @yoieh ,

Thanks for filing the issue! 

Are you on the latest Insiders? If not, could you please update and let us know if you still see this error?

**Comment by yoieh** [comment]
@ulugbekna 

I got the version from above from:
```bash
> code-insiders -v
1.82.0-insider
2d9cc42045edf3458acbddf3d645bba993f82696
x64
```


But here you have a copy from  "Help > About"
```
Version: 1.82.0-insider
Commit: 2d9cc42045edf3458acbddf3d645bba993f82696
Date: 2023-08-14T05:33:33.104Z
Electron: 25.4.0
ElectronBuildId: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Linux x64 5.15.125-1-MANJARO
```

**Comment by ulugbekna** [comment]
You're on an old version. Please, update to latest to fix this issue. Sorry for the trouble

**Comment by yoieh** [comment]
@ulugbekna can't find any updates above `1.82.0-insider` but i see the commit hashes seems to diff. I will try and rebuild the package.

**Comment by yoieh** [comment]
Works a bit differently on arch. Usually you just get a popup with a link to download the latest version.

If any one else faces this issue
Rebuilding the AUR packages to get a build from the latest commit worked and solved my issue.

And thank you @ulugbekna
