### ISSUE TITLE
My Github Copilot Chat isn't accessible when I am logged with an additional Github Account

### ISSUE THREAD

**Issue by callmeberzerker** [microsoft/vscode-copilot-release#418]
I have 2 GitHub accounts. 1 is for work and 1 is personal. I am signed in both in VSCode. 

My Github Copilot is definitely working. While the Github Copilot Chat (as can be seen from the logs below) is complaining that I am currently logged in as a single user! 

![image](https://github.com/microsoft/vscode-copilot-release/assets/1324069/d580b609-e4e1-48a6-ad59-a668aa0357dd)

- VS Code Version: 1.82.2
- OS Version: MacOS
- Logs:

```
2023-09-23T09:10:08.167Z [ERROR] [extension] {"constructionStack":["    at new t.ServicesAccessor (/Users/spase/.vscode/extensions/github.copilot-chat-0.7.1/dist/extension.js:2:1262828)","    at t.createProductionContext (/Users/spase/.vscode/extensions/github.copilot-chat-0.7.1/dist/extension.js:2:1007003)","    at Y (/Users/spase/.vscode/extensions/github.copilot-chat-0.7.1/dist/extension.js:2:1604401)","    at e.activate (/Users/spase/.vscode/extensions/github.copilot-chat-0.7.1/dist/extension.js:2:1607510)","    at Function.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:13032)","    at Function.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:12750)","    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10857","    at E.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6206)","    at E.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6169)","    at E.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:5626)"],"instances":{},"isSealed":false},GitHub Copilot could not connect to server. Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as MY_OTHER_GITHUB_USER."
```

Steps to Reproduce:

1. Have 2 github accounts and sign in with them.
2. Have Github Copilot subscription on one of them.
3. Observe that you do not have access to the other

**Comment by TylerLeonhardt** [comment]
This is a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/109 . we don't officially support multi-accounts today.
