### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY in Copilot Chat

### ISSUE THREAD

**Issue by pawsaw** [microsoft/vscode-copilot-release#525]
- VS Code Version:
Version: 1.84.0-insider (Universal)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T10:18:23.824Z (6 hrs ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

- OS Version: macOs 14.1 (23B74)
- Logs: n/A

Steps to Reproduce:

1. Ask anything in Chat
![image](https://github.com/microsoft/vscode-copilot-release/assets/2669826/f679218c-f41c-4e5d-8c8c-82582a97bd28)

**Comment by roblourens** [comment]
I assume you're using a corporate proxy or some other non-standard network environment?

**Comment by pawsaw** [comment]
Let me check soon, as my current working environment is quite new to me too.

What I can say for now is, that a fresh npm/ yarn installation works out of the box, without the need to configure proxy etc. Also vanilla VSCode "networking" seems to work.

However, what I researched so far is: the error code most probably is sourced from node. But this is just a guess.

Kind, Pawel

**Comment by lramos15** [comment]
This normally means you have a self signed certificate in your certificate chain.

You may want to try disabling `http.proxyStrictSSL`

**Comment by Ron024** [comment]
Go into settings (ctl+,) and search for "http proxy".  Then deselect the check box on "Http: Proxy Strict SSL".  This allowed me to use copilot through a Zscaler proxy.

**Comment by gil31** [comment]
Hi,

I have been using copilot for a long time without any problems. I installed the latest version of VSC (1.84 for win32 X64). Since then I have had exactly the same problem. 

1) I tried to modify the setting as indicated above, it does not work. 
2) I **reverted to version 1.83. Everything is working properly again.**

Have a nice day
Gil.

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by lramos15** [comment]
@gil31 Can you share your logs and some information about your network setup?

**Comment by gil31** [comment]
Hi Logan,

Unfortunately when installing version 1.83.1, I lost information related to the current problem.

Have a good day
Gil

**Comment by lramos15** [comment]
Is anyone still blocked on this before I close the issue out?

**Comment by pawsaw** [comment]
> Is anyone still blocked on this before I close the issue out?

Why do you want to close it? This is an issue reported by many people out there.

**Comment by lramos15** [comment]
> Why do you want to close it? This is an issue reported by many people out there.

Are you still blocked? We've made some changes here

**Comment by aaronlippold** [comment]
Yes, this is still an issue

**Comment by aaronlippold** [comment]
> Go into settings (ctl+,) and search for "http proxy". Then deselect the check box on "Http: Proxy Strict SSL". This allowed me to use copilot through a Zscaler proxy.

I am behind zscaler and this did not seem to resolve the issue. NODE EXTRA CERTS is set as well

**Comment by lramos15** [comment]
> Yes, this is still an issue

Can you try adding this to your settings.json to try out some new experimental fetcher code we're working on 

```
"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}
```

**Comment by aaronlippold** [comment]
I will give that a try when I’m back at my desk

**Comment by wimvc1** [comment]
> > Yes, this is still an issue
> 
> Can you try adding this to your settings.json to try out some new experimental fetcher code we're working on
> 
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```

Works for me! (GitHub Copilot Chat - v0.11.2023112001 - Pre-Release)

**Comment by balexandermunoz** [comment]
Same issue here. I'm using Zscaler.
OS: Windows 10 Enterprise 22H2
Vscode Version: 1.84.2
Copilot Chat Version: 0.10.2

**Comment by poychang** [comment]
I get the same issue here. I'm using Zscaler. Disabling `http.proxyStrictSSL` and adding `debug.useNodeFetcher` can fix this issue.

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by lramos15** [comment]
@balexandermunoz What error do you see using the advanced setting

**Comment by balexandermunoz** [comment]
@lramos15 Same as before:
`Please check your firewall rules and network connection then try again. Error Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY.`

**Comment by lramos15** [comment]
> @lramos15 Same as before: `Please check your firewall rules and network connection then try again. Error Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY.`
> 
> ![image](https://user-images.githubusercontent.com/18507365/284945027-3ec136d0-f11b-4450-bd1a-115bb211fbac.png)

Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

When asked for the URL enter `https://api.githubcopilot.com/`. This should respond with a `404 Not Found` status, that is expected, but maybe you get something else. Please share the output of this (make sure to remove any sensitive information first).

**Comment by balexandermunoz** [comment]
> Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

```
VS Code 1.84.2
Network Proxy Test 0.0.8
win32

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: false
  - globalValue: false
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://api.githubcopilot.com/...
Received response:
- Status: 404 Not Found
```

**Comment by spacerodent** [comment]
The proposed fixes work for me on Windows but not when using WSL.

**Comment by gygelly** [comment]
yup, I was in the same boat. Swapping to insiders, using preview of copilot chat, and putting "debug.useNodeFetcher": true in settings made it start working again.

**Comment by hughesdai** [comment]
Same problem here, tried all the recommendations except getting VS Code insiders, no luck so far, waiting for suggestions/updated release.

**Comment by gil31** [comment]
Hi ,
Have you somme news. I use vsc and copilot in professional context and this issue IS extremely problematic for my productivité. 

Have a nice day
Gil

**Comment by hughesdai** [comment]
@gil31 in settings.json, I added 
"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}
There is a new update to VS Code, along with GitHub Copilot released today. After the update, it seems to be working.

**Comment by MullinsN** [comment]
So, I have been having this issue for many many weeks and months, when I travelled into the office. I push on it, and had one of the network engineers. Look at the network proxy output and he made the following change for now. His comment was a follows.

"The corporate firewalls do HTTPS inspection - so I have to bypass that check when you access api.githubcopilot.com"

Hopefully it helps.

**Comment by gil31** [comment]
Hi all,

I have just installed the latest version of vsc and the latest version of the copilot and chat copilot extensions. Everything seems to be working again:

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

![image](https://github.com/microsoft/vscode-copilot-release/assets/69890937/1b691431-2411-4c52-85ad-600c6af55fdf)
![image](https://github.com/microsoft/vscode-copilot-release/assets/69890937/d15202a4-840a-44ef-b814-54c4f3e3cee3)

**Comment by jabousanyang113** [comment]
Installing the **win-ca** extension solved it for me and several others. The extension should  be set to ‘append’ mode under its settings. Then restart vscode. Found the answer here https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot.

**Comment by jabousanyang113** [comment]
Installing the win-ca extension solved it for me and several others. The extension should be set to ‘append’ mode under its settings. Then restart vscode. Found the answer here https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot.

**Comment by roaa108** [comment]
To request access to GitHub Copilot through your company's firewall, you'll typically need the specific URLs or domains that Copilot uses. find more [here](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot#urls-to-add-to-an-allowlist)

**Comment by code669** [comment]
solved my problem by in settings.json,  added
"github.copilot.advanced": {
"debug.useNodeFetcher": true
}

**Comment by joelzeal** [comment]
> > Yes, this is still an issue
> 
> Can you try adding this to your settings.json to try out some new experimental fetcher code we're working on
> 
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```

This fixed it for me

**Comment by karnold1ur** [comment]
Was able to get this fixed by switching to pre-release and using
```
"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}
```

**Comment by data-stack404** [comment]
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```

This also solved the issue for me.

MacOS 14.2.1
VSC 1.85.1
Copilot 1.146
Company uses zscaler v. 4.1

**Comment by pexa-abruno** [comment]
After upgrading to latest MacOS 14.3 many of our corporate VSCode copilot plugins fail due to SSL errors, as our company uses MITM / VPN with self signed certs.

I tried the insider version, fresh install, add the plugins, added the above settings but no luck. 

Have raised a support issue with Microsoft github service desk, and also working with Palo Alto to resolve for 100s of users.

Any ideas, help, appreciated.

![image](https://github.com/microsoft/vscode-copilot-release/assets/97858191/e4af6d57-c879-4aeb-941e-49c19620e84b)

**Comment by sugamxp** [comment]
Hi I'm facing the same issue on the latest version of VSCode and the extension.

**Comment by globaltrickster** [comment]
Same Zscaler attack here, had to go to pre-release and also add the settings

"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}

**Comment by kevinthenard** [comment]
Hi,
I have the same issue, I try all solution here, without result: SSL in conf, set the useNodeFetcher to true, VSCode Insider or not and copilot pre-release or just release.
For information, I use WSL, ZScaler and Windows 10.
I have a 404 on https://api.githubcopilot.com/ with Network Proxy Test

**Comment by ManoMangaldas** [comment]
Same Zscaler attack here, had to go to pre-release and also add the settings

"github.copilot.advanced": {
"debug.useNodeFetcher": true
}

**Comment by j-avila** [comment]
> > Yes, this is still an issue
> 
> Can you try adding this to your settings.json to try out some new experimental fetcher code we're working on
> 
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```

This works pretty well for me. Thanks a lot!  

Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by ayoubachak** [comment]
I'm using Zscaler too 
this setting worked for me :
`
"github.copilot.advanced": {
  "debug.useNodeFetcher": true
}
`
make sure to reload the extension and VSCode if needed.
VSCode Info :
Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Github Copilot :
Version: 1.171.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

**Comment by mwthrane** [comment]
> I'm using Zscaler too this setting worked for me :
> 
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```
> 
> Make sure to **reload the extension and VSCode** if needed.
> 
> VSCode : Version: 1.87.0 (system setup) Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2 Date: 2024-02-27T23:41:44.469Z Electron: 27.3.2 ElectronBuildId: 26836302 Chromium: 118.0.5993.159 Node.js: 18.17.1 V8: 11.8.172.18-electron.0 OS: Windows_NT x64 10.0.22631
> 
> Github Copilot : Version: 1.171.0 Publisher: GitHub VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

Worked for me. Zscaler here.

**Comment by Scoop2389** [comment]
Hello! For anyone still having this issue, turning this setting on:
![image](https://github.com/microsoft/vscode-copilot-release/assets/145179281/6fb30260-4d6c-4886-b89b-bae69816859a)
solved it for me (http.experimental.systemCertificatesV2)

**Comment by EliiseS** [comment]
I also have this same issue, but when I enable all the settings, I get this error in the copilot debug output:

```sh
2024-04-05 14:17:14.866 [info] [extension] Error on conversation request: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:803:12)
    at Socket.ondata (node:internal/js_stream_socket:77:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by devm33** [comment]
@EliiseS can you try `debug.useElectronFetcher` instead of `debug.useNodeFetcher`

**Comment by chankung9** [comment]
> Hello! For anyone still having this issue, turning this setting on: ![image](https://private-user-images.githubusercontent.com/145179281/316142494-6fb30260-4d6c-4886-b89b-bae69816859a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjkyOTgsIm5iZiI6MTcxMjcyODk5OCwicGF0aCI6Ii8xNDUxNzkyODEvMzE2MTQyNDk0LTZmYjMwMjYwLTRkNmMtNDg4Ni1iODliLWJhZTY5ODE2ODU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjAzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjE4NGMzODIzNDUwMDkzZDEzZWUwNmJhMGY3ZmFmY2ZmZGNiYzYxNjgwN2E2MmM1ZmVlMDUxYzk2NTdiMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ESxB49sDExNSpW-hEA1EaNHVpJpUD0sOt0OCD2QRL0) solved it for me (http.experimental.systemCertificatesV2)

this solution solve all my problem , chat , auto suggession

**Comment by EliiseS** [comment]
@devm33 Unfortunately no help. The code completion co-pilot does work, which is good enough for now I suppose :)

This is the error I receive with the above settings in the output terminal:

```txt
2024-04-10 09:57:23.257 [info] [extension] Error on conversation request: aJ: unable to get local issuer certificate
    at K2e (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:92:29514)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Git (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:92:31536)
    at X8.fetch (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:1175:27890)
    at hCe (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:1143:7965)
    at wg.fetchMany (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:1143:12855)
    at wg.fetchOne (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:1143:12036)
    at aE.fetchConversationResponse (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:859:1235)
    at aE._provideResponseWithProgress (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:857:1617)
    at aE.provideResponseWithProgress (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:855:1830)
    at r.x (/root/.vscode-server/extensions/github.copilot-chat-0.14.2024032901/dist/extension.js:869:859)
    at i.$invokeAgent (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/workbench/api/node/extensionHostProcess.js:154:44359)
```

**Comment by devm33** [comment]
Thanks for trying @EliiseS! That error stacks looks a bit odd to me though, did you restart VS Code after applying the setting?

You should see something like `[info] [FetcherService] Using Electron fetcher` in the GitHub Copilot Chat output panel.

**Comment by EliiseS** [comment]
@devm33 you're right, the setting doesn't seem to be having any effect. I only see `info] [FetcherService] Using Helix fetcher` when I enable the setting. If I change it back to node it'll says `[info] [FetcherService] Using Node fetcher`

**Comment by devm33** [comment]
@EliiseS hm strange, just to sanity check, is that where you have it in your settings json file?

```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true
  },
```

**Comment by alexdima** [comment]
@EliiseS Are you using VS Code remote like SSH, WSL, Dev Containers or Tunnels ?

**Comment by EliiseS** [comment]
@alexdima, @devm33 Ah, I am using a tunnel to a devcontainer, which runs through WSL. 

On regular windows the copilot actually works perfectly:

```sh
2024-04-15 15:20:18.925 [info] [FetcherService] Using Helix fetcher
2024-04-15 15:20:18.925 [info] [gitExtensionService] Initializing Git extension service.
2024-04-15 15:20:18.925 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-15 15:20:18.925 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-15 15:20:18.925 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-15 15:20:19.655 [info] [auth] Logged in as EliiseS
2024-04-15 15:20:19.979 [info] [chat] copilot token chat_enabled: true
2024-04-15 15:20:19.983 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-04-15 15:20:19.983 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-15 15:20:19.983 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-04-15 15:20:19.991 [info] [auth] Got Copilot token for EliiseS
2024-04-15 15:20:27.520 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-15 15:20:27.520 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-15 15:20:27.520 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-15 15:20:27.520 [info] [chat fetch] chat model gpt-4
2024-04-15 15:20:30.417 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2896 ms
2024-04-15 15:20:30.440 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-15 15:20:30.441 [info] [streamChoices] request done: requestId: [8e03e798-97ff-46ad-8d10-a29303d2e942] responseId: [8e03e798-97ff-46ad-8d10-a29303d2e942] model deployment ID: []
2024-04-15 15:20:30.445 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-15 15:20:30.445 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-15 15:20:30.445 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-15 15:20:30.445 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-15 15:20:31.510 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1065 ms
2024-04-15 15:20:31.543 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-15 15:20:31.544 [info] [streamChoices] request done: requestId: [17e35bac-66d0-46b3-a979-0b6d58375af5] responseId: [17e35bac-66d0-46b3-a979-0b6d58375af5] model deployment ID: [x4dff5e5d11fc]
2024-04-15 15:20:46.327 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-15 15:20:46.327 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-15 15:20:46.327 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-15 15:20:46.327 [info] [chat fetch] chat model gpt-4
2024-04-15 15:20:49.819 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 3491 ms
2024-04-15 15:20:49.857 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-15 15:20:49.857 [info] [streamChoices] request done: requestId: [9400238c-4450-4996-a89c-67cb9a6d3897] responseId: [9400238c-4450-4996-a89c-67cb9a6d3897] model deployment ID: []
2024-04-15 15:20:49.863 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-15 15:20:49.863 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-15 15:20:49.863 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-15 15:20:49.863 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-15 15:20:50.701 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 837 ms
2024-04-15 15:20:50.723 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-15 15:20:50.724 [info] [streamChoices] request done: requestId: [eb166036-3202-4e56-b392-5ad9bb0cfd4b] responseId: [eb166036-3202-4e56-b392-5ad9bb0cfd4b] model deployment ID: [x4dff5e5d11fc]
```

On just WSL, it won't even let me log in:

```sh
2024-04-15 13:41:54.223 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-04-15 13:44:07.656 [error] [auth] Extension activation failed: "tunneling socket could not be established, cause=connect ETIMEDOUT 127.0.0.42:9000"
```

**Comment by caoshuai619** [comment]
> Hello! For anyone still having this issue, turning this setting on: ![image](https://private-user-images.githubusercontent.com/145179281/316142494-6fb30260-4d6c-4886-b89b-bae69816859a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjUwMDIsIm5iZiI6MTcxMzQyNDcwMiwicGF0aCI6Ii8xNDUxNzkyODEvMzE2MTQyNDk0LTZmYjMwMjYwLTRkNmMtNDg4Ni1iODliLWJhZTY5ODE2ODU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzE4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWEzZDVkYTM1MThlMDYwODFmYTJiN2E3ZTZlM2UwNzFkYTAxMmU1ZTYxMjc2MWE1MzRlN2MzOGFjZWM4MGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._FniPH21Q-xnqUkYAVdBDYtz7iXZ8u9wAI-HjJWfv10) solved it for me (http.experimental.systemCertificatesV2)

thanks very much. This works for me when using copilot chat in wsl2.

**Comment by tlewers01** [comment]
> "debug.useNodeFetcher": true

I am also behind Zscaler and this seams to have fixed the issue for me.

**Comment by ChrisKibble** [comment]
Just to add to the solution and description, I'm also behind Zscaler. 

The reason it's not working out of the box is that your companies are using SSL inspection which involves replacing the certificate you're using on some or all sites so they can decrypt/re-encrypt the traffic, usually to log or analyze. You can confirm this by visiting https://api.githubcopilot.com/ and looking at the parent of the issued cert, it'll be Zscaler. The same is likely true for other proxy or VPN solutions that work similarly.

The internal (to the company) fix would be to stop SSL inspection on the domains identified [here](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot#urls-to-add-to-an-allowlist).

For me, the solution to use the pre-release of the GitHub Copilot and GitHub Copilot Chat along with the latest version of VSCode resolved the issue. I did not need to modify the Proxy SSL or the NodeFetcher values.

Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by xaviervv** [comment]
I had this issue on the newest version of 0.15.2, rolling back to 0.15.1 solved it for me
just in case I had also rolled back GitHub Copilot extension from 1.195.0 to 1.194

**Comment by GitHubCanada** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/525#issuecomment-2015746667

this work for me.

**Comment by sairaghavak** [comment]
> > Yes, this is still an issue
> 
> Can you try adding this to your settings.json to try out some new experimental fetcher code we're working on
> 
> ```
> "github.copilot.advanced": {
>   "debug.useNodeFetcher": true
> }
> ```

I am behind Zscaler and in WSL. And this has worked in my case

Updated the following in  `~/.vscode-server/data/Machine/settings.json`

```json
"http.proxyStrictSSL": false,
```
And in workspace `settings.json` Updated the following

```json
"github.copilot.advanced": {
    "debug.useNodeFetcher": true
},
```

**Comment by jejamnicki-fadv** [comment]
@sairaghavak thank you! same on WSL behind Zscaler

in my case `http.proxyStrictSSL` was true by default and it was working anyway

> [This comment](https://github.com/microsoft/vscode-copilot-release/issues/525#issuecomment-1817911755) worked for me.
> 
> I am behind Zscaler and in WSL. And this has worked in my case
> 
> Updated the following in `~/.vscode-server/data/Machine/settings.json`
> 
> "http.proxyStrictSSL": false,
> And in workspace `settings.json` Updated the following
> 
> "github.copilot.advanced": {
>     "debug.useNodeFetcher": true
> },

**Comment by simonezambettiabb** [comment]
> Go into settings (ctl+,) and search for "http proxy". Then deselect the check box on "Http: Proxy Strict SSL". This allowed me to use copilot through a Zscaler proxy.

Worked for me thanks.
