### ISSUE TITLE
Error while deciding what workspace information to collect

### ISSUE THREAD

**Issue by melvan27** [microsoft/vscode-copilot-release#618]
I get this error when I try to send a message with @ workspace in a chat with a few messages (over 5):
Encountered an error while deciding what workspace information to collect: failed
This has happened in 2 sessions so far. I had been using @ workspace in the chat a couple times before in the same session with no problems before I started seeing this error, started a second session, and eventually saw this error again. Both sessions have at least 3 workspace messages. I can send a message without @ workspace and get a response. I also started a new chat session and am able to use @ workspace with no issues.
- Version: 1.85.0-insider (system setup)
- Commit: c6b48c364dde70c12bf977f1da50acda0fd801e3
- Date: 2023-11-30T05:35:40.559Z
- Electron: 25.9.6
- ElectronBuildId: 25427645
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Windows_NT x64 10.0.19045
- Logs:
2023-11-30 11:00:10.062 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-11-30 11:00:10.062 [info] [chat fetch] modelMaxTokenWindow 4096
2023-11-30 11:00:10.062 [info] [chat fetch] chat model gpt-4
2023-11-30 11:00:10.464 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 401 ms
2023-11-30 11:00:10.465 [info] [chat fetch] Request ID for failed request: ,295006c0-9ed7-46d2-8971-20389149a1dd
2023-11-30 11:00:10.467 [info] [chat fetch] Unhandled status from server:,400,Bad Request

2023-11-30 11:00:10.468 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed
    at R7.resolveContext (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:512:1771)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at Uue (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:604:124)
    at Ei.buildPrompt (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:608:779)
    at n1._provideResponseWithProgress (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:1256:798)
    at n1.provideResponseWithProgress (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:1254:2086)
    at s.x (c:\Users\User\.vscode-insiders\extensions\github.copilot-chat-0.11.2023113001\dist\extension.js:1266:1022)
    at f.$invokeAgent (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:128938)

Steps to Reproduce:

1. Start a new session with an @ workspace message
2. Ask a few more workspace-related things, sprinkling in some non-workspace requests
3. Get the error

**Comment by mjbvz** [comment]
Are you still seeing this? If so, can you share the exact questions you asked and ideally also the workspace you asked them in. Otherwise it's going to be hard to investigate what's going wrong

**Comment by danielo515** [comment]
This happens to me in a private repository. May that be related?

**Comment by WilliamNT** [comment]
Switching both the GitHub Copilot and Copilot Chat extensions to the pre-release versions solved the issue in my case.

**Comment by michailozdemir** [comment]
Still happens to me, even after switching to Pre-Release versions.

**Comment by d-mahard** [comment]
seems to be duplicate with #646 .
In any case, I also experience this.

I can give you example, so I am working on the [@microsoft/vscode](https://github.com/microsoft/vscode) codebase itself, and asked the following:
_"I understand that colorRegistry.ts defines the default colors, but a theme can customize it. Can you tell me in which function exactly the color change is applied?"_

![image](https://github.com/microsoft/vscode-copilot-release/assets/146386738/805af952-e4e4-414a-a797-1b6b069d03d0)

Even if copilot cannot give an answer, I think the output should be in a form of a chat (with a reasoning or suggestion on what kind of information is expected from the prompt) instead of an error like that.

**Comment by SpaceFoon** [comment]
I had this same problem. No matter what question I asked @workspace would just error out every time. Never got it to work one time. Had this issues for days straight.
The solution was to start a new session. I guess when your chat gets too long it stop working.

**Comment by kadehh** [comment]
Might this error be related to local libraries in use?

**Comment by victorfeight** [comment]
Same issue here, and starting a new session fixes it for me.

**Comment by waldemarnt** [comment]
> Same issue here, and starting a new session fixes it for me.

Same here starting a new session in Copilot chat fixed the issue.

**Comment by adamwea** [comment]
Same, starting a new session fixed it.

**Comment by ldelossa** [comment]
Just encountered this, starting new session works :+1:

**Comment by smit-io** [comment]
How do I start a new session?

**Comment by ldelossa** [comment]
@smit-io on the window for copilot in the side bar (main chat not online), top right corner there's a + icon. Hit that

**Comment by smit-io** [comment]
Thanks, that worked

**Comment by Joshua2504** [comment]
I was running into the same issue. Starting a new session by clicking the plus icon above the chat window fixed this.

**Comment by mjbvz** [comment]
There was an issue with long histories sending too much content to copilot. This should now be fixed in the latest copilot-chat extension release

If you are still seeing `@workspace` requests fail with 400 (bad request), please open a new issue so we can continue investigating
