### ISSUE TITLE
`@workspace` is failing with last nights update in vscode 1.85, copilot-chat-0.11.0

### ISSUE THREAD

**Issue by shaneholloman** [microsoft/vscode-copilot-release#646]
- VS Code Version: `1.85`
- OS Version: `ubuntu 22.04`
- Copilot Chat version: `copilot-chat-0.11.0`

Steps to Reproduce:

---

@workspace

between these 2 inventory files is there a vm without any IP address

```sh
inventories/auckland/Auckland.ipv4.inventory.ini
inventories/auckland/Auckland.ipv6.inventory.ini
```

resulted in:

```markdown
Encountered an error while deciding what workspace information to collect: failed
```

## logs:

```log
2023-12-08 12:26:02.590 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed
    at A7.resolveContext (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:512:1771)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at Uue (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:604:124)
    at Ei.buildPrompt (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:608:779)
    at n1._provideResponseWithProgress (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1256:798)
    at n1.provideResponseWithProgress (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1254:2086)
    at s.x (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1266:1022)
    at f.$invokeAgent (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:128938)
2023-12-08 12:34:23.583 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-08 12:34:23.584 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-08 12:34:23.584 [info] [chat fetch] chat model gpt-4
2023-12-08 12:34:26.613 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 3029 ms
2023-12-08 12:34:31.735 [info] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-08 12:34:31.737 [info] [streamChoices] request done: requestId: [c4ca1b3d-a1c8-42f1-ac58-3514d2a2d9b6] responseId: [24eae97d-1b5e-4ab2-ac11-8c813aebbb4a] model deployment ID: [x74a4b0e7ace1]
2023-12-08 12:34:31.753 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-08 12:34:31.753 [info] [chat fetch] modelMaxTokenWindow 8192
2023-12-08 12:34:31.753 [info] [chat fetch] chat model gpt-3.5-turbo
2023-12-08 12:34:33.269 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1516 ms
2023-12-08 12:34:33.272 [info] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-08 12:34:33.273 [info] [streamChoices] request done: requestId: [e7f36e64-75c3-480a-93e5-5237dffa84cc] responseId: [dbe344be-3c8e-45bd-86f4-122bc4fbe8cd] model deployment ID: [x338b9c029b38]
2023-12-08 12:34:58.021 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-08 12:34:58.021 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-08 12:34:58.021 [info] [chat fetch] chat model gpt-4
2023-12-08 12:34:59.690 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1668 ms
2023-12-08 12:34:59.693 [info] [chat fetch] Request ID for failed request: ,f57571fc-e75d-4556-b2c6-d58f5b8d7fd5
2023-12-08 12:34:59.694 [info] [chat fetch] Unhandled status from server:,400,Bad Request

2023-12-08 12:34:59.698 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed
    at A7.resolveContext (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:512:1771)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at Uue (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:604:124)
    at Ei.buildPrompt (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:608:779)
    at n1._provideResponseWithProgress (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1256:798)
    at n1.provideResponseWithProgress (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1254:2086)
    at s.x (/home/shadmin/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:1266:1022)
    at f.$invokeAgent (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:128938)
```

![image](https://github.com/microsoft/vscode-copilot-release/assets/1563909/57ec57eb-992d-4a16-b9b8-56636b3a0547)

**Comment by erikologic** [comment]
This is happening for me as well, both on release and pre-release version.
Query: `@workspace find where the /customer endpoint is defined`
Results:
```
2023-12-11 11:04:49.954 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1854 ms
2023-12-11 11:04:49.955 [info] [chat fetch] Request ID for failed request: ,93edf2f3-db80-405d-a758-ff319f5e9d04
2023-12-11 11:04:49.957 [info] [chat fetch] Unhandled status from server:,400,Bad Request

2023-12-11 11:04:49.958 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed
    at A7.resolveContext (/.../.vscode-insiders/extensions/github.copilot-chat-0.11.0/dist/extension.js:512:1771)
    
    ...
    
 2023-12-11 11:06:47.565 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1369 ms
2023-12-11 11:06:47.566 [info] [chat fetch] Request ID for failed request: ,663817e7-f220-469f-8427-42ae0a62cccb
2023-12-11 11:06:47.567 [info] [chat fetch] Unhandled status from server:,400,Bad Request

2023-12-11 11:06:47.568 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed
    at C3.resolveContext (/.../.vscode-insiders/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:512:1768)
```

Using VSCode Insiders on Mac M1:
```
Version: 1.85.0-insider (Universal)
Commit: 055458feab40fc308fc6d70b185068138c8cf8eb
Date: 2023-11-27T05:36:15.984Z (2 wks ago)
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.1.0
```

Project is private, and it can't be shared.
It is structured as a monorepo, containing a few experimental folders and a main /src/ with different projects.
Most of the software is written in Python, with a React frontend, and a small Go code presence.
We use Pants build system as a Python toolchain, and npm for Javascript.

I've also tried using a .copilotignore file such as:
```
*
!src/nada/app/*
```
to mask everything apart one backend project, with the same results.

**Comment by mjbvz** [comment]
Please test this on copilot-chat 0.12+ and let me know if you're still seeing this issue

**Comment by erikologic** [comment]
It crashes on copilot-chat v0.13.2024020701 (pre-release)
Maybe because it is a monorepo...?
I got it working for other smaller projects...

LOGS
Copilot Chat
```
2024-02-07 15:40:45.615 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-02-07 15:40:45.615 [info] [chat fetch] modelMaxPromptTokens 7168
2024-02-07 15:40:45.615 [info] [chat fetch] modelMaxResponseTokens 4096
2024-02-07 15:40:45.615 [info] [chat fetch] chat model gpt-3.5-turbo
2024-02-07 15:40:46.364 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 749 ms
2024-02-07 15:40:46.822 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-02-07 15:40:46.823 [info] [streamChoices] request done: requestId: [e032ce2c-e210-4181-8fba-ec3310a92d67] responseId: [e032ce2c-e210-4181-8fba-ec3310a92d67] model deployment ID: [xd71d885bb108]
2024-02-07 15:41:55.512 [info] [FetcherService] Using Helix fetcher
2024-02-07 15:41:55.512 [info] [gitExtensionService] Initializing Git extension service.
2024-02-07 15:41:55.866 [info] [gitExtensionService] Successfully activated the vscode.git extension.
```

Extension Host
```
many of the following:
2024-02-07 15:41:51.718 [error] RangeError: Invalid string length
    at n.k (/Users/.../Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:18)
    at n.handleData (/Users/.../Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:1171)
    at Socket.<anonymous> (/Users/.../Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:440)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
...
2024-02-07 15:41:54.124 [info] Extension host with pid 13827 started
```

Extension Host (worker)
```
2024-02-07 15:41:54.092 [info] Extension host started
2024-02-07 15:41:54.092 [info] Eager extensions activated
```

Main
```
2024-02-07 15:41:53.570 [info] Extension host with pid 53635 exited with code: 7, signal: unknown.
```
