### ISSUE TITLE
Unable to generate responses, "e.request.message.startsWith is not a function", "e.split is not a function"

### ISSUE THREAD

**Issue by TheOnlyZac** [microsoft/vscode-copilot-release#652]
**Message from @roblourens**: Users can work around this issue by clearing the current chat session (+ icon in view header)

Copilot Chat is unable to generate responses. I just get errors like this:
`e.request.message.startsWith is not a function`
`e.split is not a function`

<img width="544" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/7002063/a8c7e8b3-bbb0-424c-84f6-49058f5247c6">

I have Copilot Chat extension v0.12.2023120701 (pre-release). Same errors happen with Release version. The issue persists even after restarting VS Code and rebooting my machine. It was working earlier today.

- **VS Code Version**:
Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z (1 day ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

- **OS Version:**
MacOS Sonoma v14.1.1
Connected to 2-core 8 GB Codespace (Ubuntu 20.04.6 LTS)

- **Logs**:
```
2023-12-08 03:53:30.440 [info] [gitExtensionService] Initializing Git extension service.
2023-12-08 03:53:30.671 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2023-12-08 03:53:30.671 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2023-12-08 03:53:30.671 [info] [gitExtensionService] Successfully registered Git commit message provider.
2023-12-08 03:53:30.991 [info] [auth] Logged in as TheOnlyZac
2023-12-08 03:53:32.041 [info] [chat] copilot token chat_enabled: true
2023-12-08 03:53:32.041 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2023-12-08 03:53:32.041 [info] [auth] Got Copilot token for TheOnlyZac
2023-12-08 03:53:32.921 [info] [auth] Logged in as TheOnlyZac
2023-12-08 03:53:32.927 [info] [chat] copilot token chat_enabled: true
2023-12-08 03:53:32.927 [info] [auth] Got Copilot token for TheOnlyZac
2023-12-08 03:53:34.529 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.Xe (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1905)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:34.530 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.et (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:2326)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:34.531 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.st (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:3497)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:34.535 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.tt (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:2585)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:34.541 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.rt (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:3238)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:34.544 [info] [asyncCompute] Failed to compute async parser based result: Error: Unrecognized language: makefile
    at y (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:5:9338)
    at E (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:1334)
    at Object.nt (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:178:2898)
    at MessagePort.<anonymous> (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/worker2.js:180:2311)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-08 03:53:35.168 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2023-12-08 03:53:35.168 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2023-12-08 03:53:38.876 [info] [extension] TypeError: e.request.message.startsWith is not a function
    at /home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:1046:80
    at Array.map (<anonymous>)
    at Object.turnFilter (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:1046:54)
    at yi.buildPrompt (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:608:1597)
    at Zy._provideResponseWithProgress (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:858:798)
    at Zy.provideResponseWithProgress (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:856:4103)
    at s.x (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:868:1022)
    at f.$invokeAgent (/vscode/bin/linux-x64/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/workbench/api/node/extensionHostProcess.js:141:128938)
2023-12-08 03:56:57.376 [info] [extension] TypeError: e.request.message.startsWith is not a function
    at /home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:1046:80
    at Array.map (<anonymous>)
    at Object.turnFilter (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:1046:54)
    at yi.buildPrompt (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:608:1597)
    at Zy._provideResponseWithProgress (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:858:798)
    at Zy.provideResponseWithProgress (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:856:4103)
    at s.x (/home/codespace/.vscode-remote/extensions/github.copilot-chat-0.12.2023120701/dist/extension.js:868:1022)
    at f.$invokeAgent (/vscode/bin/linux-x64/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/workbench/api/node/extensionHostProcess.js:141:128938)
```

Steps to Reproduce:

1. Use any feature that would prompt Copilot to respond (chat, /explain, etc)

**Comment by roblourens** [comment]
Hm, so you have some invalid data in your chat history due to a bug. I fixed that bug in https://github.com/microsoft/vscode/pull/199581 so invalid history won't be saved anymore. However I realize that once the invalid history is there, you will continue seeing this until you clear the chat session (use the plus icon) so maybe I should do something to patch up the history.

Anyway, unblock yourself for now but using the + icon in the header to start a new chat session.

**Comment by roblourens** [comment]
This has been out for awhile- not going to plan more changes here
