### ISSUE TITLE
Copilot fails when asking about @workspace - "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by bsmietanka** [microsoft/vscode-copilot-release#670]
- VS Code Version: 1.85.0
- OS Version: MacOS Sonoma 14.2
- Logs:
```
2023-12-13 16:04:49.219 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-13 16:04:49.219 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-13 16:04:49.219 [info] [chat fetch] chat model gpt-4
2023-12-13 16:04:55.791 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 6571 ms
2023-12-13 16:05:01.927 [info] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-13 16:05:01.930 [info] [streamChoices] request done: requestId: [53194cf0-f299-4a01-b519-a3d45c1d19df] responseId: [f37eca89-96a9-4441-814b-cad0b5d1307f] model deployment ID: [x8d3c95500d67]
2023-12-13 16:05:02.274 [info] [extension] RangeError: Maximum call stack size exceeded
    at y7 (/Users/bartlomiejsmietanka/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:508:2409)
    at /Users/bartlomiejsmietanka/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:508:4414
    at T7.getBasicChunks (/Users/bartlomiejsmietanka/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:508:4489)
    at /Users/bartlomiejsmietanka/.vscode/extensions/github.copilot-chat-0.11.0/dist/extension.js:511:5017
```
![image](https://github.com/microsoft/vscode-copilot-release/assets/22854483/2927f9f4-6c30-43b0-aad8-a8b88dff550a)

Steps to Reproduce:

1. Type `@workspace <any prompt here>` in Copilot Chat
2. Fails after some time with above message
3. There's no issue when running `@workspace /tests` inside some methods' context, runs as expected (writes some unit test).

If there are some additional information that I could provide let me know.

**Comment by TylerLeonhardt** [comment]
In the past, we've seen this in the semantic chunking space, so I'll defer to @andreamah for initial investigation.

**Comment by adgower** [comment]
I'm having same problem.

**Comment by TinChung41** [comment]
I'm unable to use the new LLM inside workspace because of this problem

**Comment by arthurserres** [comment]
Same issue on my side, any update ?

**Comment by Kekspace** [comment]
Same issue

**Comment by hmlatapie** [comment]
same issue

**Comment by hudarsono** [comment]
Same issue on macbook m1 pro with osx ventura, latest vscode, and latest copilot

**Comment by andreamah** [comment]
Does this still happen on the prerelease version of the extension?

**Comment by spirosbax** [comment]
same issue here. Solved it by switching to the prerelease version (v0.12.2023120701)

**Comment by andreamah** [comment]
> same issue here. Solved it by switching to the prerelease version (v0.12.2023120701

Does this happen on the latest prerelease?

**Comment by bsmietanka** [comment]
I was able to avoid the issue on the pre-release version, thanks for the suggestion

**Comment by andreamah** [comment]
Sounds like the fix is in the latest prerelease. Closing this unless others can repro.

**Comment by poka-IT** [comment]
I still have the same issue, do you know when the fix will be merge to release ?

**Comment by andreamah** [comment]
The next stable release should have it.
