### ISSUE TITLE
Unhandled Exception in AskInConversationAsync: System.InvalidOperationException

### ISSUE THREAD

**Issue by monko9j1** [microsoft/vscode-copilot-release#696]
- VS Code Version: Version: 1.85.1
- OS Version: Windows_NT x64 10.0.19045
- Logs:
[Conversations Error] [Conversations] Unhandled exception in AskInConversationAsync: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Conversations.Abstractions.RawResponse.CreateResponse(CompletionResponseStatus status) in D:\a\_work\1\s\src\Conversations.Abstractions\Parsing\RawResponse.cs:line 88
   at Conversations.Abstractions.StreamingParser.RunnerAsync(CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Abstractions\Parsing\StreamingParser.cs:line 116
   at Conversations.Kernel.DefaultConversation.BuildCompletionResponseAsync(IntentExecutionContext request, LLMResponse result, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Conversations.Kernel\DefaultConversation.cs:line 422
   at Conversations.Kernel.DefaultConversation.AskAsync(CopilotRequest request, ActiveInteractions activeInteractions, IContextProviders context, CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Kernel\DefaultConversation.cs:line 175
   at Microsoft.VisualStudio.Conversations.Service.ServiceTarget.AskInConversationAsync(CopilotSessionId sessionId, CopilotRequest request, ActiveInteractions activeInteractions, CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Service.Implementation\ServiceTarget.cs:line 144
[CopilotSessionProvider Error] Error on conversation request (CorrelationId: 6b700ad1-5382-49d3-9f03-0339af25c276): StreamJsonRpc.RemoteInvocationException: Operation is not valid due to the current state of the object.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Copilot.CopilotSession.<SendRequestCoreAsync>d__36.MoveNext()
RPC server exception:
System.InvalidOperationException: Operation is not valid due to the current state of the object.
      at Conversations.Abstractions.RawResponse.CreateResponse(CompletionResponseStatus status) in D:\a\_work\1\s\src\Conversations.Abstractions\Parsing\RawResponse.cs:line 88
      at Conversations.Abstractions.StreamingParser.RunnerAsync(CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Abstractions\Parsing\StreamingParser.cs:line 116
      at Conversations.Kernel.DefaultConversation.BuildCompletionResponseAsync(IntentExecutionContext request, LLMResponse result, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Conversations.Kernel\DefaultConversation.cs:line 422
      at Conversations.Kernel.DefaultConversation.AskAsync(CopilotRequest request, ActiveInteractions activeInteractions, IContextProviders context, CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Kernel\DefaultConversation.cs:line 175
      at Microsoft.VisualStudio.Conversations.Service.ServiceTarget.AskInConversationAsync(CopilotSessionId sessionId, CopilotRequest request, ActiveInteractions activeInteractions, CancellationToken cancellation) in D:\a\_work\1\s\src\Conversations.Service.Implementation\ServiceTarget.cs:line 144
      at Microsoft.VisualStudio.Conversations.Service.CopilotServiceContainer.AskInConversationAsync(CopilotSessionId conversationId, CopilotRequest request, ActiveInteractions activeInteractions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Conversations.Service.Implementation\CopilotServiceContainer.cs:line 252

Steps to Reproduce:

This only happens in visual studio 2022 (community edition), never has happened in vscode until now. I tried sending this prompt in github copilot chat: "im wondering is it possible to make a Radzen Server applications function he same like how MVC does, sending the fully rendered html?" in the chat it returns:
![image](https://github.com/microsoft/vscode-copilot-release/assets/59132442/7ce2bede-d0af-4e16-bd39-8696931e3e52)

I'm not sure what causes this? For example i tried fixing the prompt or rewording it, sometimes fixes the issue like I simply added a same prompt again but I fixed my typo at "function he same" I added a T for the, resent it and it answers fine. However if i close the current chat session and open a new one and send the same exact prompt again, the same error happens, with the same log attached. This has happened multiple times today, and its really making things frustrating.

**Comment by digitarald** [comment]
Please report VS issues via VS' [_built-in Feedback Tool_](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022).
