### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by nguyenvanphituoc** [microsoft/vscode-copilot-release#759]
- VS Code Version: 1.86.0-insider (Universal)
- OS Version: Darwin arm64 23.1.0
- Logs:
2024-01-19 10:52:06.927 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-19 10:52:06.927 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-19 10:52:06.928 [info] [chat fetch] chat model gpt-4
2024-01-19 10:52:08.684 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1756 ms
2024-01-19 10:52:08.823 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-19 10:52:08.826 [info] [streamChoices] request done: requestId: [d21a3fc9-2f87-46d7-bae2-ecc1d9cda129] responseId: [d21a3fc9-2f87-46d7-bae2-ecc1d9cda129] model deployment ID: [x8d3c95500d67]
2024-01-19 10:52:08.832 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-19 10:52:08.832 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-19 10:52:08.832 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-19 10:52:09.400 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 568 ms
2024-01-19 10:52:09.430 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-19 10:52:09.431 [info] [streamChoices] request done: requestId: [78b83c36-df9c-4ceb-9a24-3f774beedef4] responseId: [78b83c36-df9c-4ceb-9a24-3f774beedef4] model deployment ID: [xd71d885bb108]
2024-01-19 10:52:20.684 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (/Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1251:85)
    at /Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (/Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5183)
    at n1._provideResponseWithProgress (/Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:1173)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n1.provideResponseWithProgress (/Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at i.y (/Users/admin/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at o.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:40531)

Steps to Reproduce:

1. open new chat
2. send any message

**Comment by griffindore** [comment]
For me, the 1st message works, but all subsequent produces that error.

**Comment by aiday-mar** [comment]
It appears that the method `printMessageContent` inside of `chatLogger.ts` file is throwing an error on the `split` method.

**Comment by ford555** [comment]
Yes, the users who are paying for GitHub Copilot are experiencing it :(

**Comment by rlovell3** [comment]
Same here.  Been unable to use GitHub Copilot in Insiders version for two days now.  Standard version working well.

**Comment by nkabram** [comment]
Same issue, only in code-insiders

**Comment by w4ffl35** [comment]
Frustrating bug.

**Comment by joyceerhl** [comment]
Does this still repro for you all with the latest pre-release? If so, can you please share the conversation history that you have? That callstack points to code that has not changed in 2 months, and I would not expect it to interfere with chat functionality. There was a different issue related to some extension api changes that should have been resolved with yesterday's pre-release.

**Comment by mcarpenterjr** [comment]
Could this be related to the deprecation of LABS? I feel like it started when I uninstalled labs quelling some noisy alerts.

**Comment by mcarpenterjr** [comment]
> Does this still repro for you all with the latest pre-release? If so, can you please share the conversation history that you have? That callstack points to code that has not changed in 2 months, and I would not expect it to interfere with chat functionality. There was a different issue related to some extension api changes that should have been resolved with yesterday's pre-release.

Just switched to the pre-release channel through the extensions marketplace and it's working as expected.

**Comment by joyceerhl** [comment]
Thanks, I'll close this issue out since I believe it should now be resolved. Please let me know if that isn't the case and ideally share details of the query you are sending Copilot Chat.

**Comment by BarriBarri20** [comment]
You could switch to the release version
