### ISSUE TITLE
Response got filtered

### ISSUE THREAD

**Issue by bulawow** [microsoft/vscode-copilot-release#773]
Version: 1.86.0-insider (user setup)
Commit: e244acbb172c428cb219717a07bf55d2737492ca
Date: 2024-01-22T05:35:59.383Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

copilot: v1.153.667
copilot chat: v0.12.2024012201

- Logs:
2024-01-23 06:27:56.026 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-01-23 06:27:56.027 [info] [chat fetch] modelMaxPromptTokens 6144
2024-01-23 06:27:56.027 [info] [chat fetch] modelMaxResponseTokens 4096
2024-01-23 06:27:56.027 [info] [chat fetch] chat model gpt-4
2024-01-23 06:27:58.056 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2028 ms
2024-01-23 06:27:59.032 [info] [streamMessages] message 0 returned. finish reason: [content_filter]
2024-01-23 06:27:59.032 [info] [streamChoices] request done: requestId: [7a222166-38fc-4362-a138-40db318256e1] responseId: [7a222166-38fc-4362-a138-40db318256e1] model deployment ID: [xa51b78e920cd]
2024-01-23 06:27:59.034 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: (filtered) Response got filtered.
    at tq.resolveContext (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:338:999)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at zse (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:264:124)
    at la.buildPrompt (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:268:779)
    at hS._provideResponseWithProgress (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:892:1056)
    at hS.provideResponseWithProgress (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:890:3931)
    at i.y (c:\Users\BulawOw1\.vscode-insiders\extensions\github.copilot-chat-0.12.2024012201\dist\extension.js:902:1016)
    at o.$invokeAgent (c:\Users\BulawOw1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:40137)

![123](https://github.com/microsoft/vscode-copilot-release/assets/11963752/c247655e-c7ae-4583-a829-980b0851a1e8)

**Comment by GottZ** [comment]
for some historical game programming reason I think the word "ragdoll" would be better than "corpse".

**Comment by bulawow** [comment]
well every variable and things related to it are colled corpse i dont think it would work

**Comment by Johnsn0w** [comment]
I don't know if it's a bug, but it gives the "Response got filtered" error because i had the full line from Liam Neeson. "I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money....."

If that's indeed not a bug then a more descriptive error message would save a lot of pain and suffering to programmers, I didn't know the filter was copyright nor did I know it was erroring based on the content of the file.

**Comment by lramos15** [comment]
The messaging has been improved here to dictate copyright vs other Responsible AI service related filters
