### ISSUE TITLE
workspace suddenly stopped working

### ISSUE THREAD

**Issue by Ovid** [microsoft/vscode-copilot-release#800]
I've been using `@workspace` heavily for a Python project. Suddenly, it now longer works and cannot figure out what workspace information to collect. I have tried restarting VS Code a few times, but to no avail.

I've added my project to https://github.com/Ovid/ovid-novelist in case that helps. However, even switching back to the original `main` branch (which was working earlier) throws this error, so it does not appear to be related to the branch.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24634/ba4aaa86-f36a-4e55-8adc-57525bedbbec)

- VS Code Version: Version: 1.85.2 (Universal) 
- OS Version: Darwin Ovids-M1-Laptop.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
- Logs: 

2024-01-27 16:59:42.066 [info] [gitExtensionService] Initializing Git extension service.
2024-01-27 16:59:42.066 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-01-27 16:59:42.066 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-01-27 16:59:42.066 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-01-27 16:59:42.400 [info] [auth] Logged in as Ovid
2024-01-27 16:59:42.768 [info] [chat] copilot token chat_enabled: true
2024-01-27 16:59:42.768 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-01-27 16:59:42.768 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-01-27 16:59:42.768 [info] [auth] Got Copilot token for Ovid
2024-01-27 16:59:42.774 [info] [auth] Logged in as Ovid
2024-01-27 16:59:42.775 [info] [chat] copilot token chat_enabled: true
2024-01-27 16:59:42.775 [info] [auth] Got Copilot token for Ovid
2024-01-27 16:59:45.972 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-27 16:59:45.972 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-27 16:59:45.972 [info] [chat fetch] chat model gpt-4
2024-01-27 16:59:48.008 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2036 ms
2024-01-27 16:59:48.104 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-27 16:59:48.105 [info] [streamChoices] request done: requestId: [d001f48f-c77f-498f-99e4-f95864bdc784] responseId: [d001f48f-c77f-498f-99e4-f95864bdc784] model deployment ID: []
2024-01-27 16:59:48.301 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-27 16:59:48.301 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-27 16:59:48.301 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-27 16:59:49.169 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 867 ms
2024-01-27 16:59:49.299 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-27 16:59:49.300 [info] [streamChoices] request done: requestId: [5917006b-b88e-48c4-a42d-53ece008bff4] responseId: [5917006b-b88e-48c4-a42d-53ece008bff4] model deployment ID: [x338b9c029b38]
2024-01-27 17:00:24.974 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-27 17:00:24.975 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-27 17:00:24.975 [info] [chat fetch] chat model gpt-4
2024-01-27 17:00:25.760 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 784 ms
2024-01-27 17:00:25.762 [info] [chat fetch] Request ID for failed request: ,c381d9f2-b8d8-4a4a-8e8e-1922dc60519c
2024-01-27 17:00:25.764 [info] [chat fetch] Unhandled status from server:,400,Bad Request

**2024-01-27 17:00:25.766 [info] [extension] Error: Encountered an error while deciding what workspace information to collect: failed**
    at A7.resolveContext (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:512:1771)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at Uue (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:604:124)
    at Ei.buildPrompt (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:608:779)
    at n1._provideResponseWithProgress (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:798)
    at n1.provideResponseWithProgress (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at s.x (/Users/ovid/.vscode/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at f.$invokeAgent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:128938)
2024-01-27 17:07:22.021 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-27 17:07:22.021 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-27 17:07:22.021 [info] [chat fetch] chat model gpt-4
2024-01-27 17:07:23.619 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1597 ms
2024-01-27 17:07:25.406 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-27 17:07:25.408 [info] [streamChoices] request done: requestId: [9c184a30-3f4a-45c7-9c17-b1febacf7cb5] responseId: [9c184a30-3f4a-45c7-9c17-b1febacf7cb5] model deployment ID: []
2024-01-27 17:07:26.603 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-27 17:07:26.603 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-27 17:07:26.603 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-27 17:07:27.558 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 953 ms
2024-01-27 17:07:27.633 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-27 17:07:27.633 [info] [streamChoices] request done: requestId: [66d36f39-f80e-4821-839c-48f8e0155fde] responseId: [66d36f39-f80e-4821-839c-48f8e0155fde] model deployment ID: [x338b9c029b38]

Steps to Reproduce:

1. Be me.
2. Otherwise, I have no idea. I can no longer use `@workspace` at all.

**Comment by Ovid** [comment]
I have also tried:

* Restarting my computer
* Restarting VS Code (multiple times)
* Uninstalling github copilot and github copilot chat extensions
* Toggled between release and prerelease versions
* Using inappropriate language

Note that Copilot itself still works just fine, as does Copilot Chat. The `@vscode` command works fine, but `@terminal` fails with the same error as `@workspace`:

> Encountered an error while deciding what workspace information to collect: failed

**Comment by Ovid** [comment]
I have now cloned my repository into a new directory and started working from there. Now, `@workspace` is working again. Very happy to have this workaround. However, it's also very disruptive to my workflow. Any advice would be appreciated. Thank you!

**Comment by John-Dig** [comment]
I was getting the same error

Encountered an error while deciding what workspace information to collect: failed

I believe it was a week or more ago when i switched to the pre-release and that solved it for a while, rebooting also worked once.  Now neither approaches work.

**Comment by mjbvz** [comment]
@Ovid What version of copilot-chat were you using? Do you see this on v0.12.0+?

**Comment by Ovid** [comment]
@mjbvz I have no idea. It takes so long to get any responses to these issues that I wind up pushing my code, checking it out in a new directory, deleting the previous workspace, and starting over. By the time I get a response, my old problem and/or configuration is gone.

I'll be speaking at a conference in Germany in a couple of months about the impact of these technologies and so far, my main conclusion is that these tools just aren't ready for prime time. I'm sure that many in my audience of developers will be happy to hear that, though I suspect that with the rapid maturation of these tools, my conclusion might change.

**Comment by Ovid** [comment]
For my comment above, more context might be useful to anyone reading this.

I've successfully written some small applications using these tools, including an iPhone application, despite my not knowing iOS development or Swift. However, for my upcoming talk, aside from giving much of the history of these technologies, starting with Google's [Attention Is All You Need](https://arxiv.org/abs/1706.03762) paper, I wanted to present the results of me writing a large, professional application that solves a real problem.

I deliberately chose a to build something whose problem domain I know well (writing novels) and I knew had been done many times before (a GUI word processor customized specifically for writing novels). I've written something similar in Javascript before, but I chose technologies I have no experience with (GUI programming, specifically using PyQt6 in this case). This is to learn how a developer with decades of experience writing huge applications  and strong domain experience in the problem space can transition to these new technologies. I've tried to avoid StackOverflow and documentation to see just how far AI can carry me. The answer, so far, is not far.

I've already had someone from the PyQt community warn me that generative AI will not be able to help because there's simply not enough public code/documentation available on these applications for the models to help someone. This appears to be true. "Mansplaining as a service" has been very true as Copilot has repeatedly assured me that its code is working when, in fact, it is not.

However, when compounded with the underlying instability of these tools, they can verge on unusable ("suddenly stopped working" is the very definition of unusable in this case). These tools do show amazing promise and I look forward to seeing what they will be able to do, but so far, they're just not there yet.

**Comment by digitarald** [comment]
@Ovid thank you for sharing. Curious how it works for you when you try it again. Let us know. We are doing user research in several domains, from users working on net-new projects with stacks they know, but also projects that are unfamiliar. AI needs in both are vastly different. GitHub just published some great research here: https://github.blog/2024-01-17-a-developers-second-brain-reducing-complexity-through-partnership-with-ai/

@John-Dig is it still happenon on release or pre-release Chat?
