### ISSUE TITLE
Copilot Chat doesn't work with Remote SSH project 

### ISSUE THREAD

**Issue by clogwog** [microsoft/vscode-copilot-release#9]
- VS Code Version:Version: 1.79.0-insider (Universal)
- OS Version: Mac OS 13.3.1 and aarch64 aarm remote

Steps to Reproduce:

1. install remote ssh extension (ms-vscode-remote.remote-ssh)
2. open Remote ssh project on aarch64 ubuntu
3. install Github Copilot Chat into aarch64 machine (GitHub.copilot-nightly)
4. receive an error: log: `[ERROR] [default] [2023-05-17T03:02:01.015Z] GitHub Copilot could not connect to server. Extension activation failed: "getaddrinfo ENOTFOUND api.github.com"
`

**Comment by ahosker** [comment]
I've seen that error before, elsewhere. @clogwog itlooks like your remote server can not find the DNS to api.github.com

Does it have internet access? Is the firewall stopping remote connections?

**Comment by rrmistry** [comment]
As of today, it still doesn't work. But the error is as follows:

<img width="1197" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/25514145/23979a5a-6ab0-45b9-9308-b98ebc450aec">

```
2023-05-18 15:12:48.615 [error] Failed to install extension. github.copilot-chat
2023-05-18 15:12:48.615 [error] ReleaseVersionNotFound: Can't install release version of 'github.copilot-chat' extension because it has no release version.
    at e.ExtensionManagementService.G (/root/.vscode-server-insiders/bin/9084e081d4e89ed8ab67fce340d573c4e1378939/out/vs/server/node/server.main.js:142:32025)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async e.ExtensionManagementService.installFromGallery (/root/.vscode-server-insiders/bin/9084e081d4e89ed8ab67fce340d573c4e1378939/out/vs/server/node/server.main.js:142:23678)
```

It seems that VS Code Insider's remote server installs a Code-Server version that doesn't allow the Copilot Chat extension's version.

This could be a [VS-Code-Server](https://github.com/microsoft/vscode) issue.

_____

### VS Code Insider's build details:

Version: 1.79.0-insider
Commit: 9084e081d4e89ed8ab67fce340d573c4e1378939
Date: 2023-05-15T05:24:19.845Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

**Comment by clogwog** [comment]
Well... this is embarrassing. It wasn't just a dns issue, it was a full disconnection issue on the remote aarch64 machine. It was connected to my local machine, but it is using a different interface for the internet.. 

sorry about this. I'll close the issue. 

@ahosker thank you !!
