### ISSUE TITLE
Git model not found.

### ISSUE THREAD

**Issue by TaraPeri** [microsoft/vscode-copilot-release#937]
Getting error message GitHub model not found when asked any question in GitHub chat in VSCode.

![image](https://github.com/microsoft/vscode-copilot-release/assets/160982209/3750feba-fd8c-439d-b0cd-598d265b80ad)

**Comment by goniomdq** [comment]
I'm not the owner of the issue, but I'm having this same issue and this is all the log shows for me:
2024-07-04 13:01:02.727 [error] Activating extension GitHub.copilot-chat failed due to an error:
2024-07-04 13:01:02.727 [error] Error: Git model not found



2024-07-04 14:24:12.771 [info] [extension] Error: Git model not found
    at s.getAPI (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:793736)
    at t.getGitExtensionAPI (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:455:5778)
    at t.get repositories [as repositories] (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:455:6173)
    at t.getRemoteFetchUrls (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:1186:4435)
    at t.shouldFetchContentExclusionRules (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:1186:3642)
    at t.isIgnored (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:1186:3015)
    at A9.isIgnored (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:1186:4992)
    at A9.isCopilotIgnored (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:1186:5190)
    at Rk.get activeTextEditor [as activeTextEditor] (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:797:1940)
    at wS._provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:885:4694)
    at wS.provideResponseWithProgress (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:885:3942)
    at i.y (c:\Users\User\.vscode\extensions\github.copilot-chat-0.12.2\dist\extension.js:897:1063)
    at invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:45409)
    at o.$invokeAgent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:39808)

**Comment by lramos15** [comment]
> github.copilot-chat-0.12.2

You're on an ancient version of chat. Pleas update to 0.17.1. This issue has been fixed

**Comment by goniomdq** [comment]
Thank you. Yes. I had to update my VS code because it wasn't pulling a newer version of the chat (company managed software :( )

**Comment by lramos15** [comment]
Closing as resolved. Please let me know if you still have issues @TaraPeri
