### ISSUE TITLE
Failed to start editor chat

### ISSUE THREAD

**Issue by kudagdel** [microsoft/vscode-copilot-release#964]
Type: <b>Bug</b>

I'm getting below error when I try to use the inline chat

Failed to start editor chat. Please consult the error log and try again later.

Extension version: 0.12.2
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz (16 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (30.58GB free)|
|Process Argv|--crash-reporter-id 2c600598-eac9-425e-807f-9f294ac01271|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30958357
ccp2r6:30958158
dsvsc020cf:30973509

```

</details>

**Comment by kudagdel** [comment]
I tried on a different PC that was freshly built and getting the same error

**Comment by lramos15** [comment]
Please attach your logs.

CMD / CTRL + SHIFT +U -> Copilot Chat

**Comment by altaetran** [comment]
I am getting a similar issue. I am using MacOS with the latest version of copilot: v1.172.0 running over ssh using the  Remote Extension Host. Thank you!

`2024-03-08 00:28:03.642 [error] [ghostText] provideInlineCompletionItems: RangeError: WebAssembly.Memory(): could not allocate memory
    at /home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/node_modules/web-tree-sitter/tree-sitter.js:1:5037
    at new Promise (<anonymous>)
    at Function.init (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/node_modules/web-tree-sitter/tree-sitter.js:1:393)
    at loadWasmLanguage (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/parse.ts:232:18)
    at getLanguage (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/parse.ts:253:34)
    at parseTreeSitter (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/parse.ts:262:36)
    at De.isEmptyBlockStart (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/parseBlock.ts:327:28)
    at Object.isEmptyBlockStart (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/parseBlock.ts:863:39)
    at MessagePort.<anonymous> (/home/altaeth/.vscode-server/extensions/github.copilot-1.172.0/prompt/src/worker.js:18:35)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20) {
  code: undefined
}`

**Comment by altaetran** [comment]
One note, is the issue only seems to be a problem in .py files, as .sh files didn't produce this issue

**Comment by twasson** [comment]
From the moment I click on a file (in my case a ruby file), I see this in the log below for "GiHub Copilot Chat"
Attempting to use the "Start Inline Chat" from context menu leads to the error "Failed to start editor chat"
Tried downgrading from v0.13.0 to v0.12.2, but I no difference. I seem to be in a bad state I can't get out of (also tried uninstalling and reinstalling). Was working for me maybe a week ago, so not sure what changed.

```
2024-03-08 16:44:33.558 [info] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifier failed: TypeError: Cannot read properties of undefined (reading 'apply')
    at t.<computed> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:17037)
    at wasm://wasm/003c790e:wasm-function[20]:0x2cd5
    at wasm://wasm/003c790e:wasm-function[19]:0x28ee
    at wasm://wasm/000b627a:wasm-function[234]:0x25842
    at Parser.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:53813)
    at t.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:956)
    at async Object.pt (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:7544)
    at async MessagePort.<anonymous> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:395:3043)
2024-03-08 16:44:33.559 [info] [RefactorsProvider] RefactorsProvider: getTestableNode failed: TypeError: Cannot read properties of undefined (reading 'apply')
    at t.<computed> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:17037)
    at wasm://wasm/003c790e:wasm-function[20]:0x2cd5
    at wasm://wasm/003c790e:wasm-function[19]:0x28ee
    at wasm://wasm/000b627a:wasm-function[234]:0x25842
    at Parser.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:53813)
    at t.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:956)
    at async Object.ft (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:7863)
    at async MessagePort.<anonymous> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:395:3043)
```

**Comment by EliTheSurfer** [comment]
I am having the same error, i'm not sure why

**Comment by lramos15** [comment]
@EliTheSurfer Are you on the latest VS Code and Copilot Chat verison

**Comment by zack-is-cool** [comment]
This is also not working for me specifically the inline chat and I'm getting this error when clicking start inline chat:

<img width="420" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/24322023/e9448b39-c5ae-4c92-9b76-a2bf13933dd9">

Getting same error with release and pre-release versions, vscode is up to date

Mac os 14.4.1
I'm using code-insiders

### Code insiders info
```
Version: 1.89.0-insider (Universal)
Commit: a2194e8c49790e2139c139a0d986e815ebd43e5b
Date: 2024-04-16T05:51:47.215Z (16 hrs ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

### copilot chat:
GitHub Copilot Chat
v0.15.2024041602 (pre-release)

### copilot:
GitHub Copilot
v1.180.821 (pre-release)


### Logs
``` log
2024-04-16 15:08:54.754 [info] [FetcherService] Using Helix fetcher
2024-04-16 15:08:54.754 [info] [gitExtensionService] Initializing Git extension service.
2024-04-16 15:08:54.754 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-16 15:08:54.754 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-16 15:08:54.754 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-16 15:08:54.754 [info] [auth] Logged in as zack-is-cool
2024-04-16 15:08:56.084 [info] [chat] copilot token chat_enabled: true
2024-04-16 15:08:56.084 [info] [chat] Registration of interactive providers failed:,TypeError: le.interactive.registerInteractiveSessionProvider is not a function
2024-04-16 15:08:56.084 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-16 15:08:56.110 [info] [auth] Got Copilot token for zack-is-cool
2024-04-16 15:08:56.187 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-04-16 15:08:56.187 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-04-16 15:09:40.083 [info] [FetcherService] Using Helix fetcher
2024-04-16 15:09:40.083 [info] [gitExtensionService] Initializing Git extension service.
2024-04-16 15:09:40.422 [info] [auth] Logged in as zack-is-cool
2024-04-16 15:09:40.686 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-16 15:09:40.686 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-16 15:09:40.686 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-16 15:09:40.914 [info] [chat] copilot token chat_enabled: true
2024-04-16 15:09:40.914 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-16 15:09:40.921 [info] [auth] Got Copilot token for zack-is-cool
2024-04-16 15:09:41.196 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-04-16 15:09:41.196 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-04-16 15:10:20.664 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-16 15:10:20.665 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-16 15:10:20.665 [info] [chat fetch] modelMaxResponseTokens 2283
2024-04-16 15:10:20.665 [info] [chat fetch] chat model gpt-4
2024-04-16 15:10:23.010 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2345 ms
2024-04-16 15:10:23.979 [info] [streamChoices] request done: requestId: [fb0e100d-0145-4051-9064-376ec3dfec69] model deployment ID: []
2024-04-16 15:17:16.570 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-16 15:17:16.570 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-16 15:17:16.570 [info] [chat fetch] modelMaxResponseTokens 2296
2024-04-16 15:17:16.570 [info] [chat fetch] chat model gpt-4
2024-04-16 15:17:19.076 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2504 ms
2024-04-16 15:17:24.691 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-16 15:17:24.692 [info] [streamChoices] request done: requestId: [89f24645-38e5-43a9-9684-8cf44a8fc4af] model deployment ID: []
2024-04-16 15:17:24.702 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-16 15:17:24.702 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-16 15:17:24.702 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-16 15:17:24.702 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-16 15:17:25.114 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 411 ms
2024-04-16 15:17:25.135 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-16 15:17:25.136 [info] [streamChoices] request done: requestId: [ca4e5243-b915-4c4f-9a1d-e49f2e9f62bf] model deployment ID: [x4dff5e5d11fc]
2024-04-16 15:24:41.678 [info] [FetcherService] Using Helix fetcher
2024-04-16 15:24:41.679 [info] [gitExtensionService] Initializing Git extension service.
2024-04-16 15:24:41.679 [info] [auth] Logged in as zack-is-cool
2024-04-16 15:24:41.918 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-16 15:24:41.918 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-16 15:24:41.918 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-16 15:24:42.286 [info] [chat] copilot token chat_enabled: true
2024-04-16 15:24:42.286 [info] [chat] Registration of interactive providers failed:,TypeError: le.interactive.registerInteractiveSessionProvider is not a function
2024-04-16 15:24:42.286 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-16 15:24:42.287 [info] [auth] Got Copilot token for zack-is-cool
2024-04-16 15:24:42.463 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-04-16 15:24:42.464 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-04-16 15:29:11.800 [info] [FetcherService] Using Helix fetcher
2024-04-16 15:29:11.801 [info] [gitExtensionService] Initializing Git extension service.
2024-04-16 15:29:11.801 [info] [auth] Logged in as zack-is-cool
2024-04-16 15:29:12.003 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-16 15:29:12.003 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-16 15:29:12.003 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-16 15:29:12.422 [info] [chat] copilot token chat_enabled: true
2024-04-16 15:29:12.422 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-16 15:29:12.425 [info] [auth] Got Copilot token for zack-is-cool
2024-04-16 15:29:12.590 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-04-16 15:29:12.590 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
```

**Comment by zack-is-cool** [comment]
fwiw I just closed all of my vscode windows and reopened and now it's working again 😞

**Comment by twasson** [comment]
> From the moment I click on a file (in my case a ruby file), I see this in the log below for "GiHub Copilot Chat" Attempting to use the "Start Inline Chat" from context menu leads to the error "Failed to start editor chat" Tried downgrading from v0.13.0 to v0.12.2, but I no difference. I seem to be in a bad state I can't get out of (also tried uninstalling and reinstalling). Was working for me maybe a week ago, so not sure what changed.
> 
> ```
> 2024-03-08 16:44:33.558 [info] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifier failed: TypeError: Cannot read properties of undefined (reading 'apply')
>     at t.<computed> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:17037)
>     at wasm://wasm/003c790e:wasm-function[20]:0x2cd5
>     at wasm://wasm/003c790e:wasm-function[19]:0x28ee
>     at wasm://wasm/000b627a:wasm-function[234]:0x25842
>     at Parser.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:53813)
>     at t.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:956)
>     at async Object.pt (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:7544)
>     at async MessagePort.<anonymous> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:395:3043)
> 2024-03-08 16:44:33.559 [info] [RefactorsProvider] RefactorsProvider: getTestableNode failed: TypeError: Cannot read properties of undefined (reading 'apply')
>     at t.<computed> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:17037)
>     at wasm://wasm/003c790e:wasm-function[20]:0x2cd5
>     at wasm://wasm/003c790e:wasm-function[19]:0x28ee
>     at wasm://wasm/000b627a:wasm-function[234]:0x25842
>     at Parser.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:1:53813)
>     at t.parse (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:956)
>     at async Object.ft (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:393:7863)
>     at async MessagePort.<anonymous> (/Users/tmw/.vscode/extensions/github.copilot-chat-0.13.0/dist/worker2.js:395:3043)
> ```

my problem is gone... 👍
